### ISSUE TITLE
REPL windo produces error

### ISSUE THREAD

**Issue by trondhindenes** [adamdriscoll/poshtools#100]
Error: No exports were found that match the constraint ContractName.

VS info:
Microsoft Visual Studio Premium 2013
Version 12.0.30501.00 Update 2
Microsoft .NET Framework
Version 4.5.51641

Installed Version: Premium

LightSwitch for Visual Studio 2013   06191-004-0454001-02625
Microsoft LightSwitch for Visual Studio 2013

Office Developer Tools - May 2014 Update ENU   06191-004-0454001-02625
Microsoft Office Developer Tools for Visual Studio 2013 - May 2014 Update ENU

Team Explorer for Visual Studio 2013   06191-004-0454001-02625
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06191-004-0454001-02625
Microsoft Visual Basic 2013

Visual C# 2013   06191-004-0454001-02625
Microsoft Visual C# 2013

Visual C++ 2013   06191-004-0454001-02625
Microsoft Visual C++ 2013

Visual F# 2013   06191-004-0454001-02625
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06191-004-0454001-02625
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Windows Phone SDK 8.0 - ENU   06191-004-0454001-02625
Windows Phone SDK 8.0 - ENU

ASP.NET and Web Tools   2013.2.50425
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Windows Azure Web Sites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Windows Azure

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.1.20409.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.1
Provides common services for use by Azure Mobile Services and Windows Azure Tools.

Microsoft Advertising SDK for Windows Phone   
Microsoft Advertising SDK for Windows Phone
Build 

NuGet Package Manager   2.8.50313.46
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PowerShell Tools for Visual Studio   1.0
Information about my package

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   12.0.30919.1
Microsoft SQL Server Data Tools

Windows Azure Mobile Services Tools   1.1
Windows Azure Mobile Services Tools

Windows Azure Tools   2.3
Windows Azure Tools for Microsoft Visual Studio 2013 - v2.3.20320.1602

Windows Azure Tools   2.2
Windows Azure Tools for Microsoft Visual Studio 2013 - v2.2.11003.1601

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by AndreSayreMSFT** [comment]
@trondhindenes Are you still seeing this issue on recent builds?

**Comment by AndreSayreMSFT** [comment]
We believe we've fixed this issue since the builds nearly a year ago!  Please reopen if you're still running into this!
