### ISSUE TITLE
Odd Cursor Placement with PowerShell Editor

### ISSUE THREAD

**Issue by emed795** [adamdriscoll/poshtools#103]
There seems to be an odd issue with cursor placement in the PowerShell editor with Visual Studio 2013.

Normally, when you click to the far end of the line in VS the cursor will be placed at the end of the whitespace on that line but in the PowerShell editor the cursor is arbitrarily placed where the pointer is even if it extends past the available whitespace on that line.

![powershell whitespace](https://cloud.githubusercontent.com/assets/208549/3113460/8a1c9204-e6d8-11e3-82cf-fdb2ab283c60.png)

In the screenshot above, the cursor is placed beyond the amount of whitespace on the line which is visualized as small dots in the editor.

Also, when navigating around using the arrow keys when the end of whitespace is reached the cursor should automatically wraps around to the next line in the editor but in the PowerShell editor it keeps moving beyond the edge of whitespace on the line.

**Comment by AndreSayreMSFT** [comment]
@emed795 Thanks for reporting this!  I can't seem to reproduce this when I have virtual space off, and this only shows up, as it should, when 'Enable Virtual Space' is enabled.

Is it still showing up when the below option is disabled?

![image](https://cloud.githubusercontent.com/assets/10080679/6798063/a43f2c30-d1c6-11e4-8c80-c89ff998d236.png)

**Comment by AndreSayreMSFT** [comment]
Please let us know if you still encounter this, and don't hesitate to reopen this if you do!
