### ISSUE TITLE
Conflict With Nuget Package Manager Console

### ISSUE THREAD

**Issue by benmetheny** [adamdriscoll/poshtools#108]
This happens in both VS2012 and 2013 with latest version installed (it also existed in at least the previous released version as well) and could possibly involve an as yet unknown third extension if I'm the only one seeing this. When I have PoSh Tools enabled and try to open the PMC I only see 'Object reference not set to an instance of an object.' in red. I've tried renaming my default PoSh profile and restarting VS and my nuget profile is empty so I don't think it's any PoSh modules that are loaded. This entirely breaks Nuget as I cannot install or update packages from the console or the GUI interface when the error is present.

I'm not sure if this is related, but after disabling PoSh Tools extension and restarting VS, I do see this error message in PMC:
<b>Could not load file or assembly 'Microsoft.PowerShell.Security' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))</b>
However PMC does load and work correctly.

Like I said, it could be a combination conflict with another extension as I have numerous installed including Resharper 8.2 (although I have tried disabling that). If there is any diagnostic info I can provide to help let me know.

**Comment by adamdriscoll** [comment]
I'm assuming this is fixed. Thanks!
