### ISSUE TITLE
Output window confusion

### ISSUE THREAD

**Issue by moswald** [adamdriscoll/poshtools#109]
When opening my solution and hitting F5, I get this in the PowerShell Debug Interactive window:

    [ERROR] C:\Users\Matt\projects\personal\pstest\pstest.ps1 : Object reference not set to an instance of an object.
    [ERROR] At line:1 char:1
    [ERROR] + & 'C:\Users\Matt\projects\personal\pstest\pstest.ps1'
    [ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    [ERROR]     + CategoryInfo          : NotSpecified: (:) [pstest.ps1], NullReferenceException
    [ERROR]     + FullyQualifiedErrorId : System.NullReferenceException,pstest.ps1
    [ERROR]  

After that, if I set the execution policy in the interactive window:

    PS C:\Users\Matt\projects\personal\pstest> set-ExecutionPolicy unrestricted

and then I can run just fine, *except* everything is sent to this window, instead of to Output. It's not a big deal, but it's not what I expected.

I have the option to override the execution policy set to true in VS.

(This happens every time I start VS.)

**Comment by adamdriscoll** [comment]
The Set-ExecutionPolicy issue has been fixed and output now goes to both the Output Window and the REPL window.
