### ISSUE TITLE
$host.UI.PromptForChoice doesn't work

### ISSUE THREAD

**Issue by SuperJMN** [adamdriscoll/poshtools#120]
Code like this doesn't prompt.

```
$Title = "Welcome"
$Info = "Just to Demo Promt for Choice"

$options = [System.Management.Automation.Host.ChoiceDescription[]] @("&Power", "&Shell", "&Quit")
[int]$defaultchoice = 2
$opt =  $host.UI.PromptForChoice($Title , $Info , $Options,$defaultchoice)
switch($opt)
{
    0 { Write-Host "Power" -ForegroundColor Green}
    1 { Write-Host "Shell" -ForegroundColor Green}
    2 {Write-Host "Good Bye!!!" -ForegroundColor Green}
}
```

I'm afraid it doesn't Read-Host, neither.
##

**Comment by AndreSayreMSFT** [comment]
To add to this, we need to implement:

        public override int PromptForChoice(string caption, string message, Collection<ChoiceDescription> choices,
            int defaultChoice)
        {
            return 0;
        }


and

        public override Dictionary<string, PSObject> Prompt(string caption, string message,
            Collection<FieldDescription> descriptions)
        {
            return null;
        }

in VSXHost.cs

**Comment by Pieter-Veenstra** [comment]
I'm running into the same issue with PromptForChoice. When is this expected to be addressed?

**Comment by adamdriscoll** [comment]
This is fixed in recent versions.
