### ISSUE TITLE
Cannot drag & drop projects into Solution Folders

### ISSUE THREAD

**Issue by SuperJMN** [adamdriscoll/poshtools#125]
- Given PowerShell solution with Solution Folders (not folders inside a Project)
- When you try to move (with drag&drop)  a Project inside a solution folder
- EXPECTED: The project is moved into the solution folder on drop
- ACTUAL: The project remains in the same place. It has no effects.

WORKAROUND: If you unload the project before doing the Drag&Drop operation, it works OK. Later you can reload the project and the changes are persisted correctly in the .sln file.
##

**Comment by adamdriscoll** [comment]
Fixed with in 513.
