### ISSUE TITLE
VERY slow performance with PowerShell addin when working with PowerShell projects

### ISSUE THREAD

**Issue by ChrisLynchHP** [adamdriscoll/poshtools#133]
I am using VS 2013 with Update 3 (12.0.30723.00), and the 1.0.4 build (was using 1.0.0 previously) and when I type into the editor, performance is very slow.  Scrolling is just fine, moving the cursor is also fine.  But typing, it will take about 2 seconds to display a single character.  Is this a known issue?  Any way of fixing this?  My system is a Surface Pro 3 with the Core i5 processor (Windows 8.1, not Windows 10 Preview), so I have enough resources.

**Comment by AndreSayreMSFT** [comment]
@ChrisLynchHP There have been some recent improvements, but there's definitely more that we're able to do.  What size of PowerShell script are you using when you encounter this?

**Comment by ChrisLynchHP** [comment]
Including comments and blank lines, roughly 21000 lines.

**Comment by AndreSayreMSFT** [comment]
That's quite a PS file, and definitely on the larger size of PS files we've come across!

@adamdriscoll has done some [great work](https://github.com/adamdriscoll/poshtools/releases/tag/v1.0.5) for his 1.0.5 builds to bring some processing into background threads when possible.  Do these improvements make things better for you?

**Comment by ChrisLynchHP** [comment]
This is a PS Module, not just a script file.

Sent from my Windows Phone
________________________________

**Comment by lzybkr** [comment]
How does performance compare with the ISE?  Neither tool does incremental parsing, which for scripts up to 2-3K lines seems to be acceptable.

It's quite common for large modules to use multiple ps1 files that are all dot sourced in the main psm1 file.  This is a good solution to make editing a more reasonable experience.

**Comment by ChrisLynchHP** [comment]
The ISE performs just fine. My wish for the ISE was a better way to navigate around functions and better publishing and code management VS provides. FunctionExplorer for the ISE just isn't great, and has a number issues itself. Would love to use VS for my POSH development.

Sent from my Windows Phone
________________________________

**Comment by AndreSayreMSFT** [comment]
@ChrisLynchHP And we want to make the experience on VS awesome for you as well! :D  Any word if the latest builds of the PoshTools alleviates some of your pain?

**Comment by ChrisLynchHP** [comment]
I have 1.0.5, and it does not. Are there newer compiled builds,or do you have a specific commit you want me to test/try?

Sent from my Windows Phone
________________________________

**Comment by AndreSayreMSFT** [comment]
@ChrisLynchHP Ah, was just looking for a check on 1.0.5 - Interesting that the ISE performs well for you, but the VS tools don't upon typing. We'll definitely be taking a look. Is it [this](https://github.com/HewlettPackard/POSH-HPOneView/blob/master/HPOneView.120.psm1) PS Module you're using?

In the interim, while we continue to make improvements, hopefully @lzybkr's suggestion will reduce pain.

**Comment by ChrisLynchHP** [comment]
Yep. That is the psm1 file that I develop and maintain.

Sent from my Windows Phone
________________________________

**Comment by AndreSayreMSFT** [comment]
@ChrisLynchHP Good news!  We think we've identified and fixed this issue.  We can't make the PowerShell parser any faster, but we can move it to the background, and not block the editor!

Would you be willing to verify with our latest [nightly](https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev/artifacts) build?

**Comment by ChrisLynchHP** [comment]
Sure. I will test over the next few days and report back.

Sent from my Windows Phone
________________________________

**Comment by ChrisLynchHP** [comment]
I just tested the nightly build on a brand new VS2013.4 install.  I loaded my current PSM1 file, and typing is vastly improved.  Color syntax highlighting is a bit off (processing wise, which you stated above), but it is usable.  I'll continue to test and report back.

**Comment by ChrisLynchHP** [comment]
Performance is very nice. I did run into just one application exception, although VS2013.4 didn't crash itself and I haven't run into it since.

One question I did have, is there any way to support when double-clicking a variable that the $ not be selected, or is that completely controlled by VS?

**Comment by adamdriscoll** [comment]
I think that's the way the ISE work, right? We could probably do that. Could you enter a new issue about it?

**Comment by ChrisLynchHP** [comment]
Sure.  In your repo @adamdriscoll  or MS's?

**Comment by adamdriscoll** [comment]
You can throw it in this one.

**Comment by AndreSayreMSFT** [comment]
@ChrisLynchHP Glad to hear your perf issues were fixed!

Closing out this issue, but is the exception that you ran into the same issue as found at https://github.com/Microsoft/poshtools/issues/109 ?

**Comment by ChrisLynchHP** [comment]
Looking at the ActivityLog.xml file, yes, the exact same error message.
