### ISSUE TITLE
tab completion works only after partially completing the cmdlet

### ISSUE THREAD

**Issue by rchaganti** [adamdriscoll/poshtools#14]
Typing Get and then tab does not bring the tab completion to work. If we need to see all Get* cmdlets, we need to do Get- and then choose from intellisense list. Also, Get- and Tab does not cycle between the available cmdlets.

**Comment by AndreSayreMSFT** [comment]
Similar to #13

**Comment by AndreSayreMSFT** [comment]
Fixed!
