### ISSUE TITLE
[Colorization] No sysntax colorization when editing files but it shows up when reopened

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [adamdriscoll/poshtools#143]
Seems like a regression since refactoring with async

**Comment by sunmorgus** [comment]
Experiencing the same issue. Using Visual Studio 2013 Update 4. It doesn't affect the entire file, just from the point you start editing and below. Also, doesn't occur all the time, only occasionally. Any other info you need, I'd be happy to provide.

**Comment by HuanhuanSunMSFT** [comment]
The latest one seems to have fixed this issue. I haven't seen it repo'd again. BTW, not sure if the recent commits with ISE colors has been merged to this repo. @adamdriscoll @AndreSayreMSFT

**Comment by sunmorgus** [comment]
I'm using version 1.0.5 and still having this issue.

**Comment by AndreSayreMSFT** [comment]
@HuanhuanSunMSFT : Nope, the recent commits haven't been pulled into this repo yet.
@sunmorgus : We have a recent experimental build that you can find [here](https://ci.appveyor.com/api/buildjobs/lsvicu7gwpvdap0j/artifacts/Binaries/Release12.0/PowerShellTools.vsix).  Would you be willing to see if this issue still shows up for you in that build?

**Comment by sunmorgus** [comment]
Sorry for the late reply. Installed the experimental build just now, and that appears to be working MUCH better.

**Comment by AndreSayreMSFT** [comment]
Hooray!
