### ISSUE TITLE
[Debug] Debugging interactive window shows error instead of evaluating during debugging

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [adamdriscoll/poshtools#146]
During debugging: Interactive window evaluate doesn't work  
Error: Pipeline not run because a pipeline is already running. Pipelines cannot be run concurrently.

**Comment by EricMSFT** [comment]
Fixed in Microsoft/posh repo

**Comment by AndreSayreMSFT** [comment]
Closing out this issue as it's fixed in the other repo.
