### ISSUE TITLE
Attach to Process broken in VS 2013 Ultimate

### ISSUE THREAD

**Issue by lzybkr** [adamdriscoll/poshtools#152]
This extension is causing a crash in VS 2013 Ultimate when I choose "Debug|Attach to Process...".
To repro, start a new instance of VS 2013.
Press Ctrl+Alt+P.  That's it, simple repro, you don't need any open files or solutions.
When I disable the extension, the crash goes away.

**Comment by AndreSayreMSFT** [comment]
Keeping this open until we bring the fix [ #153 ] up!  Thanks for bringing the issue to our attention!
