### ISSUE TITLE
Exception in VS2015 witn poshtools installed

### ISSUE THREAD

**Issue by dtewinkel** [adamdriscoll/poshtools#154]
Hi,

With poshtools installed, when loading my project I get the following pop-up:
![exception](https://cloud.githubusercontent.com/assets/2182654/5517977/690f7816-890c-11e4-956f-160f33e7f0c0.png)
The ActivityLog.xml contains a number of entries with:
```xml
  <entry>
    <record>590</record>
    <time>2014/12/21 11:08:37.581</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: classification&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.ClassificationSpan..ctor(SnapshotSpan span, IClassificationType classification)&#x000D;&#x000A;   at PowerShellTools.Classification.PowerShellClassifier.FillClassificationGap(List`1 classifications, Nullable`1 lastClassificationSpan, Span newClassificationSpan, ITextSnapshot currentSnapshot, IClassificationType classificationType)&#x000D;&#x000A;   at PowerShellTools.Classification.PowerShellClassifier.AddTokenClassifications(ITextBuffer buffer, SnapshotSpan span, List`1 classifications, Nullable`1 lastClassificationSpan, IClassificationType gapType)&#x000D;&#x000A;   at PowerShellTools.Classification.PowerShellClassifier.VirtualGetClassificationSpans(SnapshotSpan span)&#x000D;&#x000A;   at PowerShellTools.Classification.Classifier.GetClassificationSpans(SnapshotSpan span)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.&lt;GetTags&gt;d__0.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__2.MoveNext()</description>
  </entry>
``` 
This is in VS2015 Preview version.
I open a normal C# library project with a few PowerShell scripts in it (`*.ps1`). I noted that before installing the poshtools there was already syntax highlighting, but unfortunately no intellisense. After installing poshtools to get it all I get the exception now. Most of the syntax highlighting is gone, but intellisense seems to work and there is this exception on load of the project.

With regards,

Daniël

**Comment by AndreSayreMSFT** [comment]
@dtewinkel I'm trying to reproduce the problem -- Are you able to provide:

The version number of Visual Studio [from the Help->About pane]
The version number of PoshTools
Does it happen even on the simplest of .ps1 files?

Does it still happen with [this](https://ci.appveyor.com/api/buildjobs/g9jcpxv4g7hmlbqm/artifacts/Binaries/Release12.0/PowerShellTools.vsix) experimental build?

Thanks!

**Comment by dtewinkel** [comment]
Hi Andre,

 

Thanks for your response. 

 

Visual studio version is: 



 

Posh tools version is 1.0.5:



 

To reproduce the issue, I just create a simple project and added a .ps1 file. It gave the following exception:



 

Re-opening the solution gives the same exception. 

 

The experimental build seems to make no difference. It now opens a PowerShell command window :(.

 

I attached the solution I created to reproduce the issue. 
With PoshTools installed I have virtually no syntax highlighting.

 



Without PoshTools it looks like: 

 



The issue also shows with a simple file with just “Write-Host "Hello"” in it :(.

 

In case it matters, I am running Windows 8.1.

 

With regards,

 

Daniël

 

Van: Andre Sayre [mailto:notifications@github.com] 
Verzonden: vrijdag 16 januari 2015 3:57
Aan: adamdriscoll/poshtools
CC: dtewinkel
Onderwerp: Re: [poshtools] Exception in VS2015 witn poshtools installed (#154)

 

@dtewinkel <https://github.com/dtewinkel>  I'm trying to reproduce the problem -- Are you able to provide:

The version number of Visual Studio [from the Help->About pane]
The version number of PoshTools
Does it happen even on the simplest of .ps1 files?

Does it still happen with this <https://ci.appveyor.com/api/buildjobs/g9jcpxv4g7hmlbqm/artifacts/Binaries/Release12.0/PowerShellTools.vsix>  experimental build?

Thanks!

**Comment by AndreSayreMSFT** [comment]
@dtewinkel I think a bunch of images didn't get sent to GitHub during the reply-via-email.

**Comment by dtewinkel** [comment]
Hi Andre,

That a shame that image from an e-mail are not copied into the GitHub comment. So now the bits with the images:

Visual studio version is:
![vsversion](https://cloud.githubusercontent.com/assets/2182654/5788217/b583f290-9e28-11e4-8349-5ec14dad9f93.png)

Posh tools version is 1.0.5:
![poshversion](https://cloud.githubusercontent.com/assets/2182654/5788218/be04f2a2-9e28-11e4-8301-7745fbfe456d.png)

To reproduce the issue, I just create a simple project and added a .ps1 file. It gave the following exception:
![exception](https://cloud.githubusercontent.com/assets/2182654/5788227/56cf23f4-9e29-11e4-82b8-f2e33e72a902.png)

Re-opening the solution gives the same exception.

The experimental build seems to make no difference. It now opens a PowerShell command window :(.

I attached the solution I created to reproduce the issue.
With PoshTools installed I have virtually no syntax highlighting.
![code1](https://cloud.githubusercontent.com/assets/2182654/5788228/63f78dd2-9e29-11e4-863f-c4d1a6d95a80.png)

Without PoshTools it looks like:
![code2](https://cloud.githubusercontent.com/assets/2182654/5788229/6edb6886-9e29-11e4-9a55-248c915ed844.png)

To reproduce I created a simple Class library and added a ps1 file.

**Comment by AndreSayreMSFT** [comment]
Hi @dtewinkel !  Visual Studio 2015 CTP 6 has been released, and fixes a few issues.  Does the combination of the latest CTP + the latest dev build https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev/artifacts fix things up?

[I am still unable to reproduce this issue locally :(]

**Comment by dtewinkel** [comment]
hi @AndreSayreMSFT,
Yes, it looks like this combination does work :smile:. 
I did a quick check. I see no exception anymore and the syntax highlight now works again.

**Comment by AndreSayreMSFT** [comment]
Glad to hear it!
