### ISSUE TITLE
PowerShell Projects Properties Page Polish

### ISSUE THREAD

**Issue by AndreSayreMSFT** [adamdriscoll/poshtools#158]
We need to polish up the project properties page, as the text boxes don't always display completely.  They don't flow.  We would also need to ensure [unknown to me currently] that all options can be successfully used.

![image](https://cloud.githubusercontent.com/assets/10080679/5654888/9a6348f2-967c-11e4-8b77-aa588452762c.png)

**Comment by ChrisLynchHP** [comment]
I reported this in Issue #132.  Maybe merge the two and hopefully fix?

**Comment by adamdriscoll** [comment]
The project system needs a little work in general. I'm pretty sure these options don't do anything at the moment.
