### ISSUE TITLE
REPL Window Parameter Intellisense for CmdLets different than Editor

### ISSUE THREAD

**Issue by AndreSayreMSFT** [adamdriscoll/poshtools#162]
For example, Get-ExectionPolicy doesn't display list as one of the params in the REPL window when hitting '-'.

Expected:
![image](https://cloud.githubusercontent.com/assets/10080679/5756247/325bc694-9c62-11e4-8759-89adccc763b5.png)

Actual: 
![image](https://cloud.githubusercontent.com/assets/10080679/5756263/4a5f1aa2-9c62-11e4-99da-0114f9c61534.png)

**Comment by HuanhuanSunMSFT** [comment]
REPL Window Parameter Intellisense completions never change per cmdlet, meaning they always show the same completion list.

**Comment by HuanhuanSunMSFT** [comment]
Fixed in Microsoft/poshtools
