### ISSUE TITLE
Extension does not install on machines that only have .NET 4.6

### ISSUE THREAD

**Issue by AndreSayreMSFT** [adamdriscoll/poshtools#165]
If a machine only has .NET 4.6 installed, the current VSIX doesn't install.

1/19/2015 1:09:34 PM - 	SupportedFrameworkVersionRange : [4.5]

1/19/2015 1:10:36 PM - Beginning to install extension to Microsoft Visual Studio Ultimate 2015 RC...
1/19/2015 1:10:37 PM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'PowerShell Tools for Visual Studio 2013' requires a version of the .NET Framework that is not installed.

![image](https://cloud.githubusercontent.com/assets/10080679/5824265/458959e0-a098-11e4-9574-9f492fe32e6c.png)

**Comment by masaeedu** [comment]
The fix is apparently to target `[4.5,)` in the vsix manifest, instead of `4.5`.
