### ISSUE TITLE
Visual Studio doesn't find my pester tests.

### ISSUE THREAD

**Issue by luck02** [adamdriscoll/poshtools#166]
When I run tests - run all I get:

Method not found: 'System.String Microsoft.VisualStudio.TestPlatform.ObjectModel.ValidateArg.NotNullOrEmpty(System.String, System.String)'.

My resharper test window is empty, essentially VS is unable to find my tests.

Is there some convention I may be missing, or is this related to the above error message.

WIndows 7 x64
SP1

VS 2013 
12.0.21004.1 REL

I can't find a version # on my poshtools install, but I downloaded it this morning.

**Comment by adamdriscoll** [comment]
Tests should be in files named: *.Tests.ps1. Do you see tests in the Visual Studio Test Explorer window?

**Comment by luck02** [comment]
That's how their named right now, I don't see anything in the visual studio test explorer window, see screen shot.

Also, thank you very much for responding.

![posttoolstesting](https://cloud.githubusercontent.com/assets/364095/5903751/5dc66ecc-a538-11e4-80f1-12400636dd25.JPG)

**Comment by adamdriscoll** [comment]
Can you look in the output window and see if there is anything in there about test discovery?

**Comment by luck02** [comment]
All I get is the message from above:  It's definitly related, if I clear the output window and then run the tests I see the message again (And it's obviously related in the namespace)
![poshtoolscaptureoutput](https://cloud.githubusercontent.com/assets/364095/5903918/65ba9440-a539-11e4-8eb2-2cdd6a0e084c.JPG)

**Comment by adamdriscoll** [comment]
Sounds like it actually might be an issue with the Release version of Visual Studio. Since PoshTools was developed against newer updates, this likely may be the issue. Python Tools has a similar issue: https://pytools.codeplex.com/workitem/2814

Can you install updates to VS to see if that resolves the issue?

**Comment by luck02** [comment]
I thought I was up to date,  I will definitely check that out.

G

**Comment by luck02** [comment]
No error message... :+1: 

No tests show up either though :-1:

The tests do work with 'Invoke-Pester' in a parent directory finds and runs all the tests.  

Any further investigation I can do here to help out?

**Comment by adamdriscoll** [comment]
Nothing interesting in the output pane?

**Comment by luck02** [comment]
nope, zilch.  No errors...  Nothing :(

**Comment by luck02** [comment]
Ok, new info.

When I close and re-open the project I get thsi in the output window:

------ Load Playlist started ------
========== Load Playlist finished (0:00:00.0010002) ==========
------ Discover test started ------
Searching for tests in [C:\Dev\tools-scripts\TaskAutomationScripts\ServerProvisioning\ServerProvisioning\commandgenerator\commandGenerator.ps1].
Searching for tests in [C:\Dev\tools-scripts\TaskAutomationScripts\ServerProvisioning\ServerProvisioning\configvm\configvm.ps1].
Searching for tests in [C:\Dev\tools-scripts\TaskAutomationScripts\ServerProvisioning\ServerProvisioning\Deploy.ps1].
Searching for tests in [C:\Dev\tools-scripts\TaskAutomationScripts\ServerProvisioning\ServerProvisioning\deployvm\deployvm.ps1].
Searching for tests in [C:\Dev\tools-scripts\TaskAutomationScripts\ServerProvisioning\ServerProvisioning\Helpers\DomainNameParser.ps1].
Searching for tests in [C:\Dev\tools-scripts\TaskAutomationScripts\ServerProvisioning\ServerProvisioning\Helpers\DomainNameParser.Tests.ps1].
An exception occurred while test discoverer 'PowerShellTestDiscoverer' was loading tests. Exception: Object reference not set to an instance of an object.
========== Discover test finished: 0 found (0:00:00.5471094) ==========

**Comment by adamdriscoll** [comment]
@luck02 Is there any way you could provide DOmainNameParser.Tests.ps1 for me to take a look?

**Comment by iainbrighton** [comment]
I seem to have a related issue - no tests are discovered in test explorer. Blank. Nada.

From the the Debug Interactive window, if I navigate to the project folder I can run Invoke-Pester and the tests execute successfully. 

I don't get any error/warning in the tests output window either..? This is with the latest development build (not on the MSFT fork).

**Comment by luck02** [comment]
Hi, my appologies for not following up on this.

I ran out of time and handed off what I was doing to another developer.  I had to reverse out the changes I had made as it was not working as expected.  So I don't have the code in it's original form.

But here's what was probably in one of the tests file (I don't think it will have changed) I can't reproduce the rest of the issue without substantial effort:

{code}
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path).Replace(".Tests.", ".")
. "$here\$sut"

Describe "ParseHostName without team component" {

    It "Can Tell if the hostname does not have a team component" {
        $HostComponents = ParseHostName "VVD-IIS001"
        $hostComponents.Team | should be ""
    }

    It "Can find the environment" {
        $HostComponents = ParseHostName "VVD-IIS001-SITH"
        $hostComponents.Environment | should be "VVD"
    }

    It "Can find the machine type" {
        $HostComponents = ParseHostName "VVD-PRO001"
        $hostComponents.MachineType | should be "PRO"
    }

    It "Can find the machine type" {
        $HostComponents = ParseHostName "VVD-PRO001"
        $hostComponents.MachineNumber | should be "001"
    }

}

Describe "ParseHostName with team component" {
    It "Can Tell if the hostname has a team component" {
        $HostComponents = ParseHostName "VVD-IIS001-SITH"
        $hostComponents.Team | should be "SITH"
    }

        It "Can find the environment" {
        $HostComponents = ParseHostName "VVD-IIS001-SITH"
        $hostComponents.Environment | should be "VVD"
    }

    It "Can find the machine type" {
        $HostComponents = ParseHostName "VVD-PRO001-SITH"
        $hostComponents.MachineType | should be "PRO"
    }

    It "Can find the machine type" {
        $HostComponents = ParseHostName "VVD-PRO001-SITH"
        $hostComponents.MachineNumber | should be "001"
    }
}
{code}

**Comment by theficus** [comment]
I don't see any Pester tests either and my project is made up entirely of Foo.ps1/Foo.Tests.Ps1 pairs.

**Comment by adamdriscoll** [comment]
@theficus  Can you try this build to see if it resolves your issue? https://ci.appveyor.com/project/adamdriscoll/poshtools/branch/testadapter/artifacts

**Comment by adamdriscoll** [comment]
@luck02 I think your issue may be fixed here as well. The adapter was requiring Context blocks which you did not have in your tests. This version fixes that.

**Comment by theficus** [comment]
It does appear to be working for me in the latest build! Thanks!

**Comment by adamdriscoll** [comment]
@luck02 I've actually changed the behavior in the latest dev build. It no longer even finds Context\It blocks because Pester really can't run at that granularity. For now, I've changed it to only find Describe blocks.
