### ISSUE TITLE
Convert-Path . returns "C:\Windows\system32" script isn't there

### ISSUE THREAD

**Issue by luck02** [adamdriscoll/poshtools#169]
So all dot-source breaks if using relative paths.

Is there a setting for this, the plugin obviously over rides the environment.
##

**Comment by luck02** [comment]
Set-Location $PSScriptRoot

Seems to resolve for my purposes, but I bet there's side effects.

**Comment by AndreSayreMSFT** [comment]
Thanks for bringing this to our attention!

Played around with this a little bit: The default setting for `.` paths matches the current location in the REPL Window.  When following this within the PowerShell ISE, we get the same behavior.

The only side-effect I can think of by setting the $PSScriptRoot is that it'll set the Location within the REPL Window.  

Brainstorming a few things we may want to do to improve the experience though:
1) Set the default location to something friendlier.  Maybe the user Profile directory.  [Eg, C:\Users\Andre\]

2) Set the location upon running a script.  But this has side effects for the entire PS environment as mentioned above.

**Comment by luck02** [comment]
PowerShell ISE is a POS though...  Sorry, try not to rant. 

But, it's quite frustrating that we have a reasonable scripting environment and the company that built it is primarily known for offering a good IDE experience didn't bother offering that (one good feature across all it's products) for the scripting environment.

**Comment by bmoore-msft** [comment]
@luck02 - can you give a little more detail about your scenario - or what think the right solution is here?  I'm not quite following and don't want to assume...

**Comment by AndreSayreMSFT** [comment]
What about having it match the Solution location, for the path?

**Comment by luck02** [comment]
@bmoore-msft 

I'm not sure what the actual underlying problem is, for some reason the script execution directory is c:\windows\system32.

Whereas the script may be executing (As an example) c:\dev\devProject\powershells\script.ps1

My assumption is that the script should execute in it's directory, not in the system directory.

**Comment by bmoore-msft** [comment]
@luck02 - Gary, I agree that's what you should see... but where are you seeing that the execution dir is %system%?  If I run the following script:

write-host $PSScriptRoot
write-host $(Convert-Path .)

I see what I would expect... the script root is where the script is located on disk and " . " is the path of the execution environment (i.e. the powerShell prompt).  If you're seeing something different can you share a script snippet and how you're executing it?
