### ISSUE TITLE
Executing a selection doesn't execute if the area is selected from bottom to top

### ISSUE THREAD

**Issue by simonsabin** [adamdriscoll/poshtools#173]
When you select an area from bottom to top, and then execute the selection nothing is executed and the selected area changes to be just the top line.

To repro.
Move the cursor to the bottom of the area to execute. 
Hold shift and click at the top of the area to be executed. 
Select execute selection

After execution just the area selected changes to be just the first line.

**Comment by AndreSayreMSFT** [comment]
Playing around with this, the only time we should auto select anything, eg, the entire line, is when /nothing/ is selected.

With a partial selection, and this matches ISE behavior, we should run only what is selected, even if it is a partial line.
