### ISSUE TITLE
ImportCardinalityMismatchException prevents initialization

### ISSUE THREAD

**Issue by abrobston** [adamdriscoll/poshtools#178]
Possibly related to #160.  Running VS2013 Premium, Update 4, on Windows 7 x64.  I have Windows Management Framework and PowerShell 4 installed via [`cinst powershell`](https://chocolatey.org/packages/PowerShell).  Attempting to use PowerShell Tools version 1.0.5 as installed from the Extensions and Updates dialog within Visual Studio.

On starting Visual Studio, I get the following:

![image](https://cloud.githubusercontent.com/assets/400286/6081644/e5a5bf86-ade0-11e4-9322-ff9554150b3f.png)

There are no obvious issues in the activity log; in fact, it reports success:

    <entry>
      <record>135</record>
      <time>2015/02/06 15:03:56.600</time>
      <type>Information</type>
      <source>Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost</source>
      <description>Successfully loaded component assembly from cache</description>
      <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\WINDOWS AZURE TOOLS\COMMON\Microsoft.VisualStudio.PowerShellTools.Package.dll</path>
    </entry>
    ...
    <entry>
      <record>221</record>
      <time>2015/02/06 15:03:56.602</time>
      <type>Information</type>
      <source>Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost</source>
      <description>Successfully loaded component assembly from cache</description>
      <path>C:\USERS\ANDBROB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\12.0\EXTENSIONS\UK2LCQVF.5WK\Microsoft.VisualStudio.PowerShellReplWindow.dll</path>
    </entry>
    ...
    <entry>
      <record>228</record>
      <time>2015/02/06 15:03:56.602</time>
      <type>Information</type>
      <source>Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost</source>
      <description>Successfully loaded component assembly from cache</description>
      <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\COMMON7\IDE\EXTENSIONS\DT1USPVX.LTW\NuGetConsole.Host.PowerShellProvider.dll</path>
    </entry>
    ...
    <entry>
      <record>307</record>
      <time>2015/02/06 15:03:56.949</time>
      <type>Information</type>
      <source>VisualStudio</source>
      <description>Begin package load [PowerShellToolsPackage]</description>
      <guid>{58DCE676-42B0-4DD6-9EE4-AFBC8E582B8A}</guid>
    </entry>
    <entry>
      <record>308</record>
      <time>2015/02/06 15:03:57.032</time>
      <type>Information</type>
      <source>VisualStudio</source>
      <description>Entering function CVsPackageInfo::HrInstantiatePackage</description>
      <guid>{6E87CFAD-6C05-4ADF-9CD7-3B7943875B7C}</guid>
    </entry>
    <entry>
      <record>309</record>
      <time>2015/02/06 15:03:57.032</time>
      <type>Information</type>
      <source>VisualStudio</source>
      <description>Begin package load [Visual Studio Common IDE Package]</description>
      <guid>{6E87CFAD-6C05-4ADF-9CD7-3B7943875B7C}</guid>
    </entry>
    <entry>
      <record>310</record>
      <time>2015/02/06 15:03:57.041</time>
      <type>Information</type>
      <source>VisualStudio</source>
      <description>End package load [Visual Studio Common IDE Package]</description>
      <guid>{6E87CFAD-6C05-4ADF-9CD7-3B7943875B7C}</guid>
    </entry>
    <entry>
      <record>311</record>
      <time>2015/02/06 15:04:00.458</time>
      <type>Information</type>
      <source>VisualStudio</source>
      <description>End package load [PowerShellToolsPackage]</description>
      <guid>{58DCE676-42B0-4DD6-9EE4-AFBC8E582B8A}</guid>
    </entry>

Any help?

**Comment by adamdriscoll** [comment]
Wow, that's really weird. Haven't seen that one before. Can you try a different build to see if it happens there? https://ci.appveyor.com/project/adamdriscoll/poshtools/build/artifacts

**Comment by abrobston** [comment]
With the build you provided, I no longer get the error.  If I can provide further information, let me know.
