### ISSUE TITLE
Syntactical highlighting disappears on the line you're editing until you scroll off scren and come back

### ISSUE THREAD

**Issue by etriebe** [adamdriscoll/poshtools#179]
Seems to only have started happening in the latest update.

**Comment by AndreSayreMSFT** [comment]
Hi @etriebe !  Thanks for reporting this!  We've made some changes in this space that'll hopefully fix things up.  Would you be able to verify it's patched up for you in our latest build found [here](https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev/artifacts)?

**Comment by etriebe** [comment]
Yes, that patched build from that location fixes this issue.
