### ISSUE TITLE
PowerShell V2 Support

### ISSUE THREAD

**Issue by TheSemicolon** [adamdriscoll/poshtools#18]
Is there a plan to support PowerShell v2? We will not be upgrading the PowerShell instance on Server 2008 machines and do not plan to roll out Server 2012 for some time. I have been VERY reliant on the old PowerGuiVSIX project, and I would like to keep all my development within the Visual Studios...

**Comment by AndreSayreMSFT** [comment]
Unfortunately, PowerShell 2.0 doesn't support a bunch of the features we need for full-fledged editor support.
