### ISSUE TITLE
Selecting an open bracket doesn't highlight the closing bracket

### ISSUE THREAD

**Issue by Magissia** [adamdriscoll/poshtools#181]
Selecting an open bracket/parentheses should show the closing one and vice-versa

**Comment by AndreSayreMSFT** [comment]
Fantastic feedback, @Magissia !  Added this to the backlog for something that we can improve!

**Comment by AndreSayreMSFT** [comment]
Related to #104 and https://github.com/Microsoft/poshtools/pull/117

**Comment by bmoore-msft** [comment]
I'd like to see us pull this in with the other brace/bracket matching work, I was thinking that was part of the work in my head, even though I didn't write it down :)

**Comment by HuanhuanSunMSFT** [comment]
Fixed in https://github.com/Microsoft/poshtools/pull/382

**Comment by Magissia** [comment]
Thanks
