### ISSUE TITLE
Dev Build from 2/18/2015 Changed My Syntax Highlighting

### ISSUE THREAD

**Issue by smaglio81** [adamdriscoll/poshtools#189]
Hey,

I mentioned on [Visual Studio Gallery Q&A](https://visualstudiogallery.msdn.microsoft.com/c9eb3ba8-0c59-4944-9a62-6eee37294597) that after installing the dev build from 2/18/2015 all of my syntax highlighting was changed.

I did have the current download from the Visual Studio Gallery installed before, which was normal. At that time, the Dark Theme I used looked exactly like the images on http://adamdriscoll.github.io/poshtools/.

Now it looks like this:

![image](https://cloud.githubusercontent.com/assets/169953/6306010/80b9809e-b8e4-11e4-8fca-71a5472e727e.png)

The line highlighting change even extended to other file types, like .cs files:

![image](https://cloud.githubusercontent.com/assets/169953/6306071/0797ceea-b8e5-11e4-9364-5fba7e29226a.png)

You had suggested changing the colors under Tools->Options->Fonts and Colors->"PowerShell *". But, I can't seem to find those options. I tried hitting "Use Defaults", but that didn't revert anything. It's like these colors are the defaults now.

![image](https://cloud.githubusercontent.com/assets/169953/6306093/4f0c7f46-b8e5-11e4-9af4-9c89fa5327cc.png)
![image](https://cloud.githubusercontent.com/assets/169953/6306095/52fa7482-b8e5-11e4-93fd-e0e5b5465499.png)

So, I guess that was a long way to get back the answer from the Visual Studio Gallery question:

> I think the highlighting was changed to match the ISE. If it's not, please raise an issue on GitHub.

I actually really like the Visual Studio Dark theme. So much so, that I setup my ISE to match the VS theme ([VS2013DarkTheme.StorableColorTheme.ps1xml](https://drive.google.com/file/d/0B3rJL431bZWXX0xYbXZDVWtUeVE/view?usp=sharing))

Maybe there could be a "theme selector" within Tools > Options > PowerShell Tools > General?

Sidenotes:

After writing this, I realized I could try uninstalling the dev build version and see if it reverts the colors. It did! But, the current install on the Visual Studio Gallery some issues which make it hard to use at work (I'll search around if the bugs are already reported here).

**Comment by adamdriscoll** [comment]
The PowerShell items are listed in the Text Editor category. They start with "PowerShell"

**Comment by smaglio81** [comment]
Thanks!

I couldn't really get the color picker right. They all look a little off (screenshot at bottom). You wouldn't happen to have the color picker values of the previous versions? I re-installed the older version but, everything was set to 'defaut', and some of those colors didn't really matched up:

![image](https://cloud.githubusercontent.com/assets/169953/6315150/aea740bc-b9ad-11e4-989a-d00ed46936ce.png)


My unfortunate imitation of colors:

![image](https://cloud.githubusercontent.com/assets/169953/6315156/e6a98358-b9ad-11e4-984d-14568c7104d0.png)

**Comment by adamdriscoll** [comment]
All the colors are in: https://github.com/adamdriscoll/poshtools/blob/dev/PowerShellTools/Classification/ClassificationType.cs

We updated in the MSFT fork but not this one. 

FYI: @AndreSayreMSFT @EricMSFT

**Comment by adamdriscoll** [comment]
Related to #191

**Comment by bmoore-msft** [comment]
@smaglio81 - we're going to track this in https://github.com/Microsoft/poshtools/issues/160 - take a look at that provide any feedback you have...

**Comment by smaglio81** [comment]
My apologies that I haven't been able to get back to this. Your response speed is amazing.

I've switched back to some C# coding over the last day and the coloring changes for Powershell are effecting the coloring schemes for those files aswell.

I would like to request that the coloring scheme changes in the Dev build be removed from the next release, please? If there's a checkbox to turn them on, that's great. But, these coloring changes seem to effect more than just powershell files.

C#, highlighting of text when matching search results from PowerTools search:
![image](https://cloud.githubusercontent.com/assets/169953/6404240/c48e7eba-bdca-11e4-9328-6f9ee9b9803d.png)

C#, highlighting that occurs when hovering over the expand/collapse button:
![image](https://cloud.githubusercontent.com/assets/169953/6404246/da95b6ba-bdca-11e4-9393-10f2c7ef0e37.png)



__After uninstalling PoshTools:__
C#, highlighting of text when matching search results from PowerTools search:
![image](https://cloud.githubusercontent.com/assets/169953/6404302/530998c8-bdcb-11e4-9eb1-393597b148f5.png)

C#, highlighting that occurs when hovering over the expand/collapse button:
![image](https://cloud.githubusercontent.com/assets/169953/6404303/60db4078-bdcb-11e4-8940-b6d08e332989.png)
