### ISSUE TITLE
It doesn't stop on breakpoints

### ISSUE THREAD

**Issue by jesuslpm** [adamdriscoll/poshtools#190]
Windows 8.1, Visual Studio 2013 Update 4. PowerShell Tools for Visual Studio 2013 versión 1.0.5. 

I set I break point on a ps1 script, click on start debugging, the script executes, completes, but it doesn't stop on the break point.

**Comment by AndreSayreMSFT** [comment]
Hi @jesuslpm !  This is related to #138 -- does our dev branch fix the issue for you?
[Disclaimer: Nightly build] https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev/artifacts

**Comment by jesuslpm** [comment]
Yes, it fix it!. Thank you very much.

**Comment by AndreSayreMSFT** [comment]
Glad to hear!
