### ISSUE TITLE
Color Scheme in new dev build

### ISSUE THREAD

**Issue by curi0usJack** [adamdriscoll/poshtools#191]
Per the discussion here - https://visualstudiogallery.msdn.microsoft.com/c9eb3ba8-0c59-4944-9a62-6eee37294597/view/Discussions/0 - I tried installing the new dev build to try and fix the issue I was having with breakpoints not being set. 

This raised a new issue - which is the color scheme. To be honest, this isn't really an issue, but a request to put things back the way they were. The new color scheme looks like this:

![image](https://cloud.githubusercontent.com/assets/5608516/6338128/227869ce-bb72-11e4-8ebf-0a15849d6bcb.png)

I tried the following:
1) Remove the dev build
2) Install current build
3) Export the fonts and colors (VS2013 Default Dark Theme) to a vssettings file.
4) Remove the current build
5) Install the dev build
6) Import the fonts and colors exported in step 3
7) Nothing changed.

Not sure how to ask my question other than to say can the colors be put back to defaults? If users want to change them, they can. Adam mentioned that this was to bring the color scheme in line with ISE, but if I wanted to use ISE, I would.

**Comment by adamdriscoll** [comment]
You're not the first to mention it. ;) Adding @AndreSayreMSFT and @EricMSFT to the discussion. 

For the time being, if you want the colors back they are all defined here: https://github.com/adamdriscoll/poshtools/blob/dev/PowerShellTools/Classification/ClassificationType.cs

**Comment by curi0usJack** [comment]
Dumb question. The file you linked above appears to be the same as the dev branch with I had downloaded. I recompiled/reinstalled with the file you gave me, but the colors were still the "new" colors (above). What am I missing? Sorry - I am not an extension developer by any means, so I'm sure it's something really obvious...

**Comment by adamdriscoll** [comment]
That's my bad. I was assuming the color change hadn't been merged in but it looks like it has. 

These are the previous colors: https://github.com/adamdriscoll/poshtools/commit/e2b1eee367d635c3fbda4876ec5b9ae226c5e18b

**Comment by AndreSayreMSFT** [comment]
@bmoore-msft -- Thoughts?

Hi @curi0usJack and @smaglio81 [ #189 ] !  We hear yas!  While we take a look at changing these Dark theme colors, do y'all have feedback on the tweaks we did on the light them?  For both themes, we added in a few items which did not previously have colorization.

In the interim, does using https://visualstudiogallery.msdn.microsoft.com/9e08e5d3-6eb4-4e73-a045-6ea2a5cbdabe work for you to tweak the PowerShell's theme colors?

**Comment by adamdriscoll** [comment]
@curi0usJack My bad. The colorization is merged in. 

I don't recall how the defaults were set before. They used to not be set like they are. 

https://github.com/adamdriscoll/poshtools/blob/e2b1eee367d635c3fbda4876ec5b9ae226c5e18b/PowerShellTools/Classification/ClassificationType.cs

Maybe @EricMSFT  or @AndreSayreMSFT  remembers. Otherwise, I'll have to take a look later.

**Comment by curi0usJack** [comment]
@adamdriscoll - Thanks for responding. No go on using that file. I get the following error while building

![image](https://cloud.githubusercontent.com/assets/5608516/6339618/35ab3f16-bb7d-11e4-8d08-f10fd74baed8.png)

I noticed in the new file you posted that the colors simply weren't specified, so I went into "ClassificationType.cs" where the colors are specified (the dev build) and tried replacing "ForegroundColor" with "//ForegroundColor" in hopes that the defaults would be used. This didn't work either. 

I will try @AndreSayreMSFT's suggestion and see how the VS Color Switcher works.

**Comment by curi0usJack** [comment]
@AndreSayreMSFT - I installed the Color Theme extension you suggested. This worked (sort of). The default Light Theme with Dark Editor was what I wanted in the script window. I duplicated the default Dark Theme and changed the "Text Editor - Powershell" settings to match what was in the editor style I was after. Thanks for the suggestion.

**Comment by bmoore-msft** [comment]
@curi0usJack - as you're probably aware the change was intentional, we were trying to ease the transition from the ISE to VS for newcomers and [obviously] overlooked folks who were quite happy with the scheme.  My guess is others will also have similar opinions.  Do you have the colors you need now or would it be helpful to dig out the old RGB values?

@AndreSayreMSFT - I like your suggestion for the Theme Editor, I'd prefer we don't get too carried away with theme'ing in poshtools but we clearly overlooked a need this fills.

@adamdriscoll - lmk if you have other thoughts on this... (i.e. in poshtools, etc)

**Comment by curi0usJack** [comment]
@bmoore-msft - I was able to use the Color Theme extension to get what I wanted. For the record, I really don't care what you change the color scheme to, but it would be nice to have a "Use Default Color Theme" checkbox. That's probably the easiest way to introduce new colors while keeping the purists happy. :-)

**Comment by bmoore-msft** [comment]
@curi0usJack - cool, thanks for walking us through...  I'll file a suggestion for a "classic" checkbox, and see what other folks think.

**Comment by bmoore-msft** [comment]
https://github.com/Microsoft/poshtools/issues/160

**Comment by curi0usJack** [comment]
@bmoore-msft Thanks!
