### ISSUE TITLE
Invoke-Sqlcmd : Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information.

### ISSUE THREAD

**Issue by CavemanMPN** [adamdriscoll/poshtools#192]
Visual Studios 2013.4 - Posh Tools - Dev branch - Windows 8.1

Invoke-Sqlcmd : Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information.

I get this anytime i run Invoke-SQLcmd whether I use the -serverInstance switch or while using the current SQLSERVER: provider.

**Comment by AndreSayreMSFT** [comment]
Hi @CavemanMPN !  

Is this problem isolated to the new builds?  Searching around, I found some other people running into this issue even in the ISE.  http://www.sqlmusings.com/2011/11/19/resolving-powershell-v3-ise-error-with-invoke-sqlcmd/

**Comment by CavemanMPN** [comment]
Yes, only in the dev build.  Are you tied to ISE at all?  I will see if i get it in the ISE.

**Comment by AndreSayreMSFT** [comment]
Also, as a test/possible workaround, What if you create a file named ```PowerShellToolsProcessHost.exe.config``` , and place it inside the extension folder [The location of the PowerShell tools dlls] 

For example, on my machine,

C:/Users/AndreSay/AppData/Local/Microsoft/VisualStudio/12.0/Extensions/AdamDriscoll/PowerShell Tools for Visual Studio 2013/1.0.5/

and have the contents of this file be:
```xml
<?xml version="1.0" encoding="utf-8" ?> 
<configuration> 
    <startup useLegacyV2RuntimeActivationPolicy="true">
      <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    </startup>
</configuration>
```

**Comment by CavemanMPN** [comment]
I do not get it when running ISE.

Andre!!!!!!   That fixed it.  You guys ROCK!!!

**Comment by AndreSayreMSFT** [comment]
Thanks!  We've opened up an issue for us so it doesn't get lost in the proverbial shuffle! https://github.com/Microsoft/poshtools/issues/158

**Comment by aleksbor** [comment]
Getting the same error when debugging in VS Code. What would be the config change for VC Code?

**Comment by kadralievr** [comment]
Hi,
@aleksbor for VS Code create config file for `Microsoft.PowerShell.EditorServices.Host.exe` with same content as Andre wrote.
In my machine this file in `C:\Users\%USERNAME%\.vscode\extensions\ms-vscode.PowerShell-0.4.1\bin\Microsoft.PowerShell.EditorServices.Host.exe`
```xml
<?xml version="1.0" encoding="utf-8" ?> 
<configuration> 
    <startup useLegacyV2RuntimeActivationPolicy="true">
      <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    </startup>
</configuration>
```

**Comment by aleksbor** [comment]
Hello Ramil. Thanks for the tip!

AK

**Comment by fazleskhan** [comment]
To get the plugin working with VisualStudio 2015 community edition and the Invoke-Sqlcmd cmdlet I had to add the files

PowerShellToolsProcessHost.exe.config
PowerShellToolsProcessHost.x86.exe.config
PowerShellToolsProcessHostConsole.exe.config

with the content

```
<<?xml version="1.0" encoding="utf-8" ?> 
<configuration> 
    <startup useLegacyV2RuntimeActivationPolicy="true">
      <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    </startup>
</configuration>


```
to the folder

C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\ws1d53q0.nhh
