### ISSUE TITLE
New Version for VS2015?

### ISSUE THREAD

**Issue by AnneTheAgile** [adamdriscoll/poshtools#194]
hi! thank you for this tool! I see so far VS2013 is the latest shown. I'm very excited about the forthcoming OneGet and freeness of VS2015 :). Is there a roadmap on when that will be supported?

Do you think it will require many changes?
AnneTheAgile

**Comment by adamdriscoll** [comment]
@AnneTheAgile If you're interested in giving the latest dev builds a shot, they support VS2015: https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/build/artifacts

**Comment by AnneTheAgile** [comment]
@adamdriscoll , neato, ok will do!
