### ISSUE TITLE
Test Runner - Pester - Root Element is Missing

### ISSUE THREAD

**Issue by AndyBrennan1** [adamdriscoll/poshtools#197]
Hi all,

I am having a play around with your lovely extension but I can't get any Pester tests to run in the test runner. I keep getting the error below. 

I am using 

* Visual Studio Premium 2013 - 12.0.31101.00 Update 4
* Windows 8.1 Enterprise
* Powershell Tools for Visual Studio 2013 version 1.0.5

Please can you offer any advice?

Thanks

Andy

Test Name:	When called It should not throw an exception if computer not provided
Test FullName:	Pester||Get-LocalUserList||When called||should not throw an exception if computer not provided
Test Source:	C:\Users\....Get-LocalUserList.Tests.ps1 : line 15
Test Outcome:	Failed
Test Duration:	0:00:00

Result Message:	Root element is missing.
Result StackTrace:	
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at PowerShellTools.TestAdapter.PesterTestExecutor.ParseResultFile(String file, String directory, String describeName, String testCaseName)
   at PowerShellTools.TestAdapter.PesterTestExecutor.RunTest(PowerShell powerShell, TestCase testCase, IRunContext runContext)
   at PowerShellTools.TestAdapter.PowerShellTestExecutor.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle)

**Comment by adamdriscoll** [comment]
Hey @AndyBrennan1. I might have just fixed this. Can you give this dev build a try? You might need to uninstall your current build to install this one.

https://ci.appveyor.com/project/adamdriscoll/poshtools/build/1.0.93/artifacts

**Comment by AndyBrennan1** [comment]
Hey @adamdriscoll thanks for the super speedy reply.

I'm on with testing it out now. 

I look to be getting a different error message at the moment to do with the pester files not being digitally signed. I seem to remember seeing someone had posted about that already so I'll try find out the fix and then hopefully I can get back to you.

Thanks
Andy

**Comment by AndyBrennan1** [comment]
OK ..  I was tricked a little  :)

The error message I got complained about Pester scripts in the system32 folder not being digitally signed even though I had set the execution policy to bypass ... then I realised I am running a 32 bit visual studio (maybe the error message should say SysWOW64 when using 32 bit visual studio on 64 bit operating system). 

So ... all I had to do was to set the execution policy using 32 bit command prompt - then my tests started passing (and failing :(  ).

Good work @adamdriscoll  - when do you think you'll be be putting this out?

**Comment by AndreSayreMSFT** [comment]
@adamdriscoll Do we want to manually set the execution policy of the runspace that executes the Pester tests?

**Comment by adamdriscoll** [comment]
@AndreSayreMSFT Yep. Good idea. Added #198

**Comment by adamdriscoll** [comment]
@AndyBrennan1 Very soon!
