### ISSUE TITLE
Officially support VS2015

### ISSUE THREAD

**Issue by hmemcpy** [adamdriscoll/poshtools#200]
The extension currently installs into VS2015, but it crashes when opening a ps1 file (see issue #199)

**Comment by adamdriscoll** [comment]
Can you try the latest dev build? https://github.com/Microsoft/poshtools/releases/tag/Dogfood-2-27-14

This might be fixed.

**Comment by hmemcpy** [comment]
Thanks! That did it! Works great now.

I tried looking at the bug myself, I couldn't figure out why `PS1ScriptGaps` classification wouldn't work in VS2015. Looks like the Microsoft team fixed it here: https://github.com/Microsoft/poshtools/commit/5c614fbe34d1fba881c12800bef208a3d3505aad

Anyway, thanks again, I guess you can also close #199!
