### ISSUE TITLE
Braces are not properly indenting

### ISSUE THREAD

**Issue by ChrisLynchHP** [adamdriscoll/poshtools#202]
When adding braces for code blocks, I hit the enter key and the final brace is only indented a single time.  However, the code block could be nested, and for obvious reading purposes, the braces should be further indented.

**Comment by AndreSayreMSFT** [comment]
Thanks for reporting this, @ChrisLynchHP !  This looks to be similar to https://github.com/Microsoft/poshtools/issues/108

**Comment by AndreSayreMSFT** [comment]
Also related to #157

**Comment by jeffpatton1971** [comment]
This is still an issue in the most recent beta release. 
Create a new function, tab and add a begin { } section. Inside the begin section I tab over and type if () when I hit enter and type a brace, instead of being underneath the if, the braces are placed underneath the begin.

**Comment by AndreSayreMSFT** [comment]
We've fixed this!
