### ISSUE TITLE
Does not install on Windows 10

### ISSUE THREAD

**Issue by clovett** [adamdriscoll/poshtools#204]
Windows 10 ships .NET 4.6, so the .NET 4.5 dependency check fails on install.  If you remove the.NET framework dependency from your vsixmanifest then the install works fine.

**Comment by AndreSayreMSFT** [comment]
Hi @clovett !  Thanks for reporting this!  Seems related to #165, which was fixed by @masaeedu . Do the nightly builds work for you?

**Comment by clovett** [comment]
Yep, same issue. The fix by masaeedu is good.


When I clone your repository I have trouble building it, I get compile errors because it cannot resolve:

Microsoft.VisualStudio.TestPlatform.ObjectModel

Microsoft.VisualStudio.TestWindow.Core

Microsoft.VisualStudio.TestWindow.Interfaces


these things do exist under:

d:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow


DevEnvDir = D:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\


Notice my devenv dir is on the D: drive, not the C: driver, so using so the hintpath doesn’t work:


 <HintPath>$(MSBuildProgramFiles32)\Microsoft Visual Studio $(VSTarget)\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Microsoft.VisualStudio.TestPlatform.ObjectModel.dll</HintPath>




Strangely changing this to use $(DevEnvDir) doesn’t work, something wrong with the order of properties…

but changing it to the following does work:


<HintPath>$(VS120COMNTOOLS)..\IDE\CommonExtensions\Microsoft\TestWindow\Microsoft.VisualStudio.TestPlatform.ObjectModel.dll</HintPath>


but clearly that voids your multi-targeting stuff…






Sent from Windows Mail





From: Andre Sayre
Sent: ‎Tuesday‎, ‎March‎ ‎17‎, ‎2015 ‎2‎:‎37‎ ‎PM
To: adamdriscoll/poshtools
Cc: Chris Lovett





Hi @clovett ! Thanks for reporting this! Seems related to #165, which was fixed by @masaeedu . Do the nightly builds work for you?

**Comment by AndreSayreMSFT** [comment]
@clovett Glad to hear that the original issue is fixed!  Closing this issue out.  Did you want to open up another issue for not being able to local-build when VS is installed to a non-default location?
