### ISSUE TITLE
VS2013 Comment / uncomment feature disabled

### ISSUE THREAD

**Issue by kratkaericd** [adamdriscoll/poshtools#206]
I grabbed build 2.0.4100.00 of PowershellTools.dll as recommended in a post to solve another issue (file paths were crashing VS), but it turns out that build disabled CTRL+E,C and CTRL+E,U used for commenting and uncommenting lines of PowerShell script. Please reinstate that functionality and thank you for putting this together.

**Comment by kratkaericd** [comment]
FYI: I just found version 3.0.632 from https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev/artifacts. It doesn't support commenting and uncommenting code whereas version 1.05 did. Thanks for all the improvements being made though!

**Comment by AndreSayreMSFT** [comment]
Thanks for reporting the bug, @kratkaericd!  Added to the list

**Comment by bgoldsht** [comment]
Hello guys. Just installed 3.0.108. Also does not support comment/uncomment. Just want to let you know. Thanks.

**Comment by bgoldsht** [comment]
Just installed 3.0.134 couple of minutes ago and there is no comment/uncomment functionality. Please add this functionality asap. Thanks.

**Comment by HuanhuanSunMSFT** [comment]
Hi, @bgoldsht @kratkaericd, sorry for all the delay but we are finally there. Fixed in this [pull request](https://github.com/Microsoft/poshtools/pull/684)

**Comment by kratkaericd** [comment]
Muuuch better! Thank you for fixing this.
