### ISSUE TITLE
almost unreadable with solarized dark theme

### ISSUE THREAD

**Issue by timabell** [adamdriscoll/poshtools#207]
Theme obtained through https://visualstudiogallery.msdn.microsoft.com/9e08e5d3-6eb4-4e73-a045-6ea2a5cbdabe

![posh vs colours](https://cloud.githubusercontent.com/assets/19378/6937810/56ad5bd6-d856-11e4-92b1-bf29db45daab.png)

As you can see from the above it's very hard to read. For some reason posh vs isn't using the same palette as the c# editor does.

Here's what c# looks like with this theme:

![posh vs csharp colours](https://cloud.githubusercontent.com/assets/19378/6937838/9ca9095a-d856-11e4-874e-ee70e7ce37a7.png)

**Comment by AndreSayreMSFT** [comment]
PowerShell uses a completely different set of color definitions than C#; and the themes provided by that extension haven't specified colors for the PowerShell definitions.  

Do you have suggestions on how the colors should map?  It would be up to folks behind the aforementioned extension to update what it ships with, but I think it allows for user-customized colors as well.

**Comment by timabell** [comment]
hmm, interesting. I think it should look like the above c# example. You are right that you can customize the colours, though it's incredibly fiddly in the UI (I had to fix a couple of broken colours for c#). I couldn't work out how to contribute changes back to their project.

**Comment by timabell** [comment]
I had a rant at them in their crappy reviews section of the gallery https://visualstudiogallery.msdn.microsoft.com/9e08e5d3-6eb4-4e73-a045-6ea2a5cbdabe/view/Reviews I'm sure it won't make the damndest bit of difference.

**Comment by timabell** [comment]
my current theme https://github.com/timabell/dotmatrix/blob/windows/vs-unfucked-dark.vstheme (excuse the language)

**Comment by timabell** [comment]
you can import/export themes so maybe that's the answer, we'll just publish our own and people can import it if they want it

**Comment by timabell** [comment]
I've customized the colours to look more like the c# theme and published it at the above url. Much more readable.

![posh vs colours take 2](https://cloud.githubusercontent.com/assets/19378/6966513/9164eb3a-d951-11e4-9391-fb8effbb0fd5.png)
