### ISSUE TITLE
VS2013 crashes when comparing/diffing 

### ISSUE THREAD

**Issue by kratkaericd** [adamdriscoll/poshtools#209]
I recently grabbed the newest build from https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev/artifacts and this build now crashes Visual Studio when attempting to compare PowerShell files and displays a "Microsoft Visual Studio 2013 has stopped working".

Exception:
System.NullReferenceException was unhandled
Message: An unhandled exception of type 'System.NullReferenceException' occurred in Microsoft.VisualStudio.Diff.dll
Additional information: Object reference not set to an instance of an object.

**Comment by smaglio81** [comment]
I just grabbed the latest build, and I'm running into the same issue.

**Comment by AndreSayreMSFT** [comment]
@kratkaericd , @smaglio81 :  Thanks for reporting this!  

Are y'all still seeing this in the latest nightly dev builds?  @HuanhuanSunMSFT did some fantastic work last Friday in improving our colorization and editor experience, which addressed a few crashing issues.

**Comment by smaglio81** [comment]
I just tried 3.0.670; Merge pull request #357 from Microsoft/outputracecondition
Fix output formatting issue you might be seeing [race condition]

I'm still unable to get the diff window to come up. VS2013 doesn't crash, but it freezes up for about a minute.

**Comment by AndreSayreMSFT** [comment]
Going to be closing this out w/regards to the crashing issue, but, @smaglio81 , if you're encountering this a slowdown after our tools are installed, are you able to provide repro steps in a new issue?

**Comment by kratkaericd** [comment]
Sorry for not replying soon enough but build 3.0.689 still crashes when trying to compare Powershell documents. This is not fixed. Thanks for giving it some attention though.

**Comment by AndreSayreMSFT** [comment]
Thanks @kratkaericd  Reopening!  Could you give us a the precise steps you're taking to bring up the comparison between the documents?  Want to make sure that we're starting at the same place :)

@HuanhuanSunMSFT  @EricMSFT ,

**Comment by kratkaericd** [comment]
1. Open Visual Studio 2013 [Ultimate]
2. Open a [TFS source controlled] PowerShell file. The file may or may not be part of a PowerShell project; it doesn't affect this behavior.
3. Use one of the many ways to compare a file. I have a custom toolbar with a Compare button, or I right-click in Solution Explorer and choose compare, or I right-click in Team Explorer and choose Compare with Latest Version
4. Notice Visual Studio crash by displaying a dialog with "Microsoft Visual Studio 2013 has stopped working"

See http://1drv.ms/1aOruTr for a visual representation of the ways I compare. Notice I have version 1.0.5 of PowerShell tools in this screenshot because I use Compare A LOT :)

**Comment by AndreSayreMSFT** [comment]
Thanks @kratkaericd !  Got the repro and callstack needed.  I've updated the title accordingly, and we'll get this fixed up for you!

![image](https://cloud.githubusercontent.com/assets/10080679/7080018/8ef45964-dee0-11e4-9b55-f0e22245d586.png)

**Comment by kratkaericd** [comment]
Works great! Thank you for fixing it.

**Comment by jamesdking** [comment]
I'm seeing this in 3.0.99
