### ISSUE TITLE
Support for Powershell extensions, snap-ins, cmdlets, etc

### ISSUE THREAD

**Issue by russshearer** [adamdriscoll/poshtools#212]
Does the extension support syntax highlighting and IntelliSense for PowerShell extensions, snap-ins, cmdlets such as VMware PowerCLI, Microsoft Exchange, etc?

If not, is it a planned feature or is there a way an end user can update or extend the support?

Thanks!

**Comment by adamdriscoll** [comment]
It certainly does. The syntax highlighting and IntelliSense components of this extension use the same interfaces as the PowerShell ISE. If something isn't working as expected, please let us know. :+1:
