### ISSUE TITLE
Could not load type 'System.Management.Automation.DebuggerCommandResults' w/PS 3.0

### ISSUE THREAD

**Issue by timabell** [adamdriscoll/poshtools#214]
This is probably me doing something wrong, but I have a script that works fine in a powershell console, but when I run it from visual studio I get the following:

	[ERROR] C:\repo\ssrs-powershell-deploy\Deploy-SSRSProject.ps1 :
		Could not load type 'System.Management.Automation.DebuggerCommandResults'
		from assembly 'System.Management.Automation, Version=3.0.0.0, 
	[ERROR] Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
	[ERROR] At line:1 char:1
	[ERROR] + . 'C:\repo\ssrs-powershell-deploy\Deploy-SSRSProject.ps1' -path 'C:\repo\foo\bar ...
	[ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	[ERROR]     + CategoryInfo          : NotSpecified: (:) [Deploy-SSRSProject.ps1], TypeLoadException
	[ERROR]     + FullyQualifiedErrorId : System.TypeLoadException,Deploy-SSRSProject.ps1
	[ERROR]  
	The program 'Deploy-SSRSProject.ps1: PowerShell Script' has exited with code 0 (0x0).

I tried adding a reference in the project to the mentioned assembly http://stackoverflow.com/q/1186270/10245 with no success, and tried fiddling with the project options for powershell version and required assemblies also to no avail.

The script I'm running is https://github.com/timabell/ssrs-powershell-deploy/blob/master/Deploy-SSRSProject.ps1 from https://github.com/timabell/ssrs-powershell-deploy (current version: https://github.com/timabell/ssrs-powershell-deploy/tree/6c7468a735fd6d35fff2cb0b536cbb1065f1b2b3 )

Thanks, it's nice to have powershell in a decent IDE.

**Comment by EricMSFT** [comment]
Thanks for reporting this issue Tim. Please refer to #213 if you have PSv3.0 installed on your machine.  Things should work fine on PSv4.0 if upgrade can be a work around for you at this moment. I m investigating and see how we can address this compatibility issue.

**Comment by timabell** [comment]
Installing powershell v4 (`cinst powershell`) and rebooting the machine fixed it for me. Many thanks.

**Comment by EricMSFT** [comment]
@timabell, @bgoldsht we've had this issue fixed on Microsoft/poshtools, should be on its way to Adam's repo later this week! Go try it out by then and let us know if you are seeing any problem there!
