### ISSUE TITLE
VS hangs when breakpoint set while debugging powershell script

### ISSUE THREAD

**Issue by timabell** [adamdriscoll/poshtools#216]
I'm afraid I don't have any more details, but feel free to ask for anything that might help diagnose this.

If I hit f5 on a script with a breakpoint set, the debugger will stop on that breakpoint and stepping through works fine. If I try and set another breakpoint while execution is paused by clicking on the left margin of the code the whole of visual studio stops responding and I get the little popup from the system try saying visual studio is busy.

If I kill `PowerShellToolsProcessHost.exe` in task manager then visual studio promptly recovers. However hitting run (f5) again immediately hangs visual studio again and no `PowerShellToolsProcessHost.exe` process appears in task manager this time. I have to kill `devenv.exe' to and restart it to get things working again.

Win7 x64 / Powershell v4 / VS 2012 update 3

Thanks again. I've already managed to get some useful insight from the debugger into the script I'm troubleshooting.

**Comment by EricMSFT** [comment]
I seem to have problem on repro'ing it on win8.1/powershellv4/vs2012 update3, will try on win7 and see if I can get a repro later today.
However, just fyi, powershell v4 does not support, or I should say both v3 and v4 have "problem" on adding/removing breakpoint during debugging break(or paused), so basically for whatever breakpoints you added during your current debugging session, won't be able to be picked up until you restart your debugging session. Powershell v5 fixed this problem.

**Comment by EricMSFT** [comment]
I'm guessing Microsoft#418 may explained what happened in your case @timabell

**Comment by timabell** [comment]
excellent, so a fix is on it's way then :-)

**Comment by adamdriscoll** [comment]
@timabell Have you tried the latest build? It should have this fix.

**Comment by timabell** [comment]
Visual Studio "Extensions and Updates" is showing v3.0.637 installed, and isn't showing any updates as being available.

I've dealt with the script I was working on so I'm not using it at the moment.

**Comment by AndreSayreMSFT** [comment]
We believe this to be fixed, definitely let us know if that's not the case!
