### ISSUE TITLE
Scripts run from Interactive Window do not preserve their state

### ISSUE THREAD

**Issue by theficus** [adamdriscoll/poshtools#222]
I've run into a couple of issues with interactive mode that I wanted to bring to your attention. These unfortunately make it so that I can't use PowerShell Tools until it's fixed as interactive mode is a critical feature for me.

Firstly, when interactive mode is loaded, it doesn't load my profile.ps1. This wouldn't be a big deal if I could just manually load my profile.ps1, but the problem is that it appears that when a script is executed, its state is immediately discarded when it's done.

In other words, my profile.ps1 does this: mounts some PSDrives, and creates some functions for shortcuts for things I do frequently. Nothing too crazy there. 

Unfortunately once my profile.ps1 is done running, the state appears to be discarded. My functions are gone, any variables I set are gone, any PSDrives I created are no longer available, any variables I set are gone.

This issue does not repro in ISE.

Repro:

```powershell
$Global:foo = "foo hello world"
$bar = "bar hello world"
Function HelloWorld 
{ 
    Write-Host "hello world" 
}
Write-Host done!
```
```
PS D:\temp> .\script.ps1
done!
PS D:\temp> $foo
foo hello world
PS D:\temp> $bar
PS D:\temp> HelloWorld
[ERROR] HelloWorld : The term 'HelloWorld' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 
[ERROR] path is correct and try again.
[ERROR] At line:1 char:1
[ERROR] + HelloWorld
[ERROR] + ~~~~~~~~~~
[ERROR]     + CategoryInfo          : ObjectNotFound: (HelloWorld:String) [], CommandNotFoundException
[ERROR]     + FullyQualifiedErrorId : CommandNotFoundException
[ERROR]  
PS D:\temp> 
```

**Comment by EricMSFT** [comment]
Thanks for reporting this @theficus . However I could not get a repro by using your repro steps on both VS2013 and VS2015 RC + latest Poshtools build.  Is there anything could be missed from your repro steps above?

**Comment by theficus** [comment]
Talked to Eric offline and got this resolved. This was a PEBKAC issue.
