### ISSUE TITLE
Pester tests as run from Test Explorer do not run in the same context as the Interactive Window

### ISSUE THREAD

**Issue by theficus** [adamdriscoll/poshtools#226]
Pester tests seem to run in their own context separate from the Interactive Window. This means if you do any necessary setup from within the Interactive Window, this is ignored when the Pester test is run.

**Comment by adamdriscoll** [comment]
This is by design at the moment. The test adapter actually runs in a seperate process. Though I'd argue that your tests should be stand alone and all the setup would be done within the test scripts themselves.

**Comment by theficus** [comment]
While this may be related to issue 222, I did want to note that even with the proper setup logic in my tests things definitely do not behave consistently when run in Test Explorer. I'm finding that all of the setup that happens in my common setup script referenced by my main .Test.ps1 scripts is all discarded by the time it gets to my unit test.

**Comment by AndreSayreMSFT** [comment]
I'm inclined to agree with @adamdriscoll about Tests running in it's own context, without having to worry about being influenced by what's been set in the REPL's runspace.

Are there situations in which you're unable to Initialize the tests within the tests' run?

**Comment by theficus** [comment]
After consideration I agree that the behavior here is correct. I've filed bug #240 to track the test runner not loading a profile.ps1 which would work around the majority of pain here for me.
