### ISSUE TITLE
Interactive window does not load profile.ps1 automatically

### ISSUE THREAD

**Issue by theficus** [adamdriscoll/poshtools#229]
When the Interactive window launches, it should load your profile.ps1 like ISE does

**Comment by adamdriscoll** [comment]
Related: https://github.com/Microsoft/poshtools/issues/291

**Comment by bmoore-msft** [comment]
@theficus - poshtools has it's own profile (which is pretty hard to discover) - the separate profile allows you to have different ones between poshtools and ps.  Is that desirable or inconvenient for you?

**Comment by theficus** [comment]
I'm a bit mixed. ISE loads the global profile so this was the behavior I was expecting. I was able to work around it by using the poshtools profile of course. It's unfortunate this isn't more discoverable.

Is this picked up by the unit test runner too? If not I'll file a separate bug for this.

--
Sent from my phone. Expect brevity and typos.

On Apr 24, 2015, at 5:56 AM, Brian Moore <notifications@github.com<mailto:notifications@github.com>> wrote:


@theficus<https://github.com/theficus> - poshtools has it's own profile (which is pretty hard to discover) - the separate profile allows you to have different ones between poshtools and ps. Is that desirable or inconvenient for you?

-

**Comment by adamdriscoll** [comment]
It's not picked up by the test runner. If we do have it picked up by the test runner, I think we should have an option to disable that.

**Comment by theficus** [comment]
Agreed. I'll submit an issue on this when I get to work.

--
Sent from my phone. Expect brevity and typos.

On Apr 24, 2015, at 9:04 AM, Adam Driscoll <notifications@github.com<mailto:notifications@github.com>> wrote:


It's not picked up by the test runner. If we do have it picked up by the test runner, I think we should have an option to disable that.

-

**Comment by adamdriscoll** [comment]
RE: Discoverability: Maybe we could have a menu option to open the PoshTools\PowerShell profile?

**Comment by theficus** [comment]
I like that so you can keep the profiles separate if you want. Some would expect parity with ISE for profile loading.

For discoverability even logging something about what it's doing could be helpful. I had no idea there was a special profile for poshtools until I filed this issue. :) a simple log entry saying it was looking for the poshtools_profile.ps1 would have been a big clue.

--
Sent from my phone. Expect brevity and typos.

On Apr 24, 2015, at 9:07 AM, Adam Driscoll <notifications@github.com<mailto:notifications@github.com>> wrote:


RE: Discoverability: Maybe we could have a menu option to open the PoshTools\PowerShell profile?

-

**Comment by AndreSayreMSFT** [comment]
@bmoore-msft All hosts should load the four profiles, and be hooked into the ```$profile``` chain; PoshTools is using a non-standard method, and should use the same, user specific Profiles as the other PowerShell hosts on the system.

        Description                Path
        -----------                ----
        Current User, Current Host $Home\[My ]Documents\WindowsPowerShell\OURPROFILE_profile.ps1
        Current User, All Hosts    $Home\[My ]Documents\Profile.ps1
        All Users, Current Host    $PsHome\OURPROFILE_profile.ps1
        All Users, All Hosts       $PsHome\Profile.ps1

@theficus : Agreed, separate issue to have Test Host handle $profile stuff :)

**Comment by theficus** [comment]
Filed bug #240 to track the test runner specific side of things.

**Comment by AndreSayreMSFT** [comment]
Agreed; Microsoft#291

**Comment by iecompat12** [comment]
wanted to say...

**Comment by AndreSayreMSFT** [comment]
Fixed up in a recent commit!
