### ISSUE TITLE
There should be a setting to turn off the auto-completion for braces, quotes, etc

### ISSUE THREAD

**Issue by theficus** [adamdriscoll/poshtools#231]
I am not a fan of auto-completing braces, quotes, and the like (it's not just a poshtools gripe, I don't like it for other code types either) but there doesn't appear to be any option to disable this behavior for poshtools.

There should be an option for the editor to disable this behavior.

**Comment by AndreSayreMSFT** [comment]
Agreed, the setting should be something that's, well, settable!

**Comment by bmoore-msft** [comment]
@theficus - Is there a particular reason you don't like it (ie. not behaving as it should, bugs, etc) or just a personal preference?

**Comment by theficus** [comment]
Both! I like closing my own statements, and it's buggy too. It's way too aggressive and often exhibits undesirable behavior. I've already filed a couple of issues on this.

Even if the bugs were fixed I still wouldn't want to use it because I just don't like this type of auto completion.

--
Sent from my phone. Expect brevity and typos.

On Apr 24, 2015, at 5:53 AM, Brian Moore <notifications@github.com<mailto:notifications@github.com>> wrote:


@theficus<https://github.com/theficus> - Is there a particular reason you don't like it (ie. not behaving as it should, bugs, etc) or just a personal preference?

-

**Comment by AndreSayreMSFT** [comment]
Also, it's an option that's there, but disabled currently.

![image](https://cloud.githubusercontent.com/assets/10080679/7324599/a69317d0-ea6c-11e4-9c5e-ea40f45fd37c.png)

**Comment by bmoore-msft** [comment]
We should look at some of the other autocomplete diffs (from ISE) as well, this may be more than a single checkbox

**Comment by xl-gtf** [comment]
When editing texts it is often necessary to append a brace or quote to the beginning of a line in which the end brace or quote already exists, or append a single character. 
This text editor persistently adds two quotes and both braces every time. Editing becomes more inconvenient than any other text editor.
If checkboxes and saving/restoring settings take time to implement - why not - for now - disable auto brace, quote, bracket  etc. completion?

**Comment by bmoore-msft** [comment]
Agree w/ @xl-gtf can we disable this until we can get it right?

**Comment by theficus** [comment]
I agree as well. Just being able to disable this feature would be hugely convenient for me. As it stands today I don’t really use poshtools as my editor because these annoyances stack up very quickly for me to the point where I just use ISE instead.

**Comment by AndreSayreMSFT** [comment]
@bmoore-msft : We should do both -- https://github.com/adamdriscoll/poshtools/issues/230 https://github.com/Microsoft/poshtools/issues/537 but enable the option as specified in the bug

@theficus Recent fixes here: https://github.com/Microsoft/poshtools/issues?q=is%3Aissue+is%3Aclosed+label%3A%22Brace+matching%22+milestone%3AMay -- Are there other annoyances we've missed?  [Would you be willing to take a look at the latest builds and see how they fare?]

**Comment by jinglou-** [comment]
Let's first enable the option in the Options dialog.

**Comment by jinglou-** [comment]
Should be fixed after next Pull Request to Adam's repo.
