### ISSUE TITLE
Unit tests in project are no longer found.

### ISSUE THREAD

**Issue by theficus** [adamdriscoll/poshtools#234]
Using the latest build from AppVeyor. 

Here's what's happening: 
* Pester unit tests are being picked up. This is weird because Pester isn't in my project (but it is in the directory that the solution file is in). This seems like a bug -- why would it pick up unit tests that aren't in my project?
* None of the unit tests for the tests in my project are being added to Test Explorer. Looking at the "Tests" log it looks like the "Found describe block." line is being logged but it's not being added for some reason.

Is there just some logic being inverted here where it's ignoring tests that are in the project but not ignoring tests that aren't in the project?

**Comment by theficus** [comment]
I just realized I had pulled the latest MSFT version from here: https://ci.appveyor.com/project/PoshTools-MSFT/poshtools not from here: https://ci.appveyor.com/project/adamdriscoll/poshtools/branch/dev

I'll check and make sure this doesn't repro with the latest version from the non-MSFT poshtools build.

**Comment by adamdriscoll** [comment]
Get the latest from here: https://ci.appveyor.com/project/adamdriscoll/poshtools/branch/testadapter/artifacts 

This hasn't been put in the dev branch yet.

**Comment by adamdriscoll** [comment]
Oh never mind. Since iit's a PR, it will be in the AppVeyor of the dev branch. You're good.

**Comment by theficus** [comment]
Update: in your version I'm still seeing the Pester unit tests (which seems like a bug) but I'm also seeing my own project's unit tests. Phew.

I'll get a new bug filed for this specific issue. I've also found a couple of interesting issues with the latest drop with how it discovers unit tests that I'll file a bug on.

Thanks!
