### ISSUE TITLE
Pester unit test discovery is discovering unit tests for files that are in the solution directory but not the project

### ISSUE THREAD

**Issue by theficus** [adamdriscoll/poshtools#235]
I have Pester in the directory that contains my unit tests, but Pester is not part of my project. The test discovery is still picking up all of the Pester unit tests. This seems wrong.

The unit test discovery should only try to add tests for files that are actually in the .psproj.

**Comment by adamdriscoll** [comment]
Bizarre. The discovery should only look at files in the project. I'm really surprised I haven't run into this before. Thanks for reporting it.

**Comment by adamdriscoll** [comment]
I've reproduced this. It's definitely picking up all files under the project directories in the solution. Working on a fix...

**Comment by theficus** [comment]
I'm using the 3.0.128 build from AppVeyor, and now only Pester tests are showing up -- the unit tests contained in my solution aren't showing up at all anymore.
