### ISSUE TITLE
Closing REPL window doesn't close underlying PSHost instance

### ISSUE THREAD

**Issue by theficus** [adamdriscoll/poshtools#239]
It looks like the state of the REPL window is preserved after closing it. This can be problematic if you have stubborn modules or code loaded since this means the only way to reset the state of the underyling PSHost used by the REPL window is to restart Visual Studio.

Closing the REPL window should terminate the underyling PSHost so you can easily get back into a clean state by closing and reopening the REPL window rather than having to restart Visual Studio.

**Comment by AndreSayreMSFT** [comment]
Hi @theficus !  

At the moment, this is by design for performance reasons [The underlying PowerShell host takes a little bit of time to initialize before becoming fully useful]. Of course, designs can always be changed if needed.

If Microsoft#292 were fixed up, would that solve the underlying issue you're running into, or are there other reasons you think we should close the host on REPL window close?

**Comment by theficus** [comment]
I think this design needs to be changed or options given. Yes reloading the pshost is slow, but think of how long it takes to reload visual studio by comparison.

I'm hitting the issue where the pshost loads modules and I am stuck trying to recompile them until I restart Visual Studio. That's a far worse experience.

Maybe add a setting to control this behavior, and/or add buttons to the repl window that can unload and _separately_ reload the pshost (not a one shot restart button in case your profile loads the modules).

--
Sent from my phone. Expect brevity and typos.

On Apr 24, 2015, at 12:01 AM, Andre Sayre <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @theficus<https://github.com/theficus> !

At the moment, this is by design for performance reasons [The underlying PowerShell host takes a little bit of time to initialize before becoming fully useful]. Of course, designs can always be changed if needed.

If Microsoft#292<https://github.com/Microsoft/poshtools/issues/292> were fixed up, would that solve the underlying issue you're running into, or are there other reasons you think we should close the host on REPL window close?

-

**Comment by AndreSayreMSFT** [comment]
With regards to ```add buttons to the repl window that can unload and _separately_ reload the pshost (not a one shot restart button in case your profile loads the modules).```

I'm unclear on how that differs from Microsoft#292 ? :)  Or is it the fact that the profile is loading the modules necessitating a 'don't load profiles option'?

**Comment by theficus** [comment]
You're right, it doesn't. It looks like Microsoft#292 covers the same underlying issue (the REPL window holds on to resources and there's no way to release them).

The reason I specifically called out there needing to be atomic unload and load functionality is this: if you have a single "reload" option and your profile loads modules is there is no way to unload the PSHost to release resources, compile, and then reload.

**Comment by AndreSayreMSFT** [comment]
Thinking out loud: If we had an option to not load/run the profile, and just allow a user to invoke $profile on their own, eg, Invoke-Command ... etc , would that work for what you're trying to do?

**Comment by theficus** [comment]
I suppose it would, but that just seems like kind of a roundabout solution. In all cases I /do/ want REPL to load my profile (this is why I filed #229). I /also/ want a way to be able to discard my current session and create a new one without restarting Visual Studio. Make sense? :)

**Comment by AndreSayreMSFT** [comment]
Yep, my above out-loud thoughts are in the context of being in conjunction with Microsoft#292 :)

**Comment by AndreSayreMSFT** [comment]
We'll take care of this with the aforementioned issue! Microsoft#292
