### ISSUE TITLE
"Failed to initialize" Issue When Running VS2013 Not As Admin With UAC Enabled

### ISSUE THREAD

**Issue by johnmcalvert** [adamdriscoll/poshtools#241]
Hi, the FAQ describes a fix for this issue:
> Failed to initialize PowerShell Tools for Visual Studio.System.IO.FileNotFoundException: Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

which involves installing Windows Management Framework v3. However, if I run Visual Studio as Admin then the issue goes away. So I'm not sure that WMF3 is what I need.

I would like to be able to run Visual Studio not as admin since I don't otherwise require that, and still have POSHTools enabled for all its goodness. Specially running as admin requires that I use a different account that is not authorized in TFS so that creates another problem.

Is there a reason why POSHTools does not work when running Visual Studio not as admin?

**Comment by adamdriscoll** [comment]
Weird. I wonder if there is an issue between installing PoshTools as an admin and then running it as a non-Admin. We recently changed PoshTools to require admin priveleges to install. We'll have to look into it. 

Have you guys seen this? @AndreSayreMSFT  @EricMSFT @bmoore-msft

**Comment by bmoore-msft** [comment]
I have not seen this but don't RANU - also been running 2015.  If you don't have a repro set up, we can easily spin up a 2013 box...

**Comment by AndreSayreMSFT** [comment]
I haven't run into this issue myself, and I often Run [VS] As Normal User, but i'm spinning up a Win7/2013 machine now.

@johnmcalvert : Are you able to provide additional details about your configuration?  OS / PowerShell version installed / Visual Studio version?

**Comment by johnmcalvert** [comment]
I regret to advise that I can no longer reproduce this exact behaviour. I was testing various scenarios, eg non-admin account, admin account, etc, so I uninstalled and re-installed the Posh extension in VS2013 several times. Now I simply get the msg that >= WMF 3 is required. When I try to install the latter I get an error. I will take that up with our infrastructure / OPS team and report back on anything of interest.

**Comment by johnmcalvert** [comment]
For the record my machine config:
Windows 7 Enterprise x64
Visual Studio 2013 Premium Update 4

PS U:\> get-host
Name             : ConsoleHost
Version          : 2.0
InstanceId       : 1d03cb54-04a8-42e5-93aa-d4f0cf295322
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-CA
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

PS U:\> $PSVersionTable
Name                           Value
----                           -----
CLRVersion                     2.0.50727.5485
BuildVersion                   6.1.7601.17514
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1

**Comment by AndreSayreMSFT** [comment]
Closing this out, though related to https://github.com/Microsoft/poshtools/issues/569
