### ISSUE TITLE
3.0.128 -- Unit tests aren't showing up anymore

### ISSUE THREAD

**Issue by theficus** [adamdriscoll/poshtools#243]
This may be a regression introduced from the fix to #235.

In the previous build I was using, I saw tests from files that happened to be in the same directory as my solution intermingling with the tests that were in my solution.

Now with 3.0.128, none of the tests from my solution are showing up, but all of the tests that are in the same directory as my solution but aren't in the solution are showing up. Looking at the Output log, it is discovering tests (I see "Found describe block." whenever I save a .Tests.ps1 file), but those tests aren't showing up in Test Explorer.
##

**Comment by adamdriscoll** [comment]
Strange. I don't see that behavior. Though, I do need to revist this. I was looking to fix #237 and took a look at the Python Tools test adapter source. They do discovery completely differently so hopefully when I implement that, this issue should also be resolve.
