### ISSUE TITLE
Unavailable from visual studio gallery

### ISSUE THREAD

**Issue by mleithaug** [adamdriscoll/poshtools#247]
The extension doesn't seem to be available from within visual studio 2013 anymore and visual studio gallery web page returns an errorpage. Both worked for me a few days ago.

**Comment by iainbrighton** [comment]
It doesn't work for me either. However, in the interim you can download the latest artifacts directly from https://ci.appveyor.com/project/adamdriscoll/poshtools/build/artifacts (if needed).

**Comment by adamdriscoll** [comment]
We are working with the VS Gallery team to get it resolved.

**Comment by adamdriscoll** [comment]
This has been resolved.

**Comment by AndreSayreMSFT** [comment]
From all of us here at MSFT, as @adamdriscoll said, the issue has been resolved.  It was an issue with the Gallery itself, and is completely unrelated to the tools.  We've got some folks digging into root cause on the web side and are working to make sure it doesn't hit us again.
