### ISSUE TITLE
Code Snippets Manager wrong Default Directory for PowerShell language

### ISSUE THREAD

**Issue by ChrisLynchHP** [adamdriscoll/poshtools#248]
When trying to import existing code snippets into VS2013, the Location for PowerShell Snippets is %TestDocs%\Code Snippets\PowerShell.  Shouldn't this be a different location?  Is this something that I can change elsewhere (registry, INI file)?
![snippetmanager](https://cloud.githubusercontent.com/assets/6956305/7417975/fae27676-ef1e-11e4-96b0-4f9f3088465f.PNG)

**Comment by ChrisLynchHP** [comment]
I just found the Registry setting where this is stored: HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\12.0_Config\Languages\CodeExpansions\PowerShell\Paths

I was able to change the value, and my snippets show up in Snippet Manager.  However, Code Snippet appears to not be supported with this extension.  Can you add it to your backlog?

**Comment by adamdriscoll** [comment]
Yep we have snippets being tracked in #50. I had it partially working in the past but never wrapped it into a release.

**Comment by ChrisLynchHP** [comment]
Got it.  Thanks.  Looking forward to Snippet support.
