### ISSUE TITLE
Visual Studio 2013 Update 4 hangs when opening pssproj in non-"empty" directory

### ISSUE THREAD

**Issue by splatteredbits** [adamdriscoll/poshtools#252]
When I try to open a .,pssproj file with Visual Studio 2013 Update 4, in an existing source control repository (9GB+) the Visual Studio window turns white and hangs. Process Explorer shows that it is doing something.

If I move the .pssproj file into its own, empty directory, it opens fine. It seems the .pssproj format is doing some kind of processing on the file system. 
##

**Comment by splatteredbits** [comment]
![pssprojhangs](https://cloud.githubusercontent.com/assets/1082153/7485173/b37c9c68-f346-11e4-94a8-67c132d8c6f8.png)
![pssprojprocesseexplorer](https://cloud.githubusercontent.com/assets/1082153/7485183/d2555cf6-f346-11e4-9ff0-6f8b0272d073.png)

**Comment by splatteredbits** [comment]
I let this run overnight with no change. Still using a constant amount of CPU and still hanging.

**Comment by splatteredbits** [comment]
When I open Process Monitor and monitor what devenv.exe is doing, it is opening all the files in a directory. This particular directory has about 48,000 files. It looks like it takes about 5 seconds to read each file. I'm not sure if it just opens .xml files (since this directory only contains XML files) or if it is opening all files. AT this rate, though, it's going to take about 3 days to read them all. :-(

**Comment by splatteredbits** [comment]
I opened a fresh version of my .pssproj with Proces Monitor running, and it is definitely recursing down the file system opening files. Why does it do this? Any way to put this off onto a background thread so as not to hang Visual Studio? Our source control repository is quite large, 7GB and over 281,557 files.

**Comment by AndreSayreMSFT** [comment]
@splatteredbits Thanks for reporting this!

That's no good that you're running into this issue!

Can you confirm the version of the PowerShell Tools you're using?  Does this nightly-type build fix the issue for you?  https://ci.appveyor.com/project/adamdriscoll/poshtools/build/3.0.136/artifacts 

Thinking out loud ( @adamdriscoll ) : I wonder if this has to do with the Test Adapter searching for tests?

**Comment by adamdriscoll** [comment]
The test adapter is running in a seperate process but it is still possible. Let me try putting together a large solution and see what happens locally.

**Comment by adamdriscoll** [comment]
I tried to repro on 2015 with no luck. Installing 2013U4 now.

**Comment by splatteredbits** [comment]
The 3.0.136 nightly build does not fix the issue.

**Comment by jinglou-** [comment]
The latest build released is 3.0.152. Although we don't it'll address the issue you ran into.  Would be good to give it a try.  Thanks.
