### ISSUE TITLE
Failed to initialize Powershell Tools for VisualStudioSystem.Reflection Popup

### ISSUE THREAD

**Issue by zaceverett** [adamdriscoll/poshtools#253]
Just downloaded the PowerShellTools.VSIX 07/05/2015 and on opening Visual Studio i receive a Popup Powershell Tools For Visual Studio Error.

In the text box

Failed to initialize PowerShell Tools for VisualStudioSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> 
System.ComponentModel.Composition.ImportCardinalityMismatchException: No exports were found that match the constraint: 
ContractName PowerShellTools.VisualStudioEvents

I'm using Visual Studio 2013 Ultimate 2013 version 12.0.31101.00 Update 4
Windows 7 64 bit.

**Comment by zaceverett** [comment]
Ok, seems to work if i uninstall the extension then add it in again. May be because i hadn't got wmf 4 already installed.

**Comment by markrowsoft** [comment]
How did you get it to uninstall from Visual Studio 2015RC1?
For me the extension doesn't show up in Tools -> Extensions and Updates.
Also fails when trying to uninstall it via the command line.
At this point, I just want to uninstall it and get rid of this error message on VS startup.

**Comment by markrowsoft** [comment]
How did you get it to uninstall from Visual Studio 2015RC1?
For me the extension doesn't show up in Tools -> Extensions and Updates.
Also fails when trying to uninstall it via the command line.
At this point, I just want to uninstall it and get rid of this error message on VS startup.

**Comment by zaceverett** [comment]
I'm only using VS 2013 Ultimate and I see the uninstall as below. Sorry
cant help on VS 2015, may be its not compatible?

[image: Inline images 1]

**Comment by AndreSayreMSFT** [comment]
This was recently fixed with #205 / PR Microsoft#601

**Comment by dozoft** [comment]
It's not fixed in the VS2015 Release. Please reopen the ticket!

**Comment by jinglou-** [comment]
Reactivating.

**Comment by jinglou-** [comment]
For any older builds including build v3.0.152, there was only one VSIX file for both VS2013 and VS2015. v3.0.152 was released around the time VS2015RC was released.  Any builds after v3.0.152, we've separated the VSIX, one for VS2013 and one for VS2015.  Therefore we had to use a different GUID. If you upgraded VS2015RC to RTM and selected to install the PoshTools as a part of the VS setup, the VS setup will automatically remove the older PoshTools on your machine, then install the newer version. However, if you manually upgrade the PoshTools from the VS Extension gallery, you will need to first manually uninstall the older builds of the PoshTools, then install the new one.  Here is the command line to uninstall the older builds (This is noted on the Extension gallery page):

NOTE: You will need to uninstall your previous version of PoshTools to install this version. To remove the "Get PowerShell Tools for Visual Studio" item inside VS2015, run the following command: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe" /admin /uninstall:58dce676-42b0-4dd6-9ee4-afbc8e582b8a

Please let us know if this solves the issue you ran into. I'll leave the issue active until hearing your confirmation. Thanks.

**Comment by MCKLMT** [comment]
@jinglou- 

I had this issue after upgrading from Visual Studio 2015 RC to RTM. 
The following command successfully uninstalled the extension and I don't have the error message at startup anymore:

`"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe" /admin /uninstall:58dce676-42b0-4dd6-9ee4-afbc8e582b8a`

Thanks.

**Comment by jinglou-** [comment]
Thanks for the confirmation.  Closing.

**Comment by swa6589** [comment]
I'm having same issue of powershell whenever I am trying to attach the proccess to my debbuger. I am using VS 2015, Windows 32 bit OS. The below command as suggested by you is not resolving the issue.

Th slight change is I have modifiled to Program files since it is 32 bit OS.

"C:\Program Files \Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe" /admin /uninstall:58dce676-42b0-4dd6-9ee4-afbc8e582b8a" 

Thanks.
