### ISSUE TITLE
Console window from within extension folder opens when Visual Studio lunches

### ISSUE THREAD

**Issue by xperiandri** [adamdriscoll/poshtools#257]
When I lunch Visual Studio 2013 / 2015 RC with installed extension a console window opens for a moment and closes.
Path in that console window points to this extension folder.

Why that console window opens?

**Comment by AndreSayreMSFT** [comment]
Hi @xperiandri !  Thanks for reporting this!  This has already been fixed up [ see Microsoft#384 ]   If brave, feel free to verify the fix from our nightly builds at http://aka.ms/get-poshtoolsNightly !
