### ISSUE TITLE
PoshTools is removing TFS commands from the right click menu

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshtools#258]
-- More info pending

**Comment by GeekActual** [comment]
Sorry I can't offer much insight, I can only report what I have seen.

On Monday I installed your extension’s update on a VM machine that we are using with Visual Studio 2015 RC. Sometime later that day I noticed that in that VM for just VS 2015 RC my TFS right mouse click in Solution Explorer, and in Source Control Explorer, no longer had the commands for Get Latest, Get Version… Check in…

Some of the TFS commands were still available (like Advanced >), but the really important ones I used everyday… they were missing. I didn’t think much about it or put the two events together, until yesterday, when I was working with Visual Studio 2015 RC on my personal Dev machine, doing my normal daily work, checking in and checking out, when I noticed there were notifications about updates, and lo and behold, there was that update to the Powershell Extension that I had installed yesterday on the VM machine. So I clicked Update…

Now my personal machine has exactly the same problem, the context menus for TFS commands for Get Latest, Check in… Get Version… etc are now missing from my Dev machine as well.

Still haven’t been able to figure out how to restore them, I have to go into VS 2013 to access the operations from within it’s Source Control Explorer, or I can access them from the Tool bar in Source Control Explorer

![missingtfscontextmenuselections](https://cloud.githubusercontent.com/assets/11168104/7725860/439eeb80-fecc-11e4-9bec-3bc049c8995b.png)
![missingtfscontextmenuselections2](https://cloud.githubusercontent.com/assets/11168104/7725886/75f1d728-fecc-11e4-88fe-b558656628b8.png)

I also installed the update on my VS 2013 installation and it works fine...

Don't know what to say.

**Comment by AndreSayreMSFT** [comment]
@GeekActual I'm trying to reproduce this, and, no luck as of yet:

![image](https://cloud.githubusercontent.com/assets/10080679/7737031/0d493154-fefd-11e4-9b2e-e504cdcc5545.png)

As sanity, if you disable the PowerShell tools extension, does the TFS menu return?

**Comment by GeekActual** [comment]
That was the first thing I tried… sadly, no

I’ve had not luck getting them back on either machine, not sure what to do now…

Matthew
ACME AtronOmatic, LLC.

**Comment by AndreSayreMSFT** [comment]
What if you run `devenv /setup` ?

**Comment by GeekActual** [comment]
That restores the standard stuff, but not the TFS context menus.  I suspect I’ll need to uninstall the TFS stuff and then reinstall it to get the menus to come back.

Oh well, that is what we expect from Beta software, and I went into this with eyes open!  If no one else has reported it, and you guys can’t reproduce it… If I were sitting in your chair, I would close this bug out with a “Sorry about that”!
If I’m the only one who has seen it, who knows what particular mix of steps I did to cause the problem.

Thanks anyways for looking into it and replying.  Good luck and keep up the good work.


Matthew
ACME AtronOmatic, LLC.

**Comment by GeekActual** [comment]
Hey Guys, 

Looks more and more like this is a problem that isn't your fault but has something to do with installing the RC over the CTP.  Different people are reporting this problem for different reasons

https://connect.microsoft.com/VisualStudio/Feedback/Details/1297121
https://connect.microsoft.com/VisualStudio/Feedback/Details/1308421

MS is telling people to run /repair.

I think it is safe to close this out, thanks for looking into, sorry I wasted your time.

**Comment by AndreSayreMSFT** [comment]
Thanks for following up and letting us know!

And no worries about the red-herring -- Better to double check than to potentially have this be an issue!

Closing this out
