### ISSUE TITLE
Missing Powershell 32 or 64 Bit Setting

### ISSUE THREAD

**Issue by MarkusWild** [adamdriscoll/poshtools#259]
Hi,

I am running a Powershell script within Powershell Tools that loads a x86 dll. This worked fine until I installed the new Version  3.0.134.

I have read that since Version  3.0.108 there is X64 Support implemented now.

My Question: Is there a configuration Setting that allows me to select the desired Target Platform?

Thanks for your reply.

Markus Wild

![poshtools](https://cloud.githubusercontent.com/assets/11989851/7770444/b6724800-008e-11e5-8066-462f1e721166.png)

**Comment by adamdriscoll** [comment]
@MarkusWild Can you try one of the Microsoft dev builds? This option was added there but hasn't been merged into this repo yet. https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev/artifacts

See:
https://github.com/Microsoft/poshtools/issues/48

**Comment by MarkusWild** [comment]
Hi Adam,

The Setting is now available. But I cannot debug into the Script with F5 when Bitness=x86.


Von: Adam Driscoll [mailto:notifications@github.com]
Gesendet: Freitag, 22. Mai 2015 15:28
An: adamdriscoll/poshtools
Cc: Wild, Markus
Betreff: Re: [poshtools] Missing Powershell 32 or 64 Bit Setting (#259)


@MarkusWild<https://github.com/MarkusWild> Can you try one of the Microsoft dev builds? This option was added there but hasn't been merged into this repo yet. https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev/artifacts

See:
Microsoft#48<https://github.com/Microsoft/poshtools/issues/48>

—
Reply to this email directly or view it on GitHub<https://github.com/adamdriscoll/poshtools/issues/259#issuecomment-104660646>.

[Wachsen mit der HOMAG Group]<http://www.homag-group.com/de-de/products/maschinen/Seiten/Werkstattkonzepte.aspx>

More Information<http://www.homag-group.com/en-en/products/machines/Pages/Workshopconcepts.aspx> Mehr Information<http://www.homag-group.com/de-de/products/maschinen/Seiten/Werkstattkonzepte.aspx>

www.homag-group.com<http://www.homag-group.com/>
Newsletter<http://www.homag-group.com/de-de/news/newsletter/Seiten/Newsletter.aspx>

Homag Holzbearbeitungssysteme GmbH
Gesellschaft mit beschränkter Haftung mit Sitz in D-72296 Schopfloch, Homagstraße 3 - 5; Registergericht Stuttgart HRB 735174
Geschäftsführer: Dr.-Ing. Christian Compera (Sprecher), Ulrich Schmitz, Michael Stotz, Ulrich Walk
Vorsitzender des Aufsichtsrats: Harald Becker-Ehmck

**Comment by adamdriscoll** [comment]
@MarkusWild Now that sounds like a bug. Does it just not break at breakpoints?  /cc: @AndreSayreMSFT

**Comment by MarkusWild** [comment]
@adamdriscoll No it is not only not breaking at the breakpoints, Debugging under Bitness=x86 is broken. /cc: @AndreSayreMSFT

**Comment by AndreSayreMSFT** [comment]
Hi @MarkusWild !  Thanks for reporting this [ Also filed under https://github.com/Microsoft/poshtools/issues/579 ] Would you be willing to verify this fixes things up for you under https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/build/3.0.1137 ?

[standard disclaimer, the original build you were using, and the above, are nightlies, and should be treated as such!]

**Comment by MarkusWild** [comment]
Hi @AndreSayreMSFT Debugging under both bitnesses  looks better now. The Debugger is still hanging one time after switching the bitness from "x86" to  "DefaultToOperatingSystem". After stopping and restarting Debugging again everything works fine. - Thanks for the quick response!

**Comment by AndreSayreMSFT** [comment]
Thanks for verifying that it fixes things for you, @MarkusWild !  With regards to the Debugger hanging, is that when you're switching the bitness in the middle of debug-mode?  Does it make the debugger just stop working, or does it hang all of Visual Studio?

**Comment by MarkusWild** [comment]
Hi @AndreSayreMSFT I can not reproduce the hanging any more. Switiching between bitnesses works fluent now. This morning I rebooted the PC so perhaps this has fixed the Problem.

**Comment by AndreSayreMSFT** [comment]
Thanks!  Closing this out then :)
