### ISSUE TITLE
Using references in PowerShell project 

### ISSUE THREAD

**Issue by skeolan** [adamdriscoll/poshtools#260]
I have a solution containing a Powershell project and a C# library project. I added a reference to the library project into the PowerShell project, but am still unable to load a class from the library in my PS script. Is this a supported scenario? What effect are added references supposed to have in PS projects?

**Comment by adamdriscoll** [comment]
@skeolan Currently, references don't do anything. We are tracking this enhacement with issue #34. There has been some discussion as what to actually do with references in a PowerShell project so I'd love you to chime in.

**Comment by adamdriscoll** [comment]
I'm closing this now as a duplicate of #34 but re-open as you see fit!
