### ISSUE TITLE
An error occurs when I run VS System.ComponentModel.Composition.ImportCardinalityMismatchException

### ISSUE THREAD

**Issue by newapx** [adamdriscoll/poshtools#261]
**System info**
VS 2013 Ultimate Windows 7 x32

**PS info**
Version          : 3.0
CurrentCulture   : ru-RU

**Error Description**
StudioSystem.Reflection.TargetInvocationException: Call Destination
generated an exception. --->
System.ComponentModel.Composition.ImportCardinalityMismatchExc
eption: Not found export operation, appropriate
Limitations:
ContractName PowerShellTools.VisualStudioEvents
RequiredTypeIdentity
PowerShellTools.VisualStudioEvents
   in
System.ComponentModel.Composition.Hosting.ExportProvider.GetExp
orts (ImportDefinition definition, AtomicComposition
atomicComposition)
   in
System.ComponentModel.Composition.Hosting.ExportProvider.GetExp
ortsCore (Type type, Type metadataViewType, String contractName,
ImportCardinality cardinality)
   in
System.ComponentModel.Composition.Hosting.ExportProvider.GetExp
ortedValueCore [T] (String contractName, ImportCardinality cardinality)
   in
System.ComponentModel.Composition.Hosting.ExportProvider.GetExp
ortedValue [T] (String contractName)
   in
System.ComponentModel.Composition.Hosting.ExportProvider.GetExp
ortedValue [T] ()
   in
Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetS
ervice [T] ()
   in PowerShellTools.Diagnostics.DiagnosticsDialogPage..ctor ()
   --- End of inner exception stack trace ---
   in System.RuntimeMethodHandle.InvokeMethod (Object target,
Object [] arguments, Signature sig, Boolean constructor)
   in System.Reflection.RuntimeConstructorInfo.Invoke (BindingFlags
invokeAttr, Binder binder, Object [] parameters, CultureInfo culture)
   in Microsoft.VisualStudio.Shell.Package.GetDialogPage (Type
dialogPageType)
   in PowerShellTools.PowerShellToolsPackage.InitializeInternal ()
   in PowerShellTools.PowerShellToolsPackage.Initialize ()

**Comment by adamdriscoll** [comment]
Can you try the latest dev build? I believe this issue is resolved. 

https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev
