### ISSUE TITLE
Clear-Host doesn't clear the PowerShell Interactive Window

### ISSUE THREAD

**Issue by pcgeek86** [adamdriscoll/poshtools#265]
The `Clear-Host` command doesn't clear the PowerShell Interactive Window. I would expect this to work.

![image](https://cloud.githubusercontent.com/assets/466713/8064278/eac896b6-0e96-11e5-88ac-ec7390355c5e.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by AndreSayreMSFT** [comment]
@pcgeek86 Thanks for reporting this!

It bugged me as well :)  We've since fixed this up in 

https://github.com/Microsoft/poshtools/issues/140 and https://github.com/Microsoft/poshtools/issues/230 

Do the nightly builds from http://aka.ms/get-poshtoolsNightly fix this up for you?

**Comment by pcgeek86** [comment]
@AndreSayreMSFT Thanks for that quick turn around! How do I download the build from the link you sent me?

**Comment by AndreSayreMSFT** [comment]
I’ve fixed up that link included in the above comment – select the Visual Studio version, and hit ‘Artifacts’ ☺

Until next adventure,

-Andre

**Comment by pcgeek86** [comment]
@adamdriscoll @AndreSayreMSFT Thanks mate, I've moved to Win10 / VS2015 RC. I just installed the nightly build of the extension.

1. `Clear-Host` **works now**!!! Thanks!!
2. The extra spacing between emitted objects is now gone!!

![2015-06-18 09_27_04-start](https://cloud.githubusercontent.com/assets/466713/8234921/391a67fc-159c-11e5-8f43-5a441592c415.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
