### ISSUE TITLE
VS2015 RC :: Test Explorer running 32-bit PowerShell?

### ISSUE THREAD

**Issue by pcgeek86** [adamdriscoll/poshtools#278]
Hello,

I am using the `Test Explorer` window in Visual Studio 2015 Release Candidate (RC) to invoke Pester tests. However, I received an exception in the `Output` window, saying:

> YourAwesomeModule.Tests.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170

I have a separate script file in my PowerShell module Visual Studio project (but not part of the PowerShell module itself), that loads the module and calls `Invoke-Pester`, and this script works successfully. This script is simply named `Run Pester Tests.ps1`.

```
### Install Pester module, if not available
if (!(Get-Module -Name Pester -ListAvailable)) {
	Install-Module -Name Pester -Force -Scope CurrentUser;
}

### Load the PowerShell module in the parent location
& $PSScriptRoot\..\LoadModule.ps1

### Invoke Pester Tests
Invoke-Pester -Path $PSScriptRoot\..\;
```

I am *reasonably* confident that the Visual Studio 2015 RC `Test Explorer` is invoking Pester tests using 32-bit PowerShell, which I currently have set to a `Restricted` execution policy.

Does this sound like an accurate assessment to you?

## Expected Result

The Visual Studio 2015 RC `Test Explorer` should invoke Pester test scripts using 64-bit PowerShell, or better yet, should provide the option to configure which version to invoke.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by adamdriscoll** [comment]
@pcgeek86 This might just be a Visual Studio setting. Have you changed this at all? 

![image](https://cloud.githubusercontent.com/assets/1256531/9251578/915958d2-4199-11e5-8872-9943a53a2d0d.png)

**Comment by pcgeek86** [comment]
@adamdriscoll Interesting, I wasn't aware of that setting. Thanks for bringing it to my attention! Feel free to close this out, and I'll have you re-open it if it's still an issue. 

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
