### ISSUE TITLE
Start debug does not reload PS Session

### ISSUE THREAD

**Issue by alinmircea** [adamdriscoll/poshtools#279]
Assigning a value to a variable is problematic when combined with testing if the variable exists. Take for instance:

if(-not(Test-Path variable:foo))
{
    $foo = 'bar'  
}

In the first run through everything will work wonderfully since the variable does not exists. Suppose however that during development I realize 'bar' is not the value the variable should have and I change it to 'test'. I then run the debugger again but my variable will never have the value of 'test' since my variable exists and its value is 'bar'

Debugging the script should start a new PS session.

Workaround: Kill the PowerShellToolsProcessHost.exe process before starting debugging.
##

**Comment by alinmircea** [comment]
Additionally, this would work if added at the top of the entry point script

if(-not(Test-Path variable:sysvars))
{
	$sysvars = Get-Variable |
	  select -ExpandProperty Name
	$sysvars += 'sysvars'
}
Get-Variable | where {$sysvars -notcontains $_.Name} | foreach {
	Remove-Variable $_.Name
}

**Comment by adamdriscoll** [comment]
I feel like we had an issue around this previously but I can't find it anywhere! This would also be helpful when debugging C# assemblies developed in VS so they would get unloaded in between executions.
