### ISSUE TITLE
Missing "PowerShell Module Project" from the New Project list.

### ISSUE THREAD

**Issue by MaxTrinidad** [adamdriscoll/poshtools#280]
After doing the uninstall and install of the new Posh Tool version 3.0.152 for VS 2013, the "PowerShell Module Project" is missing from the "New Project" list.  Only the "PowerShell Script Project" is available.

Thanks,
Max
##

**Comment by jinglou-** [comment]
Can you please share your vsixinstaller_xx.log file in your %temp% folder?  Also, if you can check if you have the project template file for the Module project along with the script project?  Let me know if you need the paths to these files.  Thanks. 
Tell us a little bit about what you did during the setup would also help.

**Comment by MaxTrinidad** [comment]
Add-on installed on Visual Studio 2013 Community Edition.

I check the Template folder under my temp location:
C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\mzw1eety.ewr\ProjectTemplates
and look in the zip file only have one project (for the script) there's no module project in it.  
PowerShellProject.zip (see image)
![poshtoolvs_01_6-30-2015](https://cloud.githubusercontent.com/assets/7338470/8441041/df4734b0-1f43-11e5-87e7-6c0f97e79306.jpg)
Here's my log image 1 and 2:
![poshtoolvs_02_6-30-2015](https://cloud.githubusercontent.com/assets/7338470/8441186/bdad1256-1f44-11e5-8e88-3c9b597899b4.jpg)
![poshtoolvs_03_6-30-2015](https://cloud.githubusercontent.com/assets/7338470/8441188/c2597772-1f44-11e5-9b21-a7148bfe7f5c.jpg)

By the way, I didn't notice this before BUT it was missing on the previous release.

**Comment by adamdriscoll** [comment]
Closing anything that is not 2015\2017 related as I've dropped support for that. Please let me know if you still see this in recent versions of VS.
