### ISSUE TITLE
Get-Credential : There is a problem in the PowerShell host service.

### ISSUE THREAD

**Issue by EvtK** [adamdriscoll/poshtools#287]
Hi there,

Been trying to get the Powershell Tools to work, since I'm looking for a good IDE for Powershell. Managed to install the package and create an empty powershell project to be able to start debugging.

When I run one of my scripts, I get the following error:

[ERROR] Get-Credential : There is a problem in the PowerShell host service.

This is just a basic PS command to get a window to enter windows credentials. 

Do I need to load something else to get this to work?

Thanks!

**Comment by EvtK** [comment]
Some more information on this one, I have tried and debugged a little more. Seems to be only happening when I pass in the message string as a variable.

    #$message = "Please provide domain\username and password to connect to the site. Press cancel when using Windows Authentication."
    $credentials = Get-Credential -Message $message

This gives the error.

But no error when I use it like $credentials = Get-Credential -Message "the message"

**Comment by erwindevreugd** [comment]
Max message length is 100 characters. Seems to be by design in the credentials dialog implementation of Powershell tools. Property throws an exception when message length exceeds 100 characters
