### ISSUE TITLE
Pester Adapter Fails If Pester Was Installed From Powershell Gallery

### ISSUE THREAD

**Issue by mattmcnabb** [adamdriscoll/poshtools#292]
Attempting to use the Pester test adapter in the Test Explorer fails if Pester was installed using PSGet from the Powershell Gallery. This seems to be a module path issue even though the PSGet module directory is in $env:PSModulePath.
![testexplorer](https://cloud.githubusercontent.com/assets/6998507/8875641/a9499008-31e8-11e5-9027-b9aea3cc6a69.png)

The issue may be that PSGet supports versioning of modules. The host may be expecting:
C:\Program Files\WindowsPowerShell\Modules\Pester\

but Pester is actually installed here:
C:\Program Files\WindowsPowerShell\Modules\Pester\3.3.9\
##

**Comment by sinaja** [comment]
This is still a problem in VS 2017; is there a work around?

**Comment by adamdriscoll** [comment]
@mattmcnabb @sinaja Is this an architecture issue? For example, if you run Install-Module Pester from an x64 PowerShell prompt, it installs into C:\Program Files\WindowsPowerShell. If you install it via an x86, prompt, it goes to C:\Program Files (x86)\WindowsPowerShell. By default the Visual Studio test adapter runs x86 so I could see the problem there. 

I just tested this and was able to load pester fine from the PsGet location. PoshTools is just calling Import-Module -Name Pester to load pester if it doesn't find it in the Solution\Test directory.

**Comment by mattmcnabb** [comment]
Wow, this is a blast from the past! I had forgotten about this. Yes, I think it was an architecture issue. Pester seems to be included in both Program Files folders now in Windows 10, and the test explorer works without issue, at least for me.

**Comment by adamdriscoll** [comment]
@mattmcnabb Doing some house cleaning. ;) Thanks!
