### ISSUE TITLE
Breakpoints not hitting as expected

### ISSUE THREAD

**Issue by erwindevreugd** [adamdriscoll/poshtools#306]
Steps to reproduce:
* Create a Script.ps1 with a number of Write-Host commands
* Set breakpoints on each line
* Hit F5 to debug
* Keep hitting F5 to continue

The debugger will not hit all of the breakpoints but will hit them apparently at random and not all of them.

**Comment by MrayerMSFT** [comment]
@erwindevreugd, a few questions for you:
1. Is this consistently happening to you?
2. Does VS show all of the breakpoints in the breakpoint window?
3. If you run "Get-PSBreakpoint" in the REPL window, do all of the breakpoints print out?

**Comment by erwindevreugd** [comment]
@MrayerMSFT Thanks! I was able to reproduce it consistently yesterday so I didn't look any further and thought I'd pick it up this morning. However I'm not able to reproduce it today. I'll do some more testing and will let you know.

**Comment by erwindevreugd** [comment]
@MrayerMSFT I cannot reproduce it anymore either. I guess you can close this issue. I'll open a new one if I ever come across it again.
