### ISSUE TITLE
Read-eval-print loop

### ISSUE THREAD

**Issue by FlintSable** [adamdriscoll/poshtools#309]
Hi there, 
Sorry to bug you for this. I am having trouble finding the repl for the poshtools for visual studio 2015 community. Do you have some documentation on that? 

Thank you, 
Nicholas

**Comment by HuanhuanSunMSFT** [comment]
Hi @FlintSable, please Go to View -> Other Windows -> PowerShell Interactive Window or Use the shortcut: Ctrl+Shift+\

**Comment by FlintSable** [comment]
Super, thank you so much
