### ISSUE TITLE
Can't comment/uncomment selection

### ISSUE THREAD

**Issue by tbergstedt** [adamdriscoll/poshtools#311]
I am not able to use Comment/Uncomment Selection commands in powershell files anymore. Whenever I do, I receive the message "The key combination (Ctrl+K, Ctrl+C) is bound to command (Comment Selection) which is not currently available". I am fairly sure those commands were available in previous releases? I'm using verssion 3.0.163 in Visual Studio 2013 now.

**Comment by adamdriscoll** [comment]
Can you try on the 177 release? https://github.com/adamdriscoll/poshtools/releases/tag/v3.0.177

**Comment by tbergstedt** [comment]
Working, thanks! (Was using the latest version provided by Visual Studio Gallery).

**Comment by adamdriscoll** [comment]
Great!
