### ISSUE TITLE
Issue when comparing Powershell files in Visual Studio

### ISSUE THREAD

**Issue by robertwwebb** [adamdriscoll/poshtools#312]
My versions of Visual Studio and PS Tools are as follows:

VS Enterprise 2015 v14.0.23107.0 D14REL
PS Tools for VS 2015 v3.0.177

1) Code Review Compare

When doing a Visual Studio code review the first Powershell file I try to compare throws an exception.  Comparisons on other files are successful.  Nothing happens (i.e. no exceptions appear to be thrown, no file content displayed, no comparison displayed) on further attempts to compare the first file.

Inspecting Visual Studio's ActivityLog.xml, the exception is as follows:
  <entry>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Differencing.Implementation.DifferenceViewer.ScrollToChange(Difference difference)&#x000D;&#x000A;   at Microsoft.TeamFoundation.CodeReview.Controls.DiffViewViewModel.ScrollToFirstDifference()&#x000D;&#x000A;   at Microsoft.TeamFoundation.CodeReview.Controls.DiffViewViewModel.InitialScrollOnDiffViewOpened()&#x000D;&#x000A;   at Microsoft.TeamFoundation.CodeReview.Controls.DiffViewViewModel..ctor(SelectionNavigationState sharedState, CommentsModel commentsModel, IWpfTextView view, IDifferenceViewer diffViewer, DifferenceViewType viewType, String fileServerPath, IAdornmentLayer layer, IVsWindowFrame frame, IEditorFormatMap formatMap, IEditorOperations editorOperations)&#x000D;&#x000A;   at Microsoft.TeamFoundation.CodeReview.Components.DiffTextViewCreationListener.CreateViewModel(IWpfTextView textView, IDifferenceViewer diffViewer, DifferenceViewType viewType)&#x000D;&#x000A;   at Microsoft.TeamFoundation.CodeReview.Components.DiffTextViewCreationListener.&lt;&gt;c__DisplayClass5.&lt;InitializeComments&gt;b__3()&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   at Microsoft.TeamFoundation.CodeReview.Components.DiffTextViewCreationListener.InitializeComments(IWpfTextView textView, IDifferenceViewer diffViewer, DifferenceViewType viewType)&#x000D;&#x000A;   at Microsoft.TeamFoundation.CodeReview.Components.DiffTextViewCreationListener.&lt;&gt;c__DisplayClass1.&lt;InitializeCommentsWhenDiffInitialized&gt;b__0(Object o, SnapshotDifferenceChangeEventArgs a)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)</description>
  </entry>

The exception is not thrown if I open a Powershell file in the IDE before attempting the comparison.

2) Normal Compare

When doing a Compare on any Powershell file (either right-click and select Compare, or by viewing History and then comparing 2 different versions) the first attempt fails.  The comparison window opens, but doesn't load anything.  Subsequent comparisons (on any file, including the first one which failed) work correctly.

**Comment by HuanhuanSunMSFT** [comment]
Looks like related to this issue: https://github.com/Microsoft/poshtools/issues/689
@robertwwebb can you see a successful comparison second time you diff a PS file?

**Comment by robertwwebb** [comment]
When doing a regular compare, yes.  When running a comparison while doing a code review the first file fails and the second one works correctly.  Subsequent attempts to compare the first file fail.

**Comment by Brunas** [comment]
Hi,

The same for VS Premium 2013 12.0.40629.00 Update 5. I cannot do PS code reviews the way I used to. Uninstalling till this is fixed.

**Comment by adamdriscoll** [comment]
Can you guys try this build? https://ci.appveyor.com/project/adamdriscoll/poshtools/build/3.0.244/job/0eyy19vlpbolj31p/artifacts

**Comment by adamdriscoll** [comment]
Closing for now since someone else verified but please re-open if that build does not fix your issue.

**Comment by Brunas** [comment]
@adamdriscoll,

I've checked 3.0.244 and it worked perfectly on VS Enterprise 2015 v14.0.23107.0 D14REL. 

Thanks :)

**Comment by adamdriscoll** [comment]
@Brunas Great! Thanks for checking.

**Comment by msorens** [comment]
... but it fails to install in VS2013 Premium. :-( 
(I suspect you've built it only for VS2015)

**Comment by adamdriscoll** [comment]
@msorens The VS2013 build is available here: https://ci.appveyor.com/project/adamdriscoll/poshtools/build/3.0.244/job/xlj2jx9deq5h90p2/artifacts
