### ISSUE TITLE
Project type (.pssproj) is not supported by this version of the application. 

### ISSUE THREAD

**Issue by techretary** [adamdriscoll/poshtools#317]
Greetings, looking for help getting poshtools to run.

After installing extension - trying to create new Powershell Project (module or otherwise) - i get the following error. I tried uninstalling/reinstalling - nothing appears to help. I searched the web for previous reports - no hits. 

I am running VS 2013 ultimate. Vanilla in every other respect i can think of. Really a bummer - stuck with PowerGUI otherwise.

Error details:

'...\AppData\Local\Temp\ah5jn4yz.wsh\Temp\PowerShellModuleProject3.pssproj' cannot be opened because its project type (.pssproj) is not supported by this version of the application. 

To open it, please use a version that supports this type of project.

Thanks in advance for your help.

**Comment by techretary** [comment]
Hi,

I posted the same question here, as well as on Visual Studio Gallery:

https://visualstudiogallery.msdn.microsoft.com/f65f845b-9430-4f72-a182-ae2a7b8999d7

I am still experiencing the problem. Appreciate any information or help..

**Comment by adamdriscoll** [comment]
That's bizarre. Can you try and get a VS activity log?

**Comment by techretary** [comment]
Hi Adam,


Thanks for your reply. I am currently out of the office until 14th - once back i will send you the information you need. Hopefully it will be helpful to get this sorted.


Thanks!


Vlad.


________________________________

**Comment by afdabro** [comment]
I had the same issue. Depending on your version upgrades from Visual Studio Extension manager are not supported. I resolved my issue by performing the following steps:

1. Remove PowerShell Tools extension through Visual Studio's extension manager
2. Close and reopen Visual Studio
3. Open the extension manager and verify the powershell extension is not installed. If it is, uninstall the version (I had two side-by-side versions v3.0.108 and v3.0.152) and reopen visual studio.
4. Install the latest version of PowerShell Tools

https://visualstudiogallery.msdn.microsoft.com/f65f845b-9430-4f72-a182-ae2a7b8999d7

I hope this helps. 

Cheers,
Andy

**Comment by techretary** [comment]
Thank you, i will give it a spin. I have been pulled into an entirely different direction and haven't had to work with powershell recently, but i am still definitely interested in getting this resolved for the next time i need it again.

Sent from a mobile device with all the downsides of typing on a tiny screen with a virtual keyboard.

On Oct 29, 2015, at 2:05 PM, afdabro <notifications@github.com<mailto:notifications@github.com>> wrote:


I had the same issue. Depending on your version upgrades from Visual Studio Extension manager are not supported. I resolved my issue by performing the following steps:

  1.  Remove PowerShell Tools extension through Visual Studio's extension manager
  2.  Close and reopen Visual Studio
  3.  Open the extension manager and verify the powershell extension is not installed. If it is, uninstall the version (I had two side-by-side versions v3.0.108 and v3.0.152) and reopen visual studio.
  4.  Install the latest version of PowerShell Tools

https://visualstudiogallery.msdn.microsoft.com/f65f845b-9430-4f72-a182-ae2a7b8999d7

I hope this helps.

Cheers,
Andy

-

**Comment by techretary** [comment]
Hi! I've had to get back into powershell - and wanted to avoid having to work with Powershell ISE. So i followed your steps - and they worked! The problem is resolved.


I am not quite sure what the difference between what i tried (i tried removing and reinstalling) and what you recommended, but the fact is, it now works!


Thanks!


________________________________
