### ISSUE TITLE
Unable to open PowerShell projects with VS 2015 after extension update

### ISSUE THREAD

**Issue by Segelfeldt** [adamdriscoll/poshtools#318]
I am running VS Enterprise 2015 i noticed that i had a new update ready for PowerShell Tools (3.0.177). After the update i am unable to open PowerShell projects even newly created projects.

When i open the project i get "Microsoft Visual Studio 2015 has stopped working"

I tried uninstalling and reinstalling the extension but i get the same result.

**Comment by adamdriscoll** [comment]
Is there anything in the VS activity log? http://blogs.msdn.com/b/visualstudio/archive/2010/02/24/troubleshooting-with-the-activity-log.aspx

If there is a crash dump generated, could you send a stack trace?

**Comment by Segelfeldt** [comment]
So it seems to work now, i were going to sned you a activyt log but when i were goint to reproduce the crash i am unable to. I guess we can close this.
