### ISSUE TITLE
Deploy option/method?

### ISSUE THREAD

**Issue by dsolodow** [adamdriscoll/poshtools#321]
I'm new to VS, so it may just be a derp. 
Is there a way to have VS "deploy" a PowerShell script or module? 

So for modules as an example, I'd want to either be able to copy the set of module files to a folder (or group of folders), and/or do a publish-module to put it in a gallery.

Scripts would probably just be a "copy to directory"
##

**Comment by adamdriscoll** [comment]
I love this idea and think it would be super useful. It's also related to #33.

**Comment by ferodom** [comment]
I have tried this but the afterbuild is not executing any ideas?
```
<Target Name="AfterBuild">
    <Exec Command="xcopy $(ProjectDir)*.ps1 \\crg-app-dev\c$\C360 Scripts" />
    <Exec Command="xcopy $(ProjectDir)*.ps1 \\crg-app-uat\c$\C360 Scripts" />
  </Target>
```

**Comment by adamdriscoll** [comment]
@ferodom @dsolodow This works with the project system upgrade. 

For example:

```
  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
   <Target Name="Build">
      <Exec Command="xcopy &quot;$(ProjectDir)*.ps1&quot; &quot;$(ProjectDir)\bin\debug&quot;" />
   </Target>
```

I'm going to look at making this use case easier.

**Comment by adamdriscoll** [comment]
Implemented with build events in #530

**Comment by ferodom** [comment]
I'll test it this week. Thanks a lot!

**Comment by artisticcheese** [comment]
Is there a documentation how this works? I also don't see any of those in release notes for June update.

**Comment by adamdriscoll** [comment]
June release will be coming in about a week.

**Comment by adamdriscoll** [comment]
@artisticcheese Documentation can be found here: https://poshtools.com/docs/poshtools-docs/build-events/
