### ISSUE TITLE
Interactive Window defaults to C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE>

### ISSUE THREAD

**Issue by paulschmeida** [adamdriscoll/poshtools#324]
Interactive shell always opens C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE when started. Would be better if it opened current project location by default. If no projects are currently opened, it could open the last active project location or projects root (parent folder to project folders). This would be similar to the way JetBrains PyCharm and other JetBrains IDEs handle docked shell windows and I think it would be better that opening the VS install location.
##

**Comment by AndreSayreMSFT** [comment]
Related to https://github.com/adamdriscoll/poshtools/issues/169 

Thinking out loud: It'd be cool to have [as a toggleable setting in the REPL Window!] the current location to follow the ActiveDocument around.  Or maybe the Project.
