### ISSUE TITLE
No horizontal scroll bar when PowerShell Command Explorer is very narrow

### ISSUE THREAD

**Issue by v-ldavid** [adamdriscoll/poshtools#339]
Config: 
Dev12 Ult + Latest PowerShell Tool(https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/branch/dev) on Win 8.1 Ent x86

Repro Steps:
1. Launch VS and open the Command Explorer.
2. Adjust Command Explorer width to small.

Expected: There is a horizontal scroll bar.
Actual: No horizontal scroll bar. see below screenshot.
![commandexplorer](https://cloud.githubusercontent.com/assets/12929699/9930995/4d6dc2d8-5d6a-11e5-9dd8-9570403b30aa.png)

**Comment by erwindevreugd** [comment]
Thanks for reporting this issue. Just to clarify: would you expect a horizontal scrollbar for just the buttons container or for the entire window content?
