### ISSUE TITLE
Performance Issues in Visual Studio 2015

### ISSUE THREAD

**Issue by tomkerkhove** [adamdriscoll/poshtools#347]
When using the PowerShell tools for Visual Studio 2015 I have performance issues without any clear cause.

Some examples that might trigger it are comparing PoSH scripts with TFS compare, editing the script, opening the solution.

Information about the script I've had issues with is a script of +/- 230 lines with multiple functions in it.

I know this is very few information but those are the conclusions I've made. Uninstalling the tool fixes my issues...
##

**Comment by adamdriscoll** [comment]
That's not a very big script so it shouldn't be an issue. When you say performance issues, do you see it hang for long periods of time?

**Comment by tomkerkhove** [comment]
My thoughts exactly... Visual Studio was not responding anymore or loading very very slow.

I'll keep an eye out for patterns that might help you...

**Comment by adamdriscoll** [comment]
Ok. If it ever stops responding and you have time to grab a memory dump. That would be really, really helpful. You can use Task Manager to do it. 

C:\windows\syswow64\taskmgr.exe 

In the details tab, right click on devenv.exe and PowerShellToolsHostService.exe and click create dump file. That should give me a really good view of where it's hanging. 

You can also use procdump to do the same thing. 

procdump -h devenv.exe -ma

**Comment by adamdriscoll** [comment]
Procdump will actually watch for a hang though. If Visual Studio hangs for more than 5 seconds, procdump would create a dump file.

**Comment by tomkerkhove** [comment]
I'll create a dump file when it occurs again, thank you for your quick reply!

**Comment by tomkerkhove** [comment]
It seems like the *PowerShellTools Host Service* is trying to start an instance of the *PowerShellTools Host Service Console* but it fails, retries, fails again, retries, etc.

I think it always occures when I'm trying to attach the debugger to something...

**Comment by adamdriscoll** [comment]
@tomkerkhove Could you try this version and scoop up a log? I added more logging to see if we can figure this out. Logging now outputs to %AppData%\PowerShell Tools for Visual Studio\log.txt

https://ci.appveyor.com/project/adamdriscoll/poshtools/build/job/rm3srfcsvgrfb6p7/artifacts

This is how you enable logging: https://github.com/adamdriscoll/poshtools/wiki/Debugging-PowerShell-Tools-for-Visual-Studio

**Comment by tomkerkhove** [comment]
I've simulated the "Attach to process" scenario and my guess was right - He's having troubles firing up an instance of the _PowerShellTools Host Service Console_

You can find the log file here - https://www.dropbox.com/s/vecm5wcwhprgdbg/2015-09-28-Connect-to-process-simulation.txt?dl=0

**Comment by adamdriscoll** [comment]
Can you run this command line once? 
[Enum]::GetValues([Microsoft.PowerShell.ExecutionPolicyScope]) | % { "$_ - $(Get-ExecutionPolicy -Scop
e $_)" }

**Comment by tomkerkhove** [comment]
Here's the result -
![posh-execution-policies](https://cloud.githubusercontent.com/assets/4345663/10156473/ca12e7d0-6681-11e5-9d11-ffc0f9f241c2.png)

**Comment by adamdriscoll** [comment]
I think I see what the issue is. Let me take a stab at fixing it. Is this setting set to True in Visual Studio on your box? 

![image](https://cloud.githubusercontent.com/assets/1256531/10171964/58b12752-66a2-11e5-90b8-4fbba691808d.png)

**Comment by tomkerkhove** [comment]
Yes, it's set on `True` by default

**Comment by adamdriscoll** [comment]
If you set it to false, do you still experience this issue?

**Comment by whvanderpost** [comment]
My PowerShell execution policy is as follows (pushed by our sysadmins via group policy):
Process - Undefined
CurrentUser - Undefined
LocalMachine - Unrestricted
UserPolicy - Undefined
MachinePolicy - Undefined

Setting the 'Enable Unrestricted Execution Policy' to false does not resolve the issue.

FYI: I don't have a PowerShell file open in Visual Studio when I click 'Attach to process'

**Comment by adamdriscoll** [comment]
Can one of you try this build once it's done? https://ci.appveyor.com/project/adamdriscoll/poshtools/build/3.0.270

It should prevent the host process from crashing when attempting to set the execution policy and failing.

**Comment by tomkerkhove** [comment]
Closing since I didn't follow up on this and it has been too long
