### ISSUE TITLE
$host.privatedata displays nothing

### ISSUE THREAD

**Issue by dafuni** [adamdriscoll/poshtools#351]
Using the Powershell tools on Visual Studio Professional 2015 running on Windows 10 pro RTM and I observe that $host.privatedata displays nothing.

![host_privatedata](https://cloud.githubusercontent.com/assets/5445383/10121477/82ab6f4c-64bb-11e5-9eb6-fd7775f66a20.png)

against the following in ISE

![host_privatedata_ise](https://cloud.githubusercontent.com/assets/5445383/10121482/e5131310-64bb-11e5-80e9-f62d9031c05c.png)

is it possible to add support for this?
##

**Comment by AndreSayreMSFT** [comment]
Related to https://github.com/Microsoft/poshtools/issues/583  

Kind of curious: What types of things do you plan to use the info in PrivateData for?

**Comment by dafuni** [comment]
I would like to change error / verbose colors to what I want. ISE displays verbose messages in Cyan, warning in yellow. VS displays these in white. I prefer the cyan or any other color that make it distinct.
Is there  way I can achieve that with VS?

**Comment by adamdriscoll** [comment]
You can change these settings in Tools->Options->Fonts and Colors

**Comment by dafuni** [comment]
ok. I'll try that. Thanks

Sent from Outlook<http://aka.ms/Ox5hz3>




On Thu, Oct 8, 2015 at 9:05 AM -0700, "Adam Driscoll" <notifications@github.com<mailto:notifications@github.com>> wrote:


You can change these settings in Tools->Options->Fonts and Colors

-
