### ISSUE TITLE
VS2015 hangs when open files layout change.

### ISSUE THREAD

**Issue by Patrikwa** [adamdriscoll/poshtools#354]
Im using 4 tab groups to show my files, some of the files are pinned and some are not. When resizing main window or opening/closing files, the remaining file tabs have their layout updated which means some files are on the same row and some are moved to row2, row3 etc. 
The bug is that sometimes a file is moved to row2 and then back to row1, then back to row2, row1, row2,row1... in an endless loop, rendering VS2015 unresponsive.

**Comment by adamdriscoll** [comment]
Are these files only PS1s? And this doesn't happen without PoshTools?

**Comment by Patrikwa** [comment]
Uh i must have been extremely tired yesterday, this bug report is supposed to be for "Productivity Power Tools", no freakin' idea how it ended up here haha, feel free to remove :)

**Comment by adamdriscoll** [comment]
Good to hear :D
