### ISSUE TITLE
[PoshTools]VS crash after copying the command "Set - BitsTransfer" in PowerShell Command Explorer

### ISSUE THREAD

**Issue by v-jannwa** [adamdriscoll/poshtools#355]
OS version: Dev12 + Update5
PoshTools build: https://github.com/adamdriscoll/poshtools/releases/tag/v3.0.231 
Repro steps:
1. Open the PowerShell Command Explorer windows.
2. Search the command "Set - Bits Transfer", then double click it.
3. click the Copy button to copy the command.

Actual:
VS will crash afer clicking the copy button, you can see the dump file from \\trinlab2\BAQAFiles\CloudToolsTest\v-jannwa\Crash.DMP to get the details.

MoreInfo:
if the command contains at least one parameter, vs not crash after clicking the copy button

**Comment by erwindevreugd** [comment]
Thank you for reporting this issue. Unfortunately I'm unable to reproduce the issue given the steps provided and cannot locate the crash dump. Could you provide any further details on the exception?

**Comment by adamdriscoll** [comment]
Could you upload the DMP file to OneDrive or something so we can download?

**Comment by adamdriscoll** [comment]
Has something to do with the Clipboard.SetText. Not getting good exception info back though....hard without symbols. 

![image](https://cloud.githubusercontent.com/assets/1256531/10229572/853d94de-683e-11e5-86cb-46365f91d24e.png)

**Comment by adamdriscoll** [comment]
Is it possible that the string is null or empty that we are passing to the SetText function? 

![image](https://cloud.githubusercontent.com/assets/1256531/10229897/ff2ddf8c-683f-11e5-8f27-f957ebca8a51.png)

**Comment by erwindevreugd** [comment]
That could be the case. However, the same method that is called to format the text is called to create the text for the preview text (wpf textblock might be able to deal with the null value) and should always contain at least the command, so something else is likely causing the returned value to be null. Did you manage to reproduce the exception?

**Comment by adamdriscoll** [comment]
I didn't. I think I'm just going to pull your PR and then release. It should be at least stable until we figure it out.

**Comment by erwindevreugd** [comment]
#356 should prevent a VS crash. Given the info you've provided about the settext method I'm thinking it's at least a good idea to check the returned value before calling this method.

I'm also thinking it would probably be nice to disable the copy button (and mouse drag/drop) when there's nothing to copy and to add logging using the log feature of poshtools.

Just saw your message popup: I was going to say i'll start adding above features to this PR and let you make the call on when to merge depending on your release schedule.

**Comment by adamdriscoll** [comment]
If you have time, I can wait.

**Comment by erwindevreugd** [comment]
I was planning to do some coding over the coming weekend so if that alright with you then hold of on the merge for a few days.
