### ISSUE TITLE
VS2013 PoshTools: "Exception has been thrown by the target of an invocation"

### ISSUE THREAD

**Issue by chilimangoes** [adamdriscoll/poshtools#368]
I have PoshTools installed in Visual Studio 2013 Ultimate, and I get the following error when I try to open a PS1 script:

```
---------------------------
Microsoft Visual Studio
---------------------------
The 'PowerShellProjectPackage' package did not load correctly.

The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'C:\Users\egglestonjg\AppData\Roaming\Microsoft\VisualStudio\12.0\ActivityLog.xml'.

Continue to show this error message?
---------------------------
Yes   No   
---------------------------
```

Looking at the ActivityLog.xml file doesn't really seem to offer any helpful debugging information. Here are the last four entries of the activity log. Let me know if you would like me to link the entire file as a gist, or if there's any other information that would be helpful.

```xml
  <entry>
    <record>1062</record>
    <time>2015/10/29 00:10:05.441</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [PowerShellProjectPackage]</description>
    <guid>{2F99237E-E34F-4A3D-A337-500E4B3167B8}</guid>
  </entry>
  <entry>
    <record>1063</record>
    <time>2015/10/29 00:10:05.442</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [PowerShellProjectPackage]</description>
    <guid>{2F99237E-E34F-4A3D-A337-500E4B3167B8}</guid>
    <hr>80131604</hr>
    <errorinfo>Exception has been thrown by the target of an invocation.</errorinfo>
  </entry>
  <entry>
    <record>1064</record>
    <time>2015/10/29 00:10:05.442</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [PowerShellProjectPackage]</description>
    <guid>{2F99237E-E34F-4A3D-A337-500E4B3167B8}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Exception has been thrown by the target of an invocation.</errorinfo>
  </entry>
```

I've googled and looked at the other issues I was able to find with similar error messages, however none of those seemed applicable. The strange thing about this error I'm getting is that there doesn't seem to be any stack trace or other information about what the underlying exception is.

**Comment by adamdriscoll** [comment]
Can you try and grab a log? It may not work since this is happening during initialization.

https://github.com/adamdriscoll/poshtools/wiki/Debugging-PowerShell-Tools-for-Visual-Studio

**Comment by chilimangoes** [comment]
Opening the PowerShell settings gave me a message about not having the correct version of Windows Management Framework installed. After installing the latest version, PoshTools is working. I don't know if this is possible, but displaying that message during initialization might save a few headaches. Regardless, thanks for the help and sorry for the trouble.

**Comment by adamdriscoll** [comment]
No problem! It should be popping up. Must be an issue with that. Thanks for getting back to me.
