### ISSUE TITLE
All code after a backtick or the Invoke operator (&) is colored as a string

### ISSUE THREAD

**Issue by nwhiteBT** [adamdriscoll/poshtools#377]
This doesn't seem to be an issue with .psm1 PowerShell module files, but it's happening on my parent (or controller) scripts, which are .ps1 files:

![image](https://cloud.githubusercontent.com/assets/15741937/11044044/82a147de-86d4-11e5-9c7e-7dcfefaeb5e8.png)

This is for version 3.0.292.

**Comment by nwhiteBT** [comment]
Here is the identical code in PowerShell ISE:

![image](https://cloud.githubusercontent.com/assets/15741937/11044123/dd2862c8-86d4-11e5-97af-172123dff432.png)

**Comment by nwhiteBT** [comment]
Sry, I almost forgot to include my environment info:
Windows 10 (x64)
Visual Studio Enterprise 2015
.NET 4.6
PowerShell v5

**Comment by ChrisLynchHP** [comment]
I have the very same issue, but with PSM1 files.  Exact same setup as @nwhiteBT .

**Comment by adamdriscoll** [comment]
Thanks. I know the commit that broke this. I will take a look later this evening.

**Comment by ChrisLynchHP** [comment]
Thanks Adam.  I'm downgrading to the prior release.

**Comment by NizZ8** [comment]
Glad to see someone reported this, was about to open up this issue myself after upgrading to the latest version this morning :).

**Comment by adamdriscoll** [comment]
I rolled back this change for now. Can you guys give this a shot? Expanable strings won't be highlighted, like in the previous version. 

https://ci.appveyor.com/project/adamdriscoll/poshtools/build/3.0.294/job/hsa3w494wtxrw9vx/artifacts

**Comment by ChrisLynchHP** [comment]
The rollback resolved the issue for me.

**Comment by adamdriscoll** [comment]
@ChrisLynchHP Great. I'll close this issue and report #342

**Comment by korygill** [comment]
I get an exception loading the update from the link above.  Still investigating.

**Comment by adamdriscoll** [comment]
Let me know if you can get a little more info about the exception details. Closed this one too quick it seems...

**Comment by korygill** [comment]
I had installed the 235 release https://github.com/adamdriscoll/poshtools/releases/tag/v3.0.235 on my machine, and ran the vsix from the link above.  Not sure why it was looking for the old build after I installed the new one.

activitylog.xml
<entry>
    <record>584</record>
    <time>2015/11/11 22:57:28.698</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.IO.FileNotFoundException: Could not load file or assembly &apos;PowerShellTools.14.0, Version=3.0.235.0, Culture=neutral, PublicKeyToken=32cd18849a3a99f8&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;PowerShellTools.14.0, Version=3.0.235.0, 
<snip>

I uninstalled the extension, and reinstalled 294 from the link above and now it works.

Everything looks good now on the 10+ files I checked.

**Comment by nwhiteBT** [comment]
Worked perfectly on my install. Much appreciated for getting the build out so quickly.

**Comment by adamdriscoll** [comment]
Great!

**Comment by AspenForester** [comment]
I've seen no problems since reinstalling with the reverted build.  Thanks!
