### ISSUE TITLE
Advanced Function Snippet extra dollar signs

### ISSUE THREAD

**Issue by michaeljprentice** [adamdriscoll/poshtools#378]
Thanks so much for adding snippets!  I did notice one thing with the Advanced Function snippet though.  It has two dollar signs for each of the $true.

```powershell
[Parameter(Mandatory=$$true, ValueFromPipelineByPropertyName=$$true,Position=0)]
```

**Comment by adamdriscoll** [comment]
Check this build out. It should fix the issue. 

https://ci.appveyor.com/project/adamdriscoll/poshtools/build/3.0.296/job/spqiacpncp8pgmsd/artifacts
