### ISSUE TITLE
Prompt for WMF 3 Dependency

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshtools#38]
It's not entirely straight forward when WMF3 is not installed. A generic GAC error message is presented. It should instead prompt about the dependency and provide a link to download it.

**Comment by AndreSayreMSFT** [comment]
@bmoore-msft : We'll need a FWLink from you to redirect people when they don't have it installed.

**Comment by bmoore-msft** [comment]
Try this:
http://go.microsoft.com/fwlink/?LinkID=524571

**Comment by AndreSayreMSFT** [comment]
Closing as this is implemented.
