### ISSUE TITLE
Test Explorer marks Pester tests as 'Failed' even though the output window marks them as Passed 

### ISSUE THREAD

**Issue by mbressle** [adamdriscoll/poshtools#385]
![capture](https://cloud.githubusercontent.com/assets/15824146/11132704/545b21dc-8946-11e5-809c-020c3fc17bc4.PNG)
When I run my Pester tests in VS using POSHTools from the PowerShell Interactive Windows and run Invoke-Pester, all of my tests pass as they should. When I run the same set of test from Test Explorer, the explorer marks them as failed, even though the output window shows them as still passing successfully. It appears that this is a bug in which the successful passing result of the pester test isn't being passed back to Test Explorer. Any help you folks can provide would be greatly appreciated.

**Comment by adamdriscoll** [comment]
The test adapter is throwing a Null Ref. Are you on the latest version of Pester?

**Comment by adamdriscoll** [comment]
@mbressle Get a chance could you send me an example test that is causing the issue?

**Comment by bartsaintgermain** [comment]
@mbressle most probably solved in latest version
