### ISSUE TITLE
F12 support for variables (and functions?)

### ISSUE THREAD

**Issue by chaim1221** [adamdriscoll/poshtools#386]
As a Visual Studio 2013 user I'd like to be able to press F12 and go to the definition of a variable (which seems maybe easier to implement) or a function (which could be doable in a single file, but would be harder for global f(x)s as you'd have to grep things).

**Comment by adamdriscoll** [comment]
@chaim1221 Hoping this will come out of #389 as it already supports these features.

**Comment by chaim1221** [comment]
Sounds great, thanks!

**Comment by nwhiteBT** [comment]
PsISEProjectExplorer actually does this already. You can also expand each module in the tree view to see the functions within that module. This would be incredibly useful for debugging and code navigation.

**Comment by chaim1221** [comment]
As long as the object being referenced (a) is a function, and (b) is within the same .ps1 file, this functionality now works in Visual Studio. Major improvement. Thanks.
