### ISSUE TITLE
Unable to cast object of type 'ConstantExpressionAst' to type 'VariableExpressionAst'

### ISSUE THREAD

**Issue by whut** [adamdriscoll/poshtools#387]
I used to debug [psake](https://github.com/psake/psake) scripts from Visual Studio by opening my custom build script and the [psake.ps1](https://github.com/psake/psake/blob/master/psake.ps1) runner script, and then executing the latter in VS. Since few releases of PowerShell Tools it does not work. I do not know which exactly release break that, but it worked few months ago. Now it works only from PowerShell ISE.

**Steps to reproduce**
1. Download [psake.ps1](https://github.com/psake/psake/blob/master/psake.ps1) script
2. Open psake.ps1 in Visual Studio 2015
3. Right click and choose "Execute as Script with Parameters...".

**Expected Result**
Script runs and the output is visible somewhere, in the "PowerShell Interactive Window" or "Output Window".

**Actual Result**
Modal dialog with below message:

> Unable to cast object of type 'System.Management.Automation.Language.ConstantExpressionAst' to type 'System.Management.Automation.Language.VariableExpressionAst'.

Also when I use the "Execute as Script" option, it just does nothing.

**Comment by erwindevreugd** [comment]
Took a quick look at this and it appears to be a parsing\validation error:

Replacing Mandatory=0 with Mandatory=$false should work as a work around.

**Comment by whut** [comment]
Thanks, there is no exception message now, but the script still does not run.

**Comment by whut** [comment]
Looks like the commit fixes the parsing error, but as before, the script does not run. I can run & debug it with ISE, bot not with poshtools.
