### ISSUE TITLE
Visual Studio 15 hangs when I open a PowerShell script file.

### ISSUE THREAD

**Issue by donnamcnair** [adamdriscoll/poshtools#393]
Visual Studio 15 hangs when I open a PowerShell script file.  This is the error from the ActivityLog.xml file.
ERROR CreateInstance failed for package [PowerShellProjectPackage] {5520558A-236B-453B-8CFF-442671DB0BB5} 80131604 VisualStudio 2015/11/27 18:53:50.173 

I found articles suggesting to uninstall and reinstall the PowerShell tools.  However, this command fails. 
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe" /admin /uninstall:5520558A-236B-453B-8CFF-442671DB0BB5

Error: 
VSIXInstaller.NoApplicableSKUsException: The extension with ID '5520558A-236B-453B-8CFF-442671DB0BB5' is not installed to any currently installed products.

When I initially installed PowerShell tools I downloaded this file.  PowerShellTools.14.0.vsix

Can you please provide assistance in uninstalling and reinstalling PowerShell tools for Visual Studio 2015?  Or assistance in resolving the hanging problem when opening a PowerShell script file in Visual Studio 2015?

Thanks,
Donna McNair
##

**Comment by adamdriscoll** [comment]
@donnamcnair Is PowerShell Tools listed in Extension manage as being installed? If so, can you uninstall it from there?

**Comment by donnamcnair** [comment]
Hi Adam,

In VS 2015, I clicked on Tools/Extensions and Updates to uninstall.  However, the file is in use.  I get the same error when attempting to install the latest update.  Any ideas?

Once I get it uninstalled, do you think reinstalling will resolve the problem with opening a PowerShell script file in VS 2015?

**Comment by guitarrapc** [comment]
I tryed reinstall but no luck. Despite of latest version PowerShell Tools for Visual Studio couldn't open several .ps1 and .psproj in Visual Studio 2015 Update 1.
Uninstalling poshtools remove this issue, so far.

**Comment by donnamcnair** [comment]
Hi Adam,

I am still not able to uninstall PowerShell Tools.  I get an error stating that the process cannot access the file because it is being used by another process.

From the previous comment, it is still a problem, so I need to uninstall PowerShell Tools but not reinstall after that.

I hope you can provide some guidance on uninstalling.  Thanks.

**Comment by adamdriscoll** [comment]
@donnamcnair Is the PoshTools host process running when you are trying to uninstall? Might just need to close that. Otherwise, you could run procmon while attempting to do the uninstall and we can take a look at the log to see what's being locked. We can use handle.exe to close that lock if necessary. 

Also, can someone please capture a process dump of devenv when this happens? It should help pin-point the issue.

**Comment by donnamcnair** [comment]
I do not see a process in Task Manager with a name like "poshtools" or "powershell".  What is the PoshTools host process name?  I'll check Task Manager again.

I don't specifically start the PoshTools host process so something must be starting it up.  I rebooted my laptop, opened VS 2015, did not open a solution, and clicked on Tools/Extensions and Updates to uninstall.

Our company restricts the software we can install.  Procmon is not a Microsoft product so I'll have to see if procmon is on the approved list.  If not, is there an alternative tool, perhaps from Microsoft, that I can use to get the information needed?

I'll also research how to capture a process dump of devenv.

**Comment by adamdriscoll** [comment]
The process is: PowerShellToolsProcessHost.exe
 
Procmon is really the only thing I'm aware of that can do something like that. I'm pretty sure Procmon, being part of SysInternals, is technically a Microsoft product. I did have a PowerShell script in PoshInternals that does it but I'm not sure how well it works. 

https://github.com/adamdriscoll/PoshInternals/blob/dev/Handle.ps1

You can capture a dump using Task Manager by right clicking on the process and selecting Create Dump File.

**Comment by donnamcnair** [comment]
I verified that the PowerShellToolsProcessHost.exe process is not displayed in Task Manager.

I produced a dump file.  However, the zipped dump file is about 265 MB which exceeds the limit for this site and for email attachments.

Procmon is approved software for our company.  I will run procmon and see if I can find the lock.  I'll keep you posted.

Thanks.

**Comment by adamdriscoll** [comment]
Closing since I haven't heard back. Feel free to re-open.
