### ISSUE TITLE
Not able to set breakpoint inside module files imported from another script in VS 2015

### ISSUE THREAD

**Issue by etriebe** [adamdriscoll/poshtools#395]
If I've imported a module inside another project (inside the same solution), I'm not able to add a breakpoint to that module file. The only way is the set a breakpoint in the calling script and step all the way to the point where I want to debug inside the module file. This used to work in VS 2013.

**Comment by etriebe** [comment]
Also, the message displayed says, "This is not a valid location for a breakpoint" in the status bar

**Comment by adamdriscoll** [comment]
There is some validation that is causing this to happen. It's a bug. That's for reporting this.

**Comment by barcexwiki** [comment]
This happens on all .psm1 files, even the ones created by default by the wizard. When you press F9 you get "This is not a valid location for a breakpoint" on the status bar.
