### ISSUE TITLE
Case sensitive Visual Studio file icon

### ISSUE THREAD

**Issue by CodeChief** [adamdriscoll/poshtools#397]
I thought my file was wrongly defined in the Visual Studio 2015 Update 1 project file, comparing it to a newly created file, until I realized it was case sensitive. You can re-create it easily:

1. Create a new unit test file, named "PowerShellTest1" which will produce the name "PowerShellTest1.tests.ps1". It has the correct unit test icon (chemical bottle).
2. Rename to "PowerShellTest1.**T**ests.ps1" (upper case T in Tests). It now has the wrong icon.

Just a minior point, but considering your documentation references "Tests.ps1" in multiple places, maybe you should fix it next time you update the VSIX. I am not sure if there were any other side effects, or if other file types have the same problem (best check case insensitivity for all your VS project item templates).

As you are now generating the end of the name (I came across this by tidying-up files generated from an earlier version/initial module project template output) I suppose you could ignore this, but case sensitivity is never a good thing when it is not required.

**Comment by adamdriscoll** [comment]
Ahhh good catch. Thanks

**Comment by cervengoc** [comment]
Hi  @adamdriscoll, this still seems to be an issue in VS 2015 using Powershell Tools version 3.0.582. Could you please have a look at it and reopen if needed?
