### ISSUE TITLE
Syntax coloring is breaking after using VS2015 for a while

### ISSUE THREAD

**Issue by korygill** [adamdriscoll/poshtools#400]
Don't have much to offer yet for a repro, other than load a .ps1 file, edit for a while, and after some time, syntax coloring will go haywire.  Closing and reopening a file fixes this for a while.

[screenshot of issue](http://i.imgur.com/4dyhlRG.png)

after restart (expected result)

[screenshot of expected result](http://i.imgur.com/vWBqpaY.png)

**Comment by adamdriscoll** [comment]
Is it a large script?

**Comment by korygill** [comment]
The script is ~500 lines. I don't have a lot to go on and give better info here yet, was hoping others may have experienced this too, but did not see other reports on build 299 about this. Could it be related to number of files open also? It's been working fine for a while now, but I only have 1 file open.  I was refactoring the project, and now come to think of it, when I clicked a result in Find Results, a 2nd copy of the same file opened sometimes.  Wonder if that is related. (could be a VS bug)  I will keep a more watchful eye on what happens, and report back if I can piece anything together.

**Comment by nferrell** [comment]
Kory,

Is the script being backed up using any cloud sync desktop client, I.e.
Google drive of Dropbox? I've found sometimes with other file formats that
it can cause weird splitting issues on a rare occasion... Just a thought

On Saturday, January 9, 2016, Kory Gill <notifications@github.com> wrote:

> The script is ~500 lines. I don't have a lot to go on and give better info
> here yet, was hoping others may have experienced this too, but did not see
> other reports on build 299 about this. Could it be related to number of
> files open also? It's been working fine for a while now, but I only have 1
> file open. I was refactoring the project, and now come to think of it, when
> I clicked a result in Find Results, a 2nd copy of the same file opened
> sometimes. Wonder if that is related. (could be a VS bug) I will keep a
> more watchful eye on what happens, and report back if I can piece anything
> together.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamdriscoll/poshtools/issues/400#issuecomment-170258816>
> .
>


-- 
Thank you for your time,
Nate Ferrell

**Comment by korygill** [comment]
This is not reproducing anymore.  I am going to close this and if I can get a solid repro, create a new issue.
