### ISSUE TITLE
Got 'Pester' was not loaded when running pester tests

### ISSUE THREAD

**Issue by alan-hu** [adamdriscoll/poshtools#401]
Environment:
Windows 2012 R2 Standard
VS2013 12.0.40629.00 Update 5
PowerShell Tools for VS2013: 3.0.299
Pester module exists at C:\Program Files\WindowsPowerShell\Modules\Pester
version 3.3.14

Steps:
Created a new PowerShell script project and run the OOTB pester tests.

I can manually run PowerShell and execute Pester test suites.

**Comment by adamdriscoll** [comment]
Are you running using the test adapter? 
If so, do you have the test adapter running as x86 or x64?
