### ISSUE TITLE
Executing old versions of code 

### ISSUE THREAD

**Issue by rob-at-work** [adamdriscoll/poshtools#402]
Changing single script file in a new project then when executing getting output as if code was unchanged even though the file said saved.

Restarting Visual Studio fixes it for a "bit".

Also had a weird problem that either break points are not hit even though the code *was* using that line or running with break point set hung the session even though no code changed.
When session hung could stop debugging and regain control.

Which sounds like it was caching previous code and that was not where the break point was really set

New Windows 10(64bit) with Visual studio 2015 and PowerShell tools from vsix downloaded from https://visualstudiogallery.msdn.microsoft.com/c9eb3ba8-0c59-4944-9a62-6eee37294597

Visual Studio 2015 Enterprise running as administrator. Code part of TFS source controlled project.

**Comment by adamdriscoll** [comment]
Could you please post or upload a log when this happens? 

https://github.com/adamdriscoll/poshtools/wiki/Debugging-PowerShell-Tools-for-Visual-Studio
