### ISSUE TITLE
Can't open files with .sql extension

### ISSUE THREAD

**Issue by savantes1** [adamdriscoll/poshtools#424]
I am currently using Microsoft Visual Studio Professional 2015 Version 14.0.24720.00 Update 1 with version 3.0.323 of PowerShell Tools for Visual Studio 2015. While working with a PowerShell Script Project, I've added an existing file to the project with the .sql extension. The file appears to have been added to the project and shows up in the solution explorer. However, when I try to open it I get the following error:

![image](https://cloud.githubusercontent.com/assets/17598341/13474767/593303c0-e074-11e5-8a5c-b9fa4dd04c5d.png)

I've done a bit of experimenting and it appears that it only happens when the file has the .sql extension. When I change the file extension to something else, add it to the project, and then attempt to open it, everything works fine.

I write a lot of PowerShell scripts that make calls to stored procedures on SQL Server DBs. Having the ability to keep the stored procedure definition script as part of the solution would be extremely helpful.

Any assistance would be greatly appreciated. Thanks
##

**Comment by adamdriscoll** [comment]
Could you grab a log? 

https://github.com/adamdriscoll/poshtools/wiki/Debugging-PowerShell-Tools-for-Visual-Studio

**Comment by adamdriscoll** [comment]
That said, it should be pretty easy for me to repro :+1:

**Comment by savantes1** [comment]
Here's the log. Thanks for taking a look.

[log.txt](https://github.com/adamdriscoll/poshtools/files/155844/log.txt)

**Comment by adamdriscoll** [comment]
FYI, I can repro this just fine...will take a look soon.

**Comment by savantes1** [comment]
Great! I'm hoping it will be an easy fix :)

**Comment by savantes1** [comment]
Just hoping to get an update. Thanks!

**Comment by adamdriscoll** [comment]
I looked at it and it's not quite as easy as I thought it would be to fix. The service I'm using to open the editor is throwing an exception for some reason and I'm not quite sure why. Still investigating.

**Comment by adamdriscoll** [comment]
You can work around this by right clicking on the item, selecting Open With and then selecting the editor directly. 
![image](https://cloud.githubusercontent.com/assets/1256531/16963361/be5aabc2-4dbb-11e6-8423-bcd838553fe5.png)

**Comment by adamdriscoll** [comment]
Fixed with the project system upgrade.
