### ISSUE TITLE
Unable to execute script added as solution item

### ISSUE THREAD

**Issue by whut** [adamdriscoll/poshtools#426]
The right-click "Execute as script" option does not work for PowerShell scripts added as solution item. It works when script is added to some project, but not when added directy to solution, for example to the default "Solution Items" folder.

It worked long time ago as I used this functionality to start [psake](https://github.com/psake/psake) scripts. I first observed the issue when reporting #387. It was closed then as the exception occuring when parsing psake.ps1 file was fixed. Still I wasn't able to run psake. Today finally I found the root cause: "Solution Items" folder.

**Steps to reproduce**
1. Right click on a solution node in Solution Explorer -> Add -> Existing item... and point to some simple PowerShell script
2. Right click in the script and select "Execute as script"

**Expected result**
Script executes, debugger gets attached, output visible in Output tool window

**Actual result**
Nothing happens

**Comment by jacargentina** [comment]
Same here. Any soon fix?

**Comment by Sylvryd** [comment]
Same here. I use the powershell scripts as a solution file to easily access but not part of a specific project. It would be very helpful to get this working as a solution item
