### ISSUE TITLE
Insert Snippet Not Functioning Correctly

### ISSUE THREAD

**Issue by RickFlist** [adamdriscoll/poshtools#437]
Hello!

I love the PowerShell Tools for VS 2015. Thanks so much for creating this!!

I'm having problems inserting snippets. They are just getting cut off. I hit CTRL+K, CTRL+X, select the snippet, and hit enter, and I get the contents of Bad.Snippet.Insert.ps1.

I've included Quick-Function.snippet, the snippet file VS is referencing as well.

The snippet was built in Snippet Manager 4

 (https://bytecookie.wordpress.com/snippet-manager/) as a PowerGUI snippet

[Bad.zip](https://github.com/adamdriscoll/poshtools/files/262050/Bad.zip)

**Comment by adamdriscoll** [comment]
@RickFlist I repro'd this but it looks like you just need to add another $ in front of the argument on line 13 in your snippet.

![image](https://cloud.githubusercontent.com/assets/1256531/15944578/d1fb6f40-2e53-11e6-855f-d64f4c09160b.png)

[Quick-Function.txt](https://github.com/adamdriscoll/poshtools/files/307821/Quick-Function.txt)
