### ISSUE TITLE
Snippets Does Not Honor Multiple Placeholders

### ISSUE THREAD

**Issue by RickFlist** [adamdriscoll/poshtools#438]
If I have a snippet with multiple placeholders, during insertion only the first one is honored. The rest are ignored.
##

**Comment by adamdriscoll** [comment]
I can't repro this: https://www.youtube.com/watch?v=jznd7uGUjQ0&feature=youtu.be

**Comment by RickFlist** [comment]
!?!?!?!

I just tried. Fresh install of Windows 10 Ent x64, fresh install of VS2015 Ent. Configured Snippets, created a new PowerShell project and attempted to insert snippet.  Here's what I got

https://youtu.be/fO8jnAGoBvU

**Comment by adamdriscoll** [comment]
Can you post the snippet that you tried to insert? Did you make it yourself?

**Comment by adamdriscoll** [comment]
Closing since I haven't heard back. Feel free to re-open.
