### ISSUE TITLE
GUID in manfist template is hardcoded

### ISSUE THREAD

**Issue by bgelens** [adamdriscoll/poshtools#453]
because the GUID 'bd4390dc-a8ad-4bce-8d69-f53ccf8e4163' is hardcoded in the manifest template. A lot of modules in the PSGallery now have this GUID. The GUID needs to generate dynamically when a project is created instead of hard coded.

**Comment by KirkMunro** [comment]
Wait, so this is a PoshTools issue? How did that happen @adamdriscoll? o_O

;)

**Comment by adamdriscoll** [comment]
Wahoh...I'll have to fix this ASAP!
