### ISSUE TITLE
Performance PESTER test execution

### ISSUE THREAD

**Issue by hometm** [adamdriscoll/poshtools#459]
I'm using POSHTOOLS (V 3.0.399) in combination with PSTER (V 3.4.1), VS2015SP2 and Powershell (V3). 

My VS2015 sollution contains one Script and one TestScript. The TestScript contains about ten tests and mocks every Script-Action away. 

I monitored, that the execution time of the TestScript very much:
- If the tests are started by VS2015 green "Debug" triangle, the execution takes about 3 seconds
- If the tests are started by VS2015 Test explorer, the execution takes about 3 minutes
- If the tests are started by VS2015 DeveloperPrompt with `"vstest.console /UseVsixExtensions:true [TestScript]"` it tooks also 3 minutes. It seems like, there is a "Sleep" between performing the tests

The test results between the three start options are the same.

For my plans, I need the execution of many many tests by vstest.console. How can I speed this execution up?

Thank you
Tobias
##

**Comment by adamdriscoll** [comment]
Can you enable logging? I haven't seen this before.

**Comment by hometm** [comment]
Now, I've got 19 Tests (19 Describe blocks each has 1 It block, 17 passed, 1 failed, 1 skipped) I enabled the loging, inside the loggings, the VS2015 is visible. But the test execution via vstest.console doesn't appear.
[log_bac.txt](https://github.com/adamdriscoll/poshtools/files/389944/log_bac.txt)

Vstest.console takes for the same operation about 6.7 minutes (20sec per test). 

My observation:
- Inside the vstest.console trx output file, time of start-test is equal to end-test, between two tests, there is a space of 20 seconds. This behaviour is independent of using the /Logger: option
- in console, the 'lost' 20seconds appear between line 'Passed...' and line 'Information'

`Passed   VSTestExecuteTestDLL.Test-Assemblies.RunNotSeparately_with_valid_parame
ters_throws_nothing
Information:`

**Comment by adamdriscoll** [comment]
Hello, could you please show me an example of the tests you are running? When I run 10 tests in the Test Explorer window it finishes under 3 seconds. 
![image](https://cloud.githubusercontent.com/assets/1256531/25655242/e4c01186-2fb9-11e7-804a-8a2a98bcfec1.png)
