### ISSUE TITLE
How can I run scripts as an administrator

### ISSUE THREAD

**Issue by MCKRUZ** [adamdriscoll/poshtools#461]
Can someone please tell me how this is done?

**Comment by guitarrapc** [comment]
I'm always elevating Visual Studio it self.

**Comment by MCKRUZ** [comment]
I did, no love.

**Comment by adamdriscoll** [comment]
We are just kicking off another process that contains the PowerShell host so if you elevate Visual Studio, the host process should be elevated as well. Can you check in taskman to make sure this is the case? 

![image](https://cloud.githubusercontent.com/assets/1256531/17377079/deaadf96-597d-11e6-9f05-744bd720beb2.png)

**Comment by MCKRUZ** [comment]
I got it.  User error. J  Thx

**Comment by adamdriscoll** [comment]
Good deal :)
