### ISSUE TITLE
Pester Tests : Describe block with a variable in the name does not show up on Test explorer

### ISSUE THREAD

**Issue by srininori** [adamdriscoll/poshtools#466]
I am new to posting issues here. Sorry if I am not posting at the right place.
I am trying to integrated my pester tests with posh tools. What I noticed is that if I have a variable in the describe block, tests aren't showing up on Test explorer.

Eg: 

Below does not show up on Test explorer.
$module = "MyModule"
Describe "$module Tests" {
    It "exists"{
        "Hello I am here" | Should BeLike "Hello *"
    }
}

![image](https://cloud.githubusercontent.com/assets/8906060/17942155/38694ff4-6a04-11e6-9e67-633117f41072.png)

Below shows on Test explorer.
Describe "Tests" {
    It "exists"{
        "Hello I am here" | Should BeLike "Hello *"
    }
}

![image](https://cloud.githubusercontent.com/assets/8906060/17942192/6162b562-6a04-11e6-94f4-a464623448fd.png)
##

**Comment by adamdriscoll** [comment]
Duplicate of #456
