### ISSUE TITLE
How do you do script deployment with VS and PS tools?

### ISSUE THREAD

**Issue by artisticcheese** [adamdriscoll/poshtools#471]
Hello,

Is there an option to have scripts deployed to specific location on demand like some other PS editors provide? To be clear I want to provide a specific place on network (or local FS) where I'd like script to be deployed once I'm done fixing/editing it. 
##

**Comment by asklar** [comment]
same/related to issue #321

**Comment by adamdriscoll** [comment]
Pre and post build scripts and MSBuild support will be coming in the June release.
