### ISSUE TITLE
Double-Click SQL File Fails To Open, But Right-Click | Open Works

### ISSUE THREAD

**Issue by ronhowe** [adamdriscoll/poshtools#473]
I have a POSH project that (naturally) has my PowerShell scripts.

I also want to have the project include some SQL scripts that I need and maintain in source control with the project.

When I double-click a SQL script, I get an error:

Microsoft Visual Studio
Value does not fall within the expected range.

However, I can successfully right-click on the SQL script and click Open.

**Comment by adamdriscoll** [comment]
Duplicate of #424
