### ISSUE TITLE
Multiple debug on same script keep old variables

### ISSUE THREAD

**Issue by RobDesideri** [adamdriscoll/poshtools#474]
If you debug a script more times, PowerShell session can keep variables at precedent state.
I have found a solution a this: 
execute a `rv * -ea SilentlyContinue; rmo *; $error.Clear(); cls` in PowerShell Interactive Windows in VS.
Can you implement an automated _"session cleaning"_ before execute debug?

**Comment by adamdriscoll** [comment]
There is an option you can enable now that does this.
