### ISSUE TITLE
Pester Test file with - "hyphen/minus" in the name doesn't show up in Test Explorer

### ISSUE THREAD

**Issue by espoelstra** [adamdriscoll/poshtools#477]
I was having some trouble with the new Pester option from Solution Explorer so I used New-Fixture from Pester, and while it allowed me to put a hyphen in the filename, the Test Explorer never showed/ran the file. Removing the hyphen allowed it to run the test file and show the individual function names.

**Comment by adamdriscoll** [comment]
@espoelstra Could you please show me an example? This seems to work for me.
![image](https://cloud.githubusercontent.com/assets/1256531/25655122/660118e0-2fb9-11e7-824a-cf62955ac2be.png)
