### ISSUE TITLE
add existing item crashes VS

### ISSUE THREAD

**Issue by mud5150** [adamdriscoll/poshtools#479]
When trying to use "add>existing item" to a psproj visual studio crashes with a System.AccessViolationException. I tried adding as well as adding as a link. 

[StackTrace.txt](https://github.com/adamdriscoll/poshtools/files/677744/StackTrace.txt)

**Comment by adamdriscoll** [comment]
Can you please try this on the most recent version? I haven't been able to reproduce the issue.
