### ISSUE TITLE
Installer isn't detecting 2017 RC?

### ISSUE THREAD

**Issue by Jaykul** [adamdriscoll/poshtools#488]
I don't understand what's happening here. I double-click the .vsix, and despite having both 2015 and 2017 RC installed, it won't install.

```
1/30/2017 3:15:02 PM - Microsoft VSIX Installer
1/30/2017 3:15:02 PM - -------------------------------------------
1/30/2017 3:15:02 PM - Initializing Install...
1/30/2017 3:15:03 PM - Extension Details...
1/30/2017 3:15:03 PM - 	Identifier         : PowerShellTools.VS2017
1/30/2017 3:15:03 PM - 	Name               : PowerShell Tools for Visual Studio 2017
1/30/2017 3:15:03 PM - 	Author             : Adam Driscoll
1/30/2017 3:15:03 PM - 	Version            : 3.0.426
1/30/2017 3:15:03 PM - 	Description        : A set of tools for developing and debugging PowerShell scripts and modules in Visual Studio.
1/30/2017 3:15:03 PM - 	Locale             : en-US
1/30/2017 3:15:03 PM - 	MoreInfoURL        : http://adamdriscoll.github.io/poshtools
1/30/2017 3:15:03 PM - 	InstalledByMSI     : False
1/30/2017 3:15:03 PM - 	SupportedFrameworkVersionRange : [4.5,)
1/30/2017 3:15:03 PM - 
1/30/2017 3:15:03 PM - 	SignatureState     : ValidSignature
1/30/2017 3:15:03 PM - 	SignedBy           : Adam Driscoll
1/30/2017 3:15:03 PM - 	Certificate Info   : 
1/30/2017 3:15:03 PM - 		-------------------------------------------------------
1/30/2017 3:15:03 PM - 		[Subject]       : CN=Adam Driscoll, O=Adam Driscoll, L=Madison, S=WISCONSIN, C=US
1/30/2017 3:15:03 PM - 		[Issuer]        : CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
1/30/2017 3:15:03 PM - 		[Serial Number] : 078345918A340BFD30AECF169FDE724D
1/30/2017 3:15:03 PM - 		[Not Before]    : 1/27/2017 7:00:00 PM
1/30/2017 3:15:03 PM - 		[Not After]     : 2/1/2018 7:00:00 AM
1/30/2017 3:15:03 PM - 		[Thumbprint]    : F2BEF33F6DD732BBAE4DD927A5BB010A93A49BD5
1/30/2017 3:15:03 PM - 
1/30/2017 3:15:03 PM - 	Supported Products : 
1/30/2017 3:15:03 PM - 		Microsoft.VisualStudio.IntegratedShell
1/30/2017 3:15:03 PM - 			Version : [15.0]
1/30/2017 3:15:03 PM - 		Microsoft.VisualStudio.Pro
1/30/2017 3:15:03 PM - 			Version : [15.0]
1/30/2017 3:15:03 PM - 
1/30/2017 3:15:03 PM - 	References         : 
1/30/2017 3:15:03 PM - 		-------------------------------------------------------
1/30/2017 3:15:03 PM - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
1/30/2017 3:15:03 PM - 		Name         : Visual Studio MPF 11.0
1/30/2017 3:15:03 PM - 		Version      : [11.0]
1/30/2017 3:15:03 PM - 		MoreInfoURL  : 
1/30/2017 3:15:03 PM - 		Nested       : No
1/30/2017 3:15:03 PM - 
1/30/2017 3:15:03 PM - Signature Details...
1/30/2017 3:15:03 PM - 	Extension is signed with a valid signature.
1/30/2017 3:15:03 PM - 
1/30/2017 3:15:03 PM - Searching for applicable products...
1/30/2017 3:15:03 PM - Found installed product - Microsoft Visual Studio Enterprise 2015
1/30/2017 3:15:03 PM - Found installed product - Microsoft Visual Studio Professional 2015
1/30/2017 3:15:03 PM - Found installed product - Microsoft Visual Studio Community 2015
1/30/2017 3:15:03 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
1/30/2017 3:15:03 PM - Found installed product - Global Location
1/30/2017 3:15:03 PM - Found installed product - ssms
1/30/2017 3:15:03 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by adamdriscoll** [comment]
@Jaykul Just checking...you downloaded the PowerShellTools.15.0.UserInstallable.vsix from the release page?

**Comment by Jaykul** [comment]
Yeah. I'll try it again on my personal desktop right now...

**Comment by Jaykul** [comment]
On my desktop it detected 2017 and installed without problems (and did _not_ attempt to update 2015). I'll have a look on my work laptop again tomorrow to see if I can figure out what went wrong.

**Comment by gratisal** [comment]
Don't know if this helps anyone, but I got an error about an "invalid manifest" and solved it by directing Windows to open the Vsix file with "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VSIXInstaller.exe" - rather than the "Visual Studio version selector" which is the default.

**Comment by mtniehaus** [comment]
I did successfully install the VS2017 Beta 3 package with Visual Studio 2017 RC.  It initially failed when I downloaded just the PowerShellTools.15.0.vsix, but when I also downloaded the PowerShellTools.VS2017.json it worked fine.  Maybe that was just luck :-)

**Comment by whiskeyjay** [comment]
Starting from VS2017 RC4 which is available at the time of writing, PowerShell Tools for VS2017 (yes the extension built specifically for VS2017, not the VS2015 one) is available in the VS Installer. I added a [Wiki page](https://github.com/adamdriscoll/poshtools/wiki/Installing-PowerShell-Tools-in-Visual-Studio-2017) with installation instructions. The version comes with VS installer contains the exact same bits as in the Beta 3 version published on GitHub, and will be upgradable from the Visual Studio Marketplace when a newer version is published there.

**Comment by mtniehaus** [comment]
Ah, that's what I was missing.  First, realizing that what gets installed from the http://visualstudio.com site is indeed RC4.  And second, that you need to choose the PowerShell items from within the VS2017 installer.

However, that still doesn't appear to have worked - no issues reported by the VS2017 installer, but I still can't open the existing PowerShell solutions from within VS, reports the solution is "incompatible."

**Comment by mtniehaus** [comment]
Using the VS2017 installer to remove and then re-add the item worked fine, now I can open my existing PowerShell solutions.

**Comment by adamdriscoll** [comment]
Can you guys try this version of PoshTools? 

https://marketplace.visualstudio.com/items?itemName=AdamRDriscoll.PowerShellToolsforVisualStudio2017

**Comment by Jaykul** [comment]
Worked for me.

--
Joel "Jaykul" Bennett
http://HuddledMasses.org
PowerShell MVP, Software Dev., Speaker
585-563-9632 <//1-585-563-9632> | Jaykul @ GitHub
<https://github.com/jaykul> | Twitter <https://twitter.com/Jaykul> | Linked
*In* <http://www.linkedin.com/in/jaykul/> <http://PowerShellGroup.org>
