### ISSUE TITLE
Will I run into tabbing problems with this product?

### ISSUE THREAD

**Issue by festus1973** [adamdriscoll/poshtools#489]
One question I wanted to ask before downloading and installing.

The reason I'm looking for an alternate PowerShell editor to ISE is because in ISE, there's no way to turn off tab-completion. I want the tab key to actually insert a tab instead of launching Intellisense. Is this product plagued by the same problem? Just didn't want to waste time installing if I'd end up facing the same issue.

**Comment by adamdriscoll** [comment]
Tab works as a tab. Ctrl + Space should open IntelliSense.

**Comment by festus1973** [comment]
Sweet! I'll give it a try.
