### ISSUE TITLE
Powershell tools are prompting for install -- already installed

### ISSUE THREAD

**Issue by webbexpert** [adamdriscoll/poshtools#495]
Powershell tools were already installed (notable, upgraded from 2017 RC to 2017)
However, the editor tool tip indicates that its 'Available' (implying that its not installed)
Attached is a screenshot
![untitled](https://cloud.githubusercontent.com/assets/6935487/23673969/1847be2c-0329-11e7-96d4-480fc7dc0d26.png)
Hope it helps!

**Comment by adamdriscoll** [comment]
Can you please uninstall your current version of PoshTools and install this one? 

https://marketplace.visualstudio.com/items?itemName=AdamRDriscoll.PowerShellToolsforVisualStudio2017

**Comment by adamdriscoll** [comment]
This is now fixed with: https://marketplace.visualstudio.com/items?itemName=AdamRDriscoll.PowerShellToolsforVisualStudio2017-18561
