### ISSUE TITLE
Debug C# DLL

### ISSUE THREAD

**Issue by asumner** [adamdriscoll/poshtools#496]
Hi, Am I supposed to be able to step through my powershell script and when it hits one of my commandlets jump into the c#? I have not been able to do it. It is not written anywhere I can find that it is supposed to or not supposed to be able to step into the c# code like I normally can by attaching to the Powershell_Ise. Is is purely for Powershell debugging in that instance?

Kind Regards
Anthony

**Comment by StingyJack** [comment]
Do you have the correct pdb, and have you disabled "Just My Code"?

**Comment by adamdriscoll** [comment]
You should be able to attach to a process and step through both. I haven't tried it in some time but it is possible. StingyJack is right that you need to make sure you have the correct PDBs and Just My Code disabled.
