### ISSUE TITLE
PowerShell Tools for VS 2017 not loading.

### ISSUE THREAD

**Issue by BenCamareno** [adamdriscoll/poshtools#497]
I've upgraded from VS 2015 to 2017, and now PowerShell Tools won't load in the new VS 2017. 
And when I try to get it from the Extensions, PoSh tools doesn't come up at all.

**Comment by sheldonhull** [comment]
I could run a script, open a powershell project, but I could not get command explorer or interactive window to open either.

**Comment by mgreenegit** [comment]
Linking to relevant issue filed on visualstudio.com:
https://developercommunity.visualstudio.com/content/problem/24658/powershell-tools-support-for-vs-2017-1.html

**Comment by savantes1** [comment]
Same deal for me...
Just installed VS2017 Pro and tried to install extension from VS, but not showing up. Also, noted that the PowerShell Interactive Window isn't even available in the Other Windows list.

Here are my specs:
Visual Studio Professional 2017
VisualStudio/15.0.0+26228.9

**Comment by JulienFloris** [comment]
Same Issue, powershell Command feature will not start. 
Windows 10 Enterprise, Clean install ( Up to date  18-03-2017) as a Virtual Machine. 
Visual Studio 2017 Pro, Clean install with Azure, .NET and powershell addon.
---------------------------------VS Info---------------------------------------------
Microsoft Visual Studio Professional 2017
Version 15.0.26228.9 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Professional

Visual Basic 2017   00369-60000-00001-AA547
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA547
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA547
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.6.00209.10
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30223.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50127.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.1.1.4
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Hive Query Language Service   2.2.5000.0
Language service for Hive query

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.1.5.0
TypeScript tools for Visual Studio

**Comment by knilecrack** [comment]
Same thing on Win build 15063

**Comment by hcsas** [comment]
Build 3.0.488 seems to work, on Community anyway. https://ci.appveyor.com/project/adamdriscoll/poshtools/build/3.0.448

**Comment by adamdriscoll** [comment]
Could you guys please try this build: https://ci.appveyor.com/project/adamdriscoll/poshtools-0wrw6/build/3.0.482

**Comment by BenCamareno** [comment]
@adamdriscoll 
Just tested build 3.0.482 and it works on Visual Studio Pro  2017.
![vspstools_482](https://cloud.githubusercontent.com/assets/20937332/24534989/095e2926-161d-11e7-91f0-50d50c76c952.jpg)

Thanks,

Ben

**Comment by adamdriscoll** [comment]
I'm going to close this. Please feel free to re-open if you experience issues.

**Comment by adamdriscoll** [comment]
Anyone that installed a build between 428 and 499, please uninstall and install this: https://marketplace.visualstudio.com/items?itemName=AdamRDriscoll.PowerShellToolsforVisualStudio2017-18561

Upgrades will now work as expected.

**Comment by koverus** [comment]
I had to open up a command prompt window and type powershell then enter.  Then restarted visual studio and everything started working.
