### ISSUE TITLE
Receive Not all privileges or groups assigned to the caller error when installing

### ISSUE THREAD

**Issue by mkenyon2** [adamdriscoll/poshtools#504]
The VSIX Installer returns:
>Not all privileges or groups referenced are assigned to the caller
at the end of the install.

I have VS 2015 and 2017 installed.

I'm running Powershell 5.1.14393.953

**Comment by adamdriscoll** [comment]
Could you get a VSIX installer log? Which version of PoshTools are you installing?

**Comment by mkenyon2** [comment]
Looking for the logs, where would I find them?
I am running the current tools from here: https://marketplace.visualstudio.com/items?itemName=AdamRDriscoll.PowerShellToolsforVisualStudio2017-18561

**Comment by adamdriscoll** [comment]
Logs go to %TEMP% by default. You can run the vsixinstaller.exe by hand if you want more control. It's in "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VSIXInstaller.exe"

> 
> ---------------------------
> VSIX Installer
> ---------------------------
> Path to vsix file '/?' is invalid or you don't have required access permissions. Please check the path is valid and you have required access permissions.
> 
> 
> 
> Usage: VSIXInstaller.exe [/quiet] [/norepair] [/admin] [/skuName:name /skuVersion:version] [/logFile:filename] </uninstall:vsixID | vsix_path>
> 
> 
> 
>     - OPTIONS -
> 
> 
> 
> /quiet
> 
> Suppresses the UI. Short form is '/q'.
> 
> 
> 
> /norepair
> 
> Disables repair support of VSIX Installer and forces the VSIX Installer to fail when the extension is already installed. Short form is '/nr'.
> 
> 
> 
> /admin
> 
> The extension will be installed to the admin extensions location. Short form is '/a'.
> 
> 
> 
> /skuName:<name>
> 
> The name of the application to which to install or uninstall the extension. Must be used with /skuVersion. Valid values include:
> 
> - Enterprise - (Visual Studio Enterprise Edition)
> 
> - Ultimate - (Visual Studio Ultimate Edition)
> 
> - Premium - (Visual Studio Premium Edition)
> 
> - Pro - (Visual Studio Professional Edition)
> 
> - Community - (Visual Studio Community Edition)
> 
> - IntegratedShell - (Visual Studio Shell - Integrated Mode)
> 
> - VSWinExpress - (Visual Studio Express for Windows)
> 
> - VSWinDesktopExpress - (Visual Studio Express for Windows Desktop)
> 
> - VWDExpress - (Visual Studio Express for Web)
> 
> Isolated Shell names may also be specified. Short form is '/s'.
> 
> 
> 
> /skuVersion:<version>
> 
> The version of the application to which to install or uninstall the extension, in the form major.minor[.build[.revision]]. Must be used with /skuName. Short form is '/v'.
> 
> 
> 
> /logFile:<filename>
> 
> Specifies the filename to be used for logging. This file will be appended to if it already exists. Logs will always be placed in %TEMP%. If this is not specified, or is invalid, a filename will be generated. Short forms are '/log' and '/l'.
> 
> 
> 
> /uninstall:<vsixID>
> 
> Uninstalls the extension with the specified identifier. If /skuName and /skuVersion are not specified, the extension will be uninstalled from all products that contain the extension with the corresponding identifier. Short form is '/u'.
> 
> 
> 
>     - ARGUMENTS -
> 
> 
> 
> <vsix_path>
> 
> Path to a valid .vsix file. This argument is invalid when /uninstall is specified.
> ---------------------------
> OK   
> ---------------------------
> 
> 
>

**Comment by mkenyon2** [comment]
The log said:
```
4/24/2017 1:43:17 PM - The extension with ID 'PowerShellTools.VS2017' is not installed to Visual Studio Professional 2017.
4/24/2017 1:43:17 PM - Microsoft.VisualStudio.ExtensionManager.RequiresAdminRightsException: You must have administrative privileges to install using the /admin switch.
   at VSIXInstaller.App.RequestElevation()
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

I ran the VS developer command prompt in Administrator mode, then ran:
```
vsixinstaller /admin C:\Users\userName\Downloads\PowerShellTools.15.0.vsix
```

And was able to install it.

**Comment by adamdriscoll** [comment]
Could be. The VSIXInstaller should prompt for elevation if the extension requires it but maybe there is some issue with certain configurations where that does not happen. I will look into it a bit.

**Comment by adamdriscoll** [comment]
I'll close this unless you run into the problem again. Feel free to open if this is the case.
