### ISSUE TITLE
Powershell Tools Project ignores Architecture / CLR Version settings; does not save requirements

### ISSUE THREAD

**Issue by bcwtw** [adamdriscoll/poshtools#506]
Visual Studio 2015 (various environments -- Update 1 and Update 3).
Powershell tools version: 3.0.399
Debugging SharePoint 2010 powershell scripts (which require x64, Powershell V2, .net 3.5).

Symptoms:
A) When in the debugger (e.g. F5 in visual studio), when I get to a SharePoint cmdlet, under output I see, e.g.:
 [ERROR] Get-SPWebApplication : Microsoft SharePoint is not supported with version 
[ERROR] 4.0.30319.42000 of the Microsoft .Net Runtime.
B) When I close and reopen the Powershell Tools solution, various settings under "Requirements" are missing.  For example, CLR version never saves between opening/closing the project.  Sometimes x64 is replaced with MSIL.  Powershell version (2) does not save.
C) I cannot attach the debugger to SharePoint Management console (e.g. the Powershell V2 / .net 3.5 console)

**Comment by adamdriscoll** [comment]
PoshTools requires PowerShell v3. The Requirements page on the project settings was for module manifests only and doesn't actually dictate the version of .NET or PowerShell that is being loaded. You can switch between x64 and x86 architectures in the Options for PowerShell Tools.

**Comment by adamdriscoll** [comment]
That said, those settings should be persisted to the project.

**Comment by bcwtw** [comment]
Okay, that makes sense.  Powershell v3 requires .net 4, so that explains that.

Maybe some text on the Properties menu / Requirements tab indicating "Settings on this tab apply to module manifests only"?

P.S. Wonderful extension.  Been using with newer environments without issue.

**Comment by adamdriscoll** [comment]
Thanks! I plan on fixing up the property pages so they work as expected and will try and make sure it's obvious what they are intended for. Thanks for the feedback and glad you're digging it!
