### ISSUE TITLE
Object Reference When Trying to Debug in VS2015

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshtools#509]
After fixing the prereq issue by hand from #508, the extension installs into VS2015 but trying to run the debugger throws an Object Reference exception.

**Comment by jazmatician** [comment]
I have this same issue, except it came after I tried running as administrator to solve a different issue within my script. It didn't solve the issue, and now I keep getting this error, even when I do not run as administrator. I reinstalled the product, but it is still happening.
