### ISSUE TITLE
Extension is signed with an invalid certificate

### ISSUE THREAD

**Issue by Snicka** [adamdriscoll/poshtools#525]
Tried installing the tools from the "PowerShell Tools for Visual Studio are available. Install Now" link that pops up when I open a .ps1 file today on my new system, i'm running VS2015 Professional Update 2 and I clicked the link and downloaded the file and installed it. It fails with a certificate issue and says it is not applicable. 

After some digging I realized the link goes to the VS2013 version of powershell tools. The link may need to be fixed. Grabbing the correct version from the poshtools.com site fixed the issue

Install log for the curious:
[VSIXInstaller_5862d431-1a4f-41ee-9d4a-42c588d4dcb1.zip](https://github.com/adamdriscoll/poshtools/files/1026229/VSIXInstaller_5862d431-1a4f-41ee-9d4a-42c588d4dcb1.zip)

**Comment by adamdriscoll** [comment]
I just tried this and it appears to be downloading the 2015 version. Can you try this again? I think something happened on the Marketplace a could days ago...
