### ISSUE TITLE
Packaging a Windows Form as Executable

### ISSUE THREAD

**Issue by nickalleyne** [adamdriscoll/poshtools#526]
Hey Adam/others,

This is more relating to PoshTools Pro, but I figured I should check here as there is no separate repo/issue tracker at this time.

I am having an issue packaging a windows form as an executable with PoshTools Pro.  It is just a VERY basic program to test if the packaging works (checks if AD RSAT tools are installed, and combines 2 words from text boxes).  When I run the .ps1 it works fine, but when I package it, it looks like it is not packaging the "Form1.designer.ps1" as the Join-path, and $MainForm.ShowDialog() at the end both error out.

If I highlight multiple files (the Form1.ps1, Form1.designer.ps1, Form1.resx), but it does not allow me to "package as executable".

See the attached image (I am unable to capture the text as text, because it pops up and away so slowly).

![error](https://cloud.githubusercontent.com/assets/961432/26552853/f9e01cda-4456-11e7-9986-d1d79f165428.png)

**Comment by nickalleyne** [comment]
I should have added the following info (I did in a followup but must have forgot to hit the comment button):


Lines 30-32 (that have the errors):
. (Join-Path $PSScriptRoot 'Form1.designer.ps1')

$MainForm.ShowDialog()

Also keep in mind that I have not manually touched the code in "Form1.Designer.ps1" at all, it is all built automatically from the designer.

**Comment by adamdriscoll** [comment]
@nickalleyne Thanks for reporting this. I'll take a look!

**Comment by adamdriscoll** [comment]
@nickalleyne I moved this to the new PoshTools Pro issue repo.
