### ISSUE TITLE
Documentation on 'Snippets'?

### ISSUE THREAD

**Issue by ronbok** [adamdriscoll/poshtools#533]
How do you make a snippet using PowerShell Tools?  From https://poshtools.com there's mention of:  "Editor enhancements like IntelliSense, syntax validation and snippets make working with PowerShell in Visual Studio as native as the ISE."

**Comment by adamdriscoll** [comment]
@ronbok  I'll put it on my todo list. It doesnt exist at the moment.

**Comment by adamdriscoll** [comment]
@ronbok The documentation for Visual Studio snippets should cover PowerShell snippets. You can use the Code Snippet Manager to developer your own snippets. You can insert snippets by pressing Ctrl+K,Ctrl+X. 

More information can be found here: https://msdn.microsoft.com/en-us/library/ms165392.aspx?f=255&MSPPError=-2147217396
