### ISSUE TITLE
Generated manifest file contains incorrect RootModule sample

### ISSUE THREAD

**Issue by pblommendaal** [adamdriscoll/poshtools#540]
The sample RootModule value contains a reference to itself.  This will result in an error on building the module.

![2017-06-29_11-26-37](https://user-images.githubusercontent.com/2590039/27681377-55e3c8f8-5cbf-11e7-9362-f60893ef121c.png)

According to:
[How to Write a PowerShell Module Manifest](https://msdn.microsoft.com/en-us/library/dd878337(v=vs.85).aspx)

>Placing the name of a module manifest (.psd1) or a script file (.ps1) in this element will cause an error to occur.

**Comment by adamdriscoll** [comment]
Fixed
