### ISSUE TITLE
Import-Module persists between runs silently

### ISSUE THREAD

**Issue by jmarshall9120** [adamdriscoll/poshtools#545]
When I  Import-Module on a clean startup of visual studio running debug Import-Module works as expected.  However if I run my script again PSTVS does not read my module.  Instead it persists the first Import-Module behind the scenes (silently).  This can easily be verified by changing my module and retrying.   I've tried counteracting with a Remove-Module command, however it throws an error: 

```
[ERROR] Remove-Module : No modules were removed. Verify that the specification of 
[ERROR] modules to remove is correct and those modules exist in the runspace.
```

If i restart VS between runs it will read the Module on import, otherwise no.  

System:
   Windows 7 64bit
   VS 2015 Pro
   PowerShell Tools for Visual Studio 2015 v3.0.582

**Comment by adamdriscoll** [comment]
@jmarshall9120 Are you using Import-Module using the -Force parameter? You can also reset the PowerShell session between each run by switching on a setting in the options.
