### ISSUE TITLE
VSIX error on upgrading to version 3.0.585 in VS2017

### ISSUE THREAD

**Issue by DannyMeister** [adamdriscoll/poshtools#547]
Upon attempting to upgrade to the latest version today in Visual Studio 2017, VSIX reported a failure "Package 'Microsoft.VisualStudio.MinShell' failed to install"

My previous version was 3.0.427.

The log file is attached.

[VSIXInstaller_fea3fc5d-0897-484c-b955-dfb469caf157.log.txt](https://github.com/adamdriscoll/poshtools/files/1183511/VSIXInstaller_fea3fc5d-0897-484c-b955-dfb469caf157.log.txt)

Will provide further update after rebooting, as VS will now not launch until I reboot.

**Comment by DannyMeister** [comment]
After rebooting, Visual Studio would not launch.  I had to use the VS installer to repair my installation.  Most plugins are no longer installed or active.  PowerShell Tools does appear to be installed, but is still version 3.0.427.

I'm not sure whether this really has anything to do with PowerShell Tools or a VSIX/VS issue.

**Comment by adamdriscoll** [comment]
I have never seen this issue but appears to be a failed VS installer issue. I'm not really sure what MinShell is but can do some research and see if I can provide some suggestions.

**Comment by adamdriscoll** [comment]
@DannyMeister I never figured out what could have caused this. Are you still experiencing this issue?

**Comment by awaescher** [comment]
Well wow ... that package crashed my whole dev system with that same error message. A help advice telling my to repair that by using `InstallCleanup.exe -full` ([see here](https://developercommunity.visualstudio.com/content/problem/141712/cannot-uninstall-due-to-missing-componentpowershel.html)) just wiped off Visual Studio and all other components from my system.

Getting close to midnight and I am installing 22.57GB of Visual Studio & its tools now ...
