### ISSUE TITLE
Powershell interactive window - [System.Environment]::OSVersion.Version gives wrong OS build

### ISSUE THREAD

**Issue by muecom** [adamdriscoll/poshtools#548]
On my Windows 10, when I look at [System.Environment]::OSVersion.Version  in the interactive window I got this result:
Major  Minor  Build  Revision
-----  -----  -----  --------
6      2      9200   0 

but it should (from PS window):
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      15063  0

**Comment by adamdriscoll** [comment]
@muecom Does a regular PowerShell prompt give the correct version?

**Comment by muecom** [comment]
yes - the second part is from regular PS prompt - 10 0 15063 0
same on three computers (with different installations / W10 builds)

**Comment by adamdriscoll** [comment]
Thanks. I will take a look. That's very strange.

**Comment by ALIENQuake** [comment]
According to Microsoft this is intentional:
https://msdn.microsoft.com/windows/compatibility/operating-system-version-changes-in-windows-8-1?f=255&MSPPError=-2147217396
https://www.sapien.com/blog/2014/04/02/microsoft-windows-8-1-breaks-version-api/

**Comment by adamdriscoll** [comment]
Thanks. Closing as designed.
