### ISSUE TITLE
Posh Tools Pro missing form toolbar

### ISSUE THREAD

**Issue by joesstlouis** [adamdriscoll/poshtools#550]
For some reason when I add a powershell form I can't see any tools in my toolbox.  I can see the toolbox when I create projects other than powershell... I just can't see them using your addon.  It keeps telling me there are no usable controls in this group.  I've tried resetting the toolbox and deleting the toobox files to no avail.

Thanks
Joe

**Comment by adamdriscoll** [comment]
@joesstlouis I'm moving this to the PoshProTools repo
