### ISSUE TITLE
First user experience

### ISSUE THREAD

**Issue by steve4444** [adamdriscoll/poshtools#553]
This is my experience with the product. For sure there will be a next one in the future. This is how it went now.

Visual Studio advertises the product to me in a PS script window. I think, cool. After installing and heading to the script pane, I expect to find around some sort of PS console and/or execute-script button. My fault, I have to read the docs.

__Getting the docs__
On the Gallery page `Ctrl+F Doc` does not help. I see a GitHub link, go there. The same: no getting-started, no Doc/Man folders.  This time there is a link to the author's page. I am brought to a beautiful travel blog (sort of), advertising a paid version of the product. Google is my friend and I find (a 3rd product page and) a GitBook website with the docs. What about a BIG link on the very first project page to the docs website?

__First things first__
I happily find my PS console and the context menu. I am done. I can start debugging my script in VS. I try to click on the left bar to set a breakpoint without luck. Strange, the product is advertised as a debugger. Indeed the context menu shows a Breakpoint item. I click "Insert" but nothing happens, or better, when I run the script, it is stuck. Again my fault, read the docs.

__Local debugging and syntax highlighting__
There is a doc section: local debugging. It starts with a long how-to to attach to a local process... What? I just need a shortcut to a breakpoint. At this time, looking at the doc screenshots, I realise that the cool highlighting and glitters, which captured me in the first place, are missing in my case. My PS script pane has the same black-on-white theme of notepad.exe. 

I also see that I have already finished my second pomodoro session, without even starting to write a line. At the moment the context menu Open with PS ISE is the only effective option. But I will have a second attempt. The project is cool and surely, as the usage goes, the experience will get more streamlined.

**Comment by adamdriscoll** [comment]
Sorry for all the issues. I've updated the readme.md on this repo and the gallery page to point to the documentation. 

Sounds like we need a doc to the basics of debugging and it seems like you aren't getting the desired PoshTools experience in your environment. 

Can you help me out by getting a log and making sure you have the latest version of PoshTools installed? Can you also let me know what version of Visual Studio you are running? 

Enabling PoshTools logging: https://adamdriscoll.gitbooks.io/powershell-tools-documentation/content/diagnostics.html

Thanks
