### ISSUE TITLE
Debug starts Notepad

### ISSUE THREAD

**Issue by SapsHaven** [adamdriscoll/poshtools#558]
I am trying to debug a module.  When I execute Debug -> Start Debugging I briefly see a command window and then the module source code appears in a Notepad window.  I must be missing something.

**Comment by SapsHaven** [comment]
I should have included that I am using VS 2015.

**Comment by adamdriscoll** [comment]
@SapsHaven Are you trying to run a PSM1 file or PS1 file?

**Comment by SapsHaven** [comment]
Hi Adam,
Rookie mistake.  Ran debug on a module.  I’ve written a small ps1 file that calls the functions in my module, and debug works on that file, so all is well.

Many thanks for getting back to me.

Regards…

**Comment by adamdriscoll** [comment]
Glad it is working. Thanks, @SapsHaven!
