### ISSUE TITLE
Cut and Copy error in PowerShell Projects

### ISSUE THREAD

**Issue by jinglouMSFT** [adamdriscoll/poshtools#562]
This was reported by David Lant in Visual Studio feedback.
Visual studio 2017 

Open a PowerShell project and in the Solution Explorer, select a script file (.ps1).  Either pressing ctrl+X or ctrl+C or using the context menu to cut or copy the file produces an error message:  

Microsoft Visual Studio
Object reference not set to an instance of an object.
OK

**Comment by mrichman** [comment]
Same issue here.
