### ISSUE TITLE
Cannot find an overload for "AddRange" and the argument count: "0".

### ISSUE THREAD

**Issue by roggyuk** [adamdriscoll/poshtools#565]
When adding Items to any kind of selection object in form designer they are not displayed when run

![image](https://user-images.githubusercontent.com/19605498/30876902-e4a453de-a2ef-11e7-9e80-9a52834eb57d.png)

**Comment by roggyuk** [comment]
When re opening a saved project...

![image](https://user-images.githubusercontent.com/19605498/31308223-d32e8556-ab6a-11e7-9b39-b7a7a375f0d2.png)

**Comment by roggyuk** [comment]
Combo Items are empty

![image](https://user-images.githubusercontent.com/19605498/31308233-fee0b520-ab6a-11e7-9502-89ce03b9e470.png)

**Comment by adamdriscoll** [comment]
@roggyuk Sorry for the delay. The issue is resolved but I am working with MSFT to fix an issue with the build system. Once that is fixed I will post the new version.
