### ISSUE TITLE
Can not to install PoShTools 2017 Free on VS 2017 Express

### ISSUE THREAD

**Issue by kukucz** [adamdriscoll/poshtools#567]
Hi,
I have just downloaded **VS Express 2017 for Windows Desktop** and I want to install **PowerShell Tools for Visual Studio 2017** with this application.  My computer is behind corporate proxy so I have downloaded **PowerShellTools.15.0.vsix** file from Visual Studio Marketplace directly.

When I try to install **PowerShellTools.15.0.vsix** by double click I get information:

> 
> Visual Studio 2017 Desktop Express
>         The extension cannot be installed to this product due to prerequisites that cannot be resolved.

Windows 7 Enterprise x64, latest hotfixes.
$PSVersionTable:
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Is it planned to support for **VS Express 2017 for Windows Desktop** in the future?

**Comment by adamdriscoll** [comment]
Express doesn't support extensions like the other version of Visual Studio. VS Community 2017 would work for this case.
