### ISSUE TITLE
Package Exe With System.Management.Automation.Dll for portability

### ISSUE THREAD

**Issue by sheldonhull** [adamdriscoll/poshtools#570]
This may be completely wrong, but I believe if the System Management Automation dll for Powershell 5/5.1 was included as a resource, and the subsequent code executed from this, that you could run a powershell 5/5.1 script on a machine that has a lower version of powershell installed, as long as the code was executed through the management dll. 

This might be a way to provide cross version compatibility in the exe without the user having to install a later version. Has this been considered? Not sure all of what the packager is doing, but figured I'd throw this idea out there. I use an app for updating/installing apps called Ketarin, and they provided the powershell 5 dll in it, solving the issue for many I believe.

**Comment by sheldonhull** [comment]
Ok... well I dug into the output from the exe and see you _did_ include this dll. Not sure which version it is, but I'd ask if possible to allow selecting the desired version. For example, if my environment should all have .net 4.5 then I'd like to ensure I provide the latest version of powershell 5.1 dll instead of only allowing version 3, thus allowing classes, and other newer functionality.

**Comment by adamdriscoll** [comment]
The file that is being output is the reference assembly and not actually the full SMA assembly. It shouldnt have to be included and the EXE should work on PSv3-5. I will fix this issue but if you just copy your EXE to a machine running v5, you should be able to use classes and newer functionality.

**Comment by adamdriscoll** [comment]
Moved to the Pro Tools Repo
