### ISSUE TITLE
Strange Behavior when executing PS project - runs old state of script

### ISSUE THREAD

**Issue by rdavidian** [adamdriscoll/poshtools#572]
I started noticing strange behavior when running my powershell project in VS 2017.  My script will run fine for a while but then out of nowhere, I'll do some edits but when I run my project it seems to run an older state (prior lines of code) of the project even if I compile.  If I restart VS, the issue goes away for a while but will come back.  I've seen this on multiple projects.

VS 2017 15.4.1
Poshtools 3.0.552 (non-pro)

**Comment by adamdriscoll** [comment]
Have you used the "Reset PowerShell Session" option at all?

**Comment by rdavidian** [comment]
Adam - I'll try that option and see if it helps.  Thanks
