### ISSUE TITLE
Task log no longer colorizes errors

### ISSUE THREAD

**Issue by jinglouMSFT** [adamdriscoll/poshtools#579]
This is an issue reported through the VS feedback channel (issue 424239) by Mr. Sullivan.

In the past when a task emitted output preceded by ##vso[task.logissue type=error] the log viewer would highlight the line with red, and the scroll bar would show a red line to indicate error lines. We aren't seeing that any more...

**Comment by adamdriscoll** [comment]
This seems like a VSTS issue. @jinglouMSFT, can you provide any other info on how this is related to PoshTools?
