### ISSUE TITLE
Errors and exceptions in context don't fail the test run

### ISSUE THREAD

**Issue by thomas-worm-datev** [adamdriscoll/poshtools#588]
If there are errors/exceptions at code positions in Context blocks, which are not within the It block, the test run ist not recognized as a failed test run, i.e. vstest.console.exe returns that tests are successfully passed, so our gated checkin allows the checkin in case of failing tests.

**Comment by thomas-worm-datev** [comment]
sample code


```powershell
Describe "Some-Test" {
  Context "Produce error" {
    $null.MethodCallNotPossible()
    It "Should fail" {
     $false | Should Be $true
    }
  }
}

Describe "Some-Test2" {
  Context "Produce no error" {
    It "Should succeed" {
     $true | Should Be $true
    }
  }
}
```

results in a succeeded test run.

**Comment by adamdriscoll** [comment]
LGTM!
