### ISSUE TITLE
Add custom font file as Embedded Resource and include into exe?

### ISSUE THREAD

**Issue by ALIENQuake** [adamdriscoll/poshtools#592]
Hi,

Is there any possible way to add custom font file as "Embedded Resource" and include into exe during build/conversion of ps1 > exe?

It's basically a copy of Visual Studio functionality but for Powershell Form converted into exe.

**Comment by adamdriscoll** [comment]
I am working on implementing resource support so this should be possible soon.

**Comment by ALIENQuake** [comment]
@adamdriscoll Well, the initial reason for this enhancement was to be able to read/load a Font Resource into memory and set it for all application labels. After some experimentation, I fear that it might not be possible at all due the ps1>exe conversion.

ps1 code converted to exe:
`[System.Reflection.Assembly]::GetExecutingAssembly().GetName().Name
[System.Reflection.Assembly]::GetExecutingAssembly().Location`

will return:
![image](https://user-images.githubusercontent.com/365255/36065263-9c08495e-0e98-11e8-9b04-08d778ff2506.png)
while using pure c# exe, will return:

> FontFromRes2
C:\Users\ALIEN\Documents\Visual Studio 2017\Projects\FontFromRes2\FontFromRes2\bin\Debug\FontFromRes2.exe

I beat that this is because c# exe is native and ps1>exe is only a some kind of layer. But why i need GetExecutingAssembly? Because c# GetManifestResourceStream require it to read Font data from Embedded resource.

I can provide working c# code and the same code converted to Powershell but I think that it's lost case :(

**Comment by ALIENQuake** [comment]
Well, I was able to create workaround:

1. Convert font binary data to Base64 string, add this string as a simple variable into script (I know it's ugly)
2. Before loading Form, convert Font Data from Base64 and export as $env:\TEMP\FontName.TTF
3. Use 'AddFontFile' from System.Drawing.Text.PrivateFontCollection by simply providing $env:\TEMP\FontName.TTF

Now, all labels are getting my custom font.
