### ISSUE TITLE
Open Folder Support

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshtools#595]
https://blogs.msdn.microsoft.com/visualstudio/2016/04/12/open-any-folder-with-visual-studio-15-preview/

**Comment by adamdriscoll** [comment]
Implemented with #596

**Comment by ciberesponce** [comment]
But can you still not "run line"? Biggest reason I simplify my processes in VSCode vs VS

**Comment by pju55** [comment]
May I ask how to supply command line arguments?
I have followed the msdn link above but cannot dig out where to find the launch.json.
Suppose I just mess around ...
