### ISSUE TITLE
Case-sensitive file icons

### ISSUE THREAD

**Issue by theaquamarine** [adamdriscoll/poshtools#598]
This looks like a return of #397: when files are named with their extensions in anything other than lower case, they get the wrong icons. Renaming the files causes the correct icon to appear.
- Pester test files named "foo.tests.ps1" get the Erlenmeyer flask icon, but files name "bar.Tests.ps1"  do not. Pester's documentation names the files with a capital T, so this definitely seems wrong.

- Ditto mymodule.Psd1 and mymodule.Psm1

Possibly the comparisons in [PowerShellFileNode.cs](https://github.com/adamdriscoll/poshtools/blob/dev/PowerShellTools/Project/PowerShellFileNode.cs#L48) L40-50 should be case-insensitive?

VS 15.5.3, poshtools 3.0.585.

**Comment by adamdriscoll** [comment]
@theaquamarine Yeah, you are totally correct. Should be able to get that resolved for the January build.
