### ISSUE TITLE
SetSite failed for package [PowerShellToolsPackage] - VS 2012

### ISSUE THREAD

**Issue by Andy65** [adamdriscoll/poshtools#61]
The latest version (0.7.0) of the extension fails to load in Visual Studio 2012 with error above being recorded in the ActivityLog.xml file. The following other extensions are also loaded:
CodeMaid
Microsoft ASP.NET and Web Tools
NuGet Package Manager
Productivity Power Tools 2012
Team Foundation Sidekicks
Visual Studio Extensions for Windows Library for JavaScript
VSCommands for Visual Studio 2012
Web Essentials 2012

**Comment by adamdriscoll** [comment]
Glad that worked!

**Comment by Chakotay** [comment]
Hi there,

using visual studio 2013 ultimate update 4 on Windows 8.1 and got the message: 

SetSite failed for package [ProviderPackage] {5F2E5E42-4192-4D79-A0D8-1D881E808829} 80070005 - E_ACCESSDENIED VisualStudio 

is this the same problem? 

I tried the wmf 3 installer but it tels me this update is not for my computer. 

Please advice,

![naamloos](https://cloud.githubusercontent.com/assets/6230857/7584245/5f85c6c4-f89c-11e4-8b47-e570b0391966.jpg)

**Comment by siudeks** [comment]
Clearing the ComponentModelCache worked for me. Nice find @luckyducky!
