### ISSUE TITLE
Missing DLL System.Collections.Immutable?

### ISSUE THREAD

**Issue by mg07647** [adamdriscoll/poshtools#610]
Install-Module -Name PowerShellProTools

Import-Module PowerShellProTools
Import-Module : Could not load file or assembly 'file:///C:\Program Files\WindowsPowerShell\Modules\PowerShellProTools\1.3.0\System.Collections.Immutable.dll' or one of its dependencies. The system cannot find the file specified.

I tried downloading the DLL from NuGet and dropping it in the directory specified above but it did not solve the issue.

**Comment by mg07647** [comment]
Partial answer to may own question. After adding the DLL to the folder I should have used the Force parameter with Import-Module. That works.

Still means the file was initial missing from the installer.

**Comment by adamdriscoll** [comment]
This has been fixed in 1.4.0 version.
