### ISSUE TITLE
[Feedback]Console window hidden when starting console application

### ISSUE THREAD

**Issue by v-xuanzh** [adamdriscoll/poshtools#633]
Build number: 15.6.27428.2037
Product: Professional-2017
Producet Version: 15.6.6
Product branch: d15.6
Product language: en-us

The console window doesn't show when starting a console application (with or without debug) after starting any console application from within the powershell manager console.

Steps to reproduce it:

1. Create a new console application project
2. Add some code to write something to the console in the main method, for example:
 static void Main(string[] args)
 {
 Console.WriteLine("Help");
 Console.ReadLine();
 }
3. Debug the application, the console window pops up and shows the text and closes after pressing enter.
4. Open the powershell manager console and start any console application, for example: cmd /c dir
5. Debug the application, the console window doesn't show and the debugger stays blocked on the "Console.ReadLine();" line.

Invoking the Invoke-FixConsole after step 4 from the following module fixes the problem.
https://gist.github.com/romerod/d4828ab5d1f2367fe757f7249c8fec4d

**Comment by romerod** [comment]
@v-xuanzh I don't use this extension, sorry I wrote "powershell manager console" instead of "package manager console"
