### ISSUE TITLE
powershell tools not included in VS2017 installer anymore. why?

### ISSUE THREAD

**Issue by AdmiralSnyder** [adamdriscoll/poshtools#636]
here
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-preview-relnotes#-known-issues
it states that 
"The PowerShell tools component has been removed from Visual Studio setup. If you upgrade to Visual Studio update 8 preview 3 or later, the installed PowerShell tools is removed. If you want to continue using this component, install from Visual Studio gallery at PowerShell Tools for Visual Studio 2017."

i'm curious for the reasoning for that.

**Comment by waaromikniet** [comment]
I also see that it is gone from the 15.8 setup. Why is this removed from the Visual Studio installer?

**Comment by adamdriscoll** [comment]
The decision was made to remove the tool from the installer because it does not meet all the requirements for inbox extensions.
