### ISSUE TITLE
Intellisense for DSC

### ISSUE THREAD

**Issue by jole78** [adamdriscoll/poshtools#69]
This works in ISE but not sure what it would take to get support for the features/keywords offered by DSC in PS4. See screenshot below:

![image](https://f.cloud.github.com/assets/2247346/1961563/aef57130-8275-11e3-8fad-1d02933f2e82.png)

The main issue seems to lie within the **Configuration** keyword.

**Comment by AndreSayreMSFT** [comment]
Related to #84

**Comment by AndreSayreMSFT** [comment]
Closing out this issue as it's implemented in the other repo.  Thanks for reporting the issue!
