### ISSUE TITLE
Auto complete on new-object results in unexpected behavior

### ISSUE THREAD

**Issue by GaryRogers** [adamdriscoll/poshtools#73]
When creating a new object from installed .net libraries, auto-complete isn't behaving the way I'd expect. For example, when creating a new `System.Data.DataSet` Object:

``` powershell
$blah = New-Object System.Da [tab]
```

Results in:

``` powershell
$blah = New-Object System.System.Data
```

Not really a big deal, just an annoyance.

**Comment by HuanhuanSunMSFT** [comment]
IntelliSense works well here so I'll close this one.
