### ISSUE TITLE
Region tags recognized as comments

### ISSUE THREAD

**Issue by djgrijalva** [adamdriscoll/poshtools#81]
When using #Region in other ISE's it is collapsible just like functions are. With your tool, it just sees it as a normal comment line.

**Comment by AndreSayreMSFT** [comment]
Seems to have been implemented since this was reported!  Please holler if there's more to this that I'm missing.

![untitled](https://cloud.githubusercontent.com/assets/10080679/5660057/66625f80-96d0-11e4-9b0c-0da9d2611417.png)
