### ISSUE TITLE
Support DSC Scripts (64bit Support)

### ISSUE THREAD

**Issue by PaulDMurphy** [adamdriscoll/poshtools#84]
Currently when loading a PowerShell DSC file into the editor fails for lack of 64bit support.

To replicate the problem paste this code into the PoSh editor.

Configuration Genesis
{
	Node "localhost"
	{
		
	}
}

When you consider just how effective DSC is at managing and deploying systems failing to support 64bit PoSh is a critical flaw.

**Comment by AndreSayreMSFT** [comment]
Hi @PaulDMurphy 

We agree -- this is a very useful feature!  We're starting to work on this in our repo where it'll get subsequently merged into this repo.  

We're currently following the 'create a new process' path for getting around Visual Studio's 32/54 bit limitations.

You can follow along on our progress with these labels:

https://github.com/Microsoft/poshtools/labels/64-bit%20Debug%2FExecute
https://github.com/Microsoft/poshtools/labels/64-bit%20Intellisense

**Comment by AndreSayreMSFT** [comment]
Closing out this issue as we've got the 64-bit support going in the other repo.  Thanks for reporting this!
