### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by jrich523** [adamdriscoll/poshtools#89]
I feel like this is something im doing wrong, but i cant seem to get it to work.

install 0.7.2
seems to work fine, create a simple script and run it via F5, never breaks, just finishes

for($i =0;$i -lt 5;$i++)
{
	write-Host "im at $i"    #BP here
}

**Comment by AndreSayreMSFT** [comment]
Related to #138 and #145

**Comment by EricMSFT** [comment]
Issue was fixed in microsoft/poshtools repo.

**Comment by AndreSayreMSFT** [comment]
Closing out this issue as it's fixed in the other repo.  Thanks again for reporting this!
