### ISSUE TITLE
Need PowerShell console in Debug session

### ISSUE THREAD

**Issue by maximpashuk** [adamdriscoll/poshtools#93]
For now, Debug session supports only Locals and Call Stack.

This is not enough for effective debugging.
Then debugging I am not able to write something like "Test-Path $path1".

For this I need powershell interactive console like in PowerGUI.
I like PowerShell Tools for VS but I can't use until debug console will add.

**Comment by AndreSayreMSFT** [comment]
This has been fixed up! :)
